Repository myriadsocial/myriad-web, pull requests merged in 2021-12, with the labels that each got.

#695 MYR-1307: handle search pagination
  pages/home.tsx
  pages/searchresults.tsx
  src/components-v2/PostCreate/PostCreate.tsx
  src/components-v2/PostsList/PostsListContainer.tsx
  src/components-v2/Search/SearchResultContainer.tsx
  src/components-v2/Timeline/hooks/use-timeline.hook.ts
  src/lib/api/post.ts
  src/reducers/timeline/actions.ts
  src/reducers/timeline/reducer.ts
Labels: bug

#698 MYR-1073: update importers query
  src/lib/api/post.ts
Labels: bug, enhancement

#700 MYR-1073: check user agent exist on redirect mobile page
  pages/experience/[experienceId]/clone.tsx
  pages/experience/[experienceId]/edit.tsx
  pages/experience/[experienceId]/preview.tsx
  pages/experience/create.tsx
  pages/friends.tsx
  pages/home.tsx
  pages/index.tsx
  pages/maintenance.tsx
  pages/mobile.tsx
  pages/nft.tsx
  pages/notification.tsx
  pages/post/[postId].tsx
  pages/profile/[id].tsx
  pages/search.tsx
  pages/searchresults.tsx
  pages/settings.tsx
  pages/socials.tsx
  pages/socialtoken.tsx
  pages/topic/[type].tsx
  pages/wallet.tsx
  pages/welcome.tsx
Labels: bug, enhancement

#701 MYR-1112: fix comment downvote behaviour
  src/components-v2/PostDetail/hooks/use-comment-tabs.tsx
  src/components-v2/atoms/CommentDetail/CommentDetail.interface.ts
  src/components-v2/atoms/CommentDetail/CommentDetail.tsx
  src/components-v2/atoms/CommentList/CommentList.container.tsx
  src/components-v2/atoms/CommentList/CommentList.tsx
Labels: bug, enhancement

#702 fix compact scroll behaviour
  src/components-v2/Notifications/sidebar/Notifications.tsx
Labels: Improvement

#703 fixed search post
  src/lib/api/post.ts
Labels: Improvement

#704 minor fixing
  src/components-v2/FriendsMenu/FriendRequest.tsx
  src/components-v2/FriendsMenu/friend.style.tsx
Labels: Fix

#706 MYR-1329: handled limiting number of chars on input and fixed typo
  src/components-v2/SendTip/SendTip.tsx
Labels: Improvement

#708 Create dedicated embed page
  pages/embed.tsx
  src/components-v2/PostDedicated/PostDedicated.container.tsx
  src/components-v2/PostDetail/PostDetail.tsx
  src/components-v2/atoms/PostAction/index.tsx
  src/components-v2/atoms/PostHeader/index.tsx
  src/components-v2/atoms/PostHeader/postHeader.interface.ts
  src/components-v2/atoms/PostHeader/subHeader/post-sub-header.component.tsx
  src/components-v2/atoms/Voting/index.tsx
  src/components-v2/atoms/Voting/voting.interface.ts
  src/helpers/auth.ts
Labels: enhancement, Feature

#709 Fix import label
  src/components-v2/atoms/PostHeader/subHeader/post-sub-header.component.tsx
Labels: bug

#711 handled timeAgo on tip history
  src/components-v2/TipHistory/TipHistory.tsx
Labels: bug

#713 bug fixed error when back home from 404
  pages/404.tsx
Labels: bug

#714 MYR-1317: change gallery layout
  src/components-v2/PostDetail/PostDetail.tsx
  src/components-v2/PostEditor/PostRender.tsx
  src/components-v2/atoms/Gallery/Gallery.styles.ts
  src/components-v2/atoms/Gallery/Gallery.tsx
  src/components-v2/atoms/Gallery/util.ts
Labels: bug, Improvement

#715 MYR-1317: fix importer
  src/components-v2/atoms/Gallery/Gallery.tsx
  src/components-v2/atoms/PostHeader/subHeader/post-sub-header.component.tsx
Labels: bug

#716 created banner announcement
  src/components-v2/atoms/BannerStatus/BannerStatus.tsx
  src/components-v2/atoms/BannerStatus/banner.style.ts
Labels: Improvement

#719 Fix post detail & gallery
  pages/_app.tsx
  pages/index.tsx
  pages/post/[postId].tsx
  pages/profile/[id].tsx
  src/components-v2/atoms/Gallery/Gallery.tsx
  src/components-v2/atoms/LinkPreview/LinkPreview.tsx
Labels: bug

#723 handled mutual friend still hardcoded
  src/components-v2/FriendsMenu/FriendList.tsx
  src/components-v2/FriendsMenu/FriendMenu.tsx
  src/components-v2/FriendsMenu/FriendRequest.tsx
  src/components-v2/FriendsMenu/friend.style.tsx
  src/components-v2/FriendsMenu/hooks/use-friend-list.hook.ts
  src/components-v2/FriendsMenu/hooks/use-friend-request.hook.ts
  src/interfaces/friend.ts
  src/lib/api/friends.ts
Labels: bug, Fix, Improvement

#724 updated embed post link
  src/components-v2/PostDetail/PostDetail.tsx
  src/components-v2/atoms/PostAction/index.tsx
Labels: Fix

#726 fix match styling dropdown menu on create post
  src/components-v2/NSFWTags/NSFWTags.styles.ts
  src/components-v2/NSFWTags/NSFWTags.tsx
  src/components-v2/atoms/DropdownMenu/DropdownMenu.styles.ts
  src/components-v2/atoms/DropdownMenu/DropdownMenu.tsx
Labels: Fix

#727 added official account tooltip
  src/components-v2/Profile/ProfileHeader/index.tsx
Labels: Improvement

#730 Seperate build and deploy
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/deploy.yml
  .github/workflows/main.yml
  .github/workflows/publish-draft-release-candidate.yml
  .github/workflows/publish-draft-release.yml
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
Labels: CI

#729 fix toaster component
  pages/_app.tsx
  src/components-v2/atoms/ToasterSnack/ToasterSnack.tsx
  src/components-v2/atoms/ToasterSnack/index.ts
  src/components-v2/atoms/ToasterSnack/toaster-snack.interface.ts
  src/components-v2/atoms/ToasterSnack/toastersnack.style.ts
  src/hooks/use-polkadot-api.hook.ts
  src/hooks/use-toaster-snack.hook.ts
  src/interfaces/toaster-snack.ts
  src/reducers/index.ts
  src/reducers/toaster-snack/actions.ts
  src/reducers/toaster-snack/constants.ts
  src/reducers/toaster-snack/reducer.ts
Labels: Fix

#734 fix styling list item on account privacy
  src/components-v2/Settings/AccountSettings.tsx
  src/components-v2/Settings/Settings.styles.ts
Labels: Fix

#736 Filter primary social on profile
  pages/profile/[id].tsx
  src/components-v2/Notifications/sidebar/Notifications.container.tsx
  src/components-v2/Notifications/sidebar/Notifications.tsx
  src/components-v2/ProfileHeader/ProfileHeaderContainer.tsx
  src/components-v2/Socials/Socials.tsx
  src/components-v2/UserSocials/UserSocial.container.tsx
  src/components-v2/atoms/PostAction/index.tsx
  src/interfaces/social.ts
  src/lib/api/notification.ts
  src/lib/api/post.ts
  src/lib/api/social.ts
  src/reducers/notification/actions.ts
  src/reducers/notification/constants.ts
  src/reducers/notification/reducer.ts
  src/reducers/profile/actions.ts
  src/reducers/user/actions.ts
Labels: bug

#735 fix styling selected experience
  src/components-v2/ExperienceList/ExperienceList.tsx
  src/components-v2/atoms/SimpleCard/SimpleCard.style.ts
  src/components-v2/atoms/SimpleCard/SimpleCard.tsx
Labels: Fix

#739 change profile link path from comment
  src/components-v2/atoms/CommentDetail/CommentDetail.tsx
Labels: bug

#740 Introduce to new analytics
  .env-template
  next.config.js
  public/firebase-messaging-sw.js
  src/components-v2/template/Default/DefaultLayout.tsx
  src/lib/firebase.ts
Labels: Feature

#742 Fixed import firebase service
  .prettierignore
  src/lib/firebase.ts
Labels: Fix

#744 disable send direct tip when balance detail still empty
  src/components/FriendsMenu/FriendList.tsx
Labels: Improvement

#745 handle clear filter input after select people
  src/components/ExperienceEditor/ExperienceEditor.tsx
Labels: Fix

#748 created leaderboard airdrop
  pages/leaderboard.tsx
  src/components/Leaderboard/LeaderBoard.tsx
  src/components/Leaderboard/leaderboard.styles.ts
  src/components/Leaderboard/use-leaderboard-hook.tsx
  src/interfaces/user.ts
  src/lib/api/leaderboard.ts
Labels: good first issue

#750 add handle unsubscribe on experience detail
  src/components/ExperiencePreview/ExperiencePreview.container.tsx
  src/components/ExperiencePreview/ExperiencePreview.tsx
Labels: Fix

#749 fix infinite scroll on wallet transaction history
  src/components/HistoryDetailList/HistoryDetailList.tsx
  src/components/HistoryDetailList/HistoryDetailListContainer.tsx
  src/components/HistoryDetailList/history-detail-list.styles.ts
  src/hooks/use-transaction.hooks.ts
  src/reducers/transaction/actions.ts
  src/reducers/transaction/reducer.ts
Labels: Fix

#754 Add toaster on saving coin priority
  src/components/PrimaryCoinMenu/PrimaryCoinMenu.tsx
Labels: bug

#752 Update login UI
  package.json
  pages/api/auth/[...nextauth].ts
  pages/index.tsx
  src/components/ExperienceEditor/ExperienceEditor.tsx
  src/components/Login/Login.tsx
  src/components/Login/render/Accounts/Accounts.style.ts
  src/components/Login/render/Accounts/Accounts.tsx
  src/components/Login/render/Accounts/index.ts
  src/components/Login/render/Login/Login.style.ts
  src/components/Login/render/Login/Login.tsx
  src/components/Login/render/Login/index.ts
  src/components/Login/render/Options/Options.style.ts
  src/components/Login/render/Options/Options.tsx
  src/components/Login/render/Options/index.ts
  src/components/Login/render/Profile/Profile.style.ts
  src/components/Login/render/Profile/Profile.tsx
  src/components/Login/render/Profile/index.ts
  src/components/ProfileHeader/ProfileHeaderContainer.tsx
  src/components/template/Login/Login.styles.ts
  src/components/template/Login/Login.tsx
  src/helpers/auth.ts
  src/hooks/auth.hook.ts
  src/hooks/use-profile.hook.ts
  src/images/myriad-logo-black.svg
  src/images/network/binance.svg
  src/images/network/ethereum.svg
  src/images/network/polkadot.svg
  src/images/network/polygon.svg
  src/images/wallet/coinbase.svg
  src/images/wallet/metamask.svg
  src/images/wallet/polkadot.svg
  src/images/wallet/trust.svg
  src/lib/api/user.ts
  yarn.lock
Labels: Feature, Improvement

#753 Takeout facebook from social list
  src/components/SocialMediaList/use-social-media-list.hook.tsx
  src/components/Socials/Socials.tsx
Labels: bug

#755 Prevent uploading empty file
  src/components/atoms/Dropzone/Dropzone.tsx
Labels: bug

#751 implement token conversion in tip history
  src/components/BalanceDetailList/BalanceDetailList.tsx
  src/components/HistoryDetailList/HistoryDetailList.tsx
  src/components/MyWallet/MyWalletContainer.tsx
  src/components/PrimaryCoinMenu/PrimaryCoinMenu.tsx
  src/components/TipHistory/TipHistory.tsx
  src/helpers/balance.ts
  src/hooks/use-exchange-rate.hook.ts
  src/interfaces/exchange.ts
  src/lib/api/exchange.ts
  src/reducers/exchange-rate/actions.ts
  src/reducers/exchange-rate/constants.ts
  src/reducers/exchange-rate/reducer.ts
  src/reducers/index.ts
Labels: Improvement

#756 Remove duplicate error message
  src/reducers/user/actions.ts
Labels: bug

#757 fix add unsubscribe on experience menu item
  src/components/ExperienceList/NonSelectableExperienceList.tsx
  src/components/ExperienceList/SearchedExperienceList.tsx
  src/components/ExperienceList/SearchedExperienceListContainer.tsx
  src/components/ExperienceList/experience-list.interfaces.ts
  src/components/Profile/ExperienceTabPanel/ExperienceTabPanel.container.tsx
  src/components/Profile/ExperienceTabPanel/ExperienceTabPanel.tsx
  src/components/atoms/SimpleCard/NonSelectableSimpleCard.tsx
  src/components/atoms/SimpleCard/simple-card.interfaces.ts
Labels: Fix

#758 Change disabled icon
  src/components/Login/render/Options/Options.style.ts
  src/components/Login/render/Options/Options.tsx
  src/images/network/binance-disabled.svg
  src/images/network/ethereum-disabled.svg
  src/images/network/polkadot.svg
  src/images/network/polygon-disabled.svg
  src/images/wallet/coinbase-disabled.svg
  src/images/wallet/metamask-disabled.svg
  src/images/wallet/polkadot.svg
  src/images/wallet/trust-disabled.svg
Labels: Fix, Improvement

#760 fixed style and wording leaderboard page
  src/components/Leaderboard/LeaderBoard.tsx
  src/components/Leaderboard/leaderboard.styles.ts
  src/components/Leaderboard/use-leaderboard-hook.tsx
  src/components/atoms/Loading/LoadMore.tsx
  src/components/atoms/Loading/index.ts
  src/lib/api/leaderboard.ts
Labels: Fix

#761 Disable edit username
  src/components/Profile/edit/ProfileEdit.tsx
  src/components/template/Login/Login.styles.ts
Labels: Fix, Improvement

#762 Change select wallet order
  src/components/Login/render/Accounts/Accounts.style.ts
  src/components/Login/render/Options/Options.style.ts
  src/components/Login/render/Options/Options.tsx
  src/components/Login/render/Profile/Profile.style.ts
  src/components/template/Login/Login.styles.ts
Labels: Fix, Improvement

#763 fixed conversion styling
  src/components/PrimaryCoinMenu/DraggableBalanceCard.tsx
  src/helpers/balance.ts
Labels: Improvement

#764 fix showing image when edit experience
  src/components/ExperienceEditor/ExperienceEditor.tsx
  src/components/atoms/Dropzone/Dropzone.tsx
Labels: Fix

#765 handled hidden blocked user commented on other people's post
  src/components/Profile/ProfileHeader/ProfileHeaderContainer.tsx
  src/components/atoms/CommentDetail/CommentDetail.styles.ts
  src/components/atoms/CommentDetail/CommentDetail.tsx
  src/hooks/use-friends-hook.ts
Labels: bug, Improvement

#766 remove sort dropdown on experience
  src/components/ExperienceTabMenu/ExperienceTabMenu.tsx
  src/components/ExperienceTabMenu/ExperienceTabMenuContainer.tsx
  src/components/HeaderWithAction/HeaderWithAction.tsx
  src/components/HeaderWithAction/header-w-action.interfaces.ts
  src/components/Profile/ExperienceTabPanel/ExperienceTabPanel.container.tsx
  src/components/Profile/ExperienceTabPanel/ExperienceTabPanel.tsx
  src/components/Timeline/default.ts
Labels: Fix

#767 Update icon & post detail
  src/components/AddSocialMedia/AddSocialMedia.tsx
  src/components/ExperienceEditor/ExperienceEditor.tsx
  src/components/ExperiencePreview/experience.style.ts
  src/components/ExperienceTabMenu/ExperienceTabMenuContainer.tsx
  src/components/Login/render/Options/Options.tsx
  src/components/ProfileHeader/ProfileHeaderContainer.tsx
  src/components/SendTip/SendTip.tsx
  src/hooks/use-experience-hook.ts
  src/images/network/near.svg
  src/lib/api/post.ts
  src/reducers/timeline/actions.ts
  src/reducers/user/actions.ts
  src/reducers/user/constants.ts
  src/reducers/user/reducer.ts
Labels: bug, enhancement, Fix

#768 fix redirect notifaction on post tips
  src/components/Notifications/hooks/use-notification-list.hook.tsx
Labels: Fix

#769 fix handle clone on subscribed experience
  src/components/ExperienceEditor/ExperienceEditor.tsx
  src/components/Notifications/hooks/use-notification-list.hook.tsx
  src/components/atoms/Dropzone/Dropzone.tsx
  src/hooks/use-experience-hook.ts
  src/lib/api/experience.ts
  src/reducers/experience/actions.ts
Labels: Fix

#770 Disable register on empty username
  src/components/Login/render/Profile/Profile.tsx
Labels: bug

#771 Remove edit profile username helper text
  src/components/Profile/edit/ProfileEdit.tsx
Labels: bug

#772 fix experience card behavior on profile
  src/components/ExperienceList/NonSelectableExperienceList.tsx
  src/components/Upload/Upload.tsx
  src/components/atoms/Dropzone/Dropzone.tsx
Labels: Fix

#773 fix selecting option on post report
  src/components/Report/Report.tsx
  src/components/Search/SearchResultContainer.tsx
Labels: Fix

#774 MYR-00: setup container resources
  .github/workflows/deploy.yml
Labels: CI

#775 Implement importers
  src/components/PostDedicated/PostDedicated.container.tsx
  src/components/PostDetail/PostDetail.tsx
  src/components/PostImporterList/PostImporter.container.tsx
  src/components/PostImporterList/PostImporter.styles.ts
  src/components/PostImporterList/PostImporter.tsx
  src/components/PostImporterList/index.ts
  src/components/PostsList/PostsList.tsx
  src/components/PostsList/PostsListContainer.tsx
  src/components/Profile/PostTabPanel/PostTabPanel.container.tsx
  src/components/Timeline/Timeline.tsx
  src/components/Timeline/TimelineContainer.tsx
  src/components/atoms/PostHeader/index.tsx
  src/components/atoms/PostHeader/postHeader.interface.ts
  src/components/atoms/PostHeader/subHeader/post-sub-header.component.tsx
  src/components/atoms/PostHeader/subHeader/post-sub-header.interface.ts
  src/components/template/home/HomePage.tsx
  src/hooks/use-importer-hook.ts
  src/interfaces/user.ts
  src/lib/api/importers.ts
  src/reducers/importers/actions.ts
  src/reducers/importers/constants.ts
  src/reducers/importers/reducer.ts
  src/reducers/index.ts
Labels: Improvement

#776 Removed optional measurementId
  public/firebase-messaging-sw.js
  src/lib/firebase.ts
Labels: Fix

#759 Introduce authorization for API call
  .env-template
  .github/workflows/deploy.yml
  .github/workflows/mlc_config.json
  .maintain/kubernetes/templates/_helpers.tpl
  .maintain/kubernetes/templates/deployment.yaml
  .maintain/kubernetes/templates/secrets.yaml
  .maintain/kubernetes/values.yaml
  README.md
  next.config.js
  public/firebase-messaging-sw.js
  sentry.client.config.js
  sentry.server.config.js
  src/components/Help/Help.tsx
  src/components/Leaderboard/LeaderBoard.tsx
  src/components/Settings/Settings.container.tsx
  src/lib/api/base.ts
  src/lib/api/healthcheck.ts
  src/lib/api/upload.ts
  src/lib/api/wallet.ts
  src/lib/firebase.ts
Labels: Feature

#777 Improve deployment automation
  .github/workflows/builder.yml
  .github/workflows/deploy.yml
  .github/workflows/main.yml
  .github/workflows/test.yml
  .maintain/kubernetes/.helmignore
  .maintain/kubernetes/Chart.yaml
  .maintain/kubernetes/templates/_helpers.tpl
  .maintain/kubernetes/templates/deployment.yaml
  .maintain/kubernetes/templates/hpa.yaml
  .maintain/kubernetes/templates/ingress.yaml
  .maintain/kubernetes/templates/secrets.yaml
  .maintain/kubernetes/templates/service.yaml
  .maintain/kubernetes/templates/serviceaccount.yaml
  .maintain/kubernetes/templates/tests/test-connection.yaml
  .maintain/kubernetes/values.yaml
Labels: CI

#778 change development image tag
  .github/workflows/deploy.yml
Labels: CI

#779 change helm charts repository
  .github/workflows/deploy.yml
Labels: CI

#780 Added authorization interceptors
  src/lib/api/upload.ts
Labels: Fix

#781 Injected authorization to upload service
  src/lib/api/upload.ts
Labels: Fix

#782 Set headers for upload imaga and video
  src/lib/api/upload.ts
Labels: Improvement

#783 Improve tag logic
  .github/workflows/builder.yml
Labels: CI

#784 fix create pre-release draft
  .github/workflows/builder.yml
Labels: CI

#785 Hotfix
  src/components/PostDedicated/PostDedicated.container.tsx
  src/components/PostImporterList/PostImporter.tsx
  src/components/Timeline/TimelineContainer.tsx
  src/components/TipHistory/TipHistory.tsx
  src/components/atoms/Modal/Modal.styles.ts
  src/components/atoms/Modal/Modal.tsx
  src/components/atoms/PostHeader/subHeader/post-sub-header.component.tsx
  src/reducers/exchange-rate/actions.ts
  src/reducers/importers/actions.ts
Labels: Improvement

#786 Improve image tag development
  .github/workflows/deploy.yml
Labels: CI

#787 Fixed post importer component
  src/components/PostImporterList/PostImporter.tsx
  src/reducers/importers/reducer.ts
Labels: Improvement

#788 bug fixed routing, removed unnecessary component
  src/components/FriendsMenu/FriendList.tsx
  src/components/Menu/MenuContainer.tsx
  src/components/atoms/AddCoin/AddCoin.component.tsx
Labels: bug

#789 Sentry ignore health-check
  .env-template
  .gitignore
  sentry.client.config.js
  sentry.properties
  sentry.server.config.js
Labels: Feature

#790 Login validation improvement & styling
  src/components/FriendsMenu/FriendList.container.tsx
  src/components/FriendsMenu/FriendList.tsx
  src/components/FriendsMenu/FriendMenu.tsx
  src/components/FriendsMenu/default.ts
  src/components/Login/Login.styles.ts
  src/components/Login/Login.tsx
  src/components/Login/render/Accounts/Accounts.tsx
  src/components/Login/render/Options/Options.tsx
  src/components/Login/render/Profile/Profile.style.ts
  src/components/Login/render/Profile/Profile.tsx
  src/components/ProfileHeader/ProfileHeader.tsx
  src/components/ProfileHeader/profile-header.style.ts
  src/components/Socials/Socials.tsx
  src/components/UserMenu/hooks/user-tabs.hooks.tsx
  src/components/atoms/DropdownMenu/DropdownMenu.styles.ts
  src/components/atoms/DropdownMenu/DropdownMenu.tsx
  src/lib/api/post.ts
  src/lib/api/upload.ts
  src/lib/api/wallet.ts
Labels: bug

#791 Unbolded text and checked post owner for imported posts
  src/components/FriendsMenu/FriendList.tsx
  src/components/PostsList/PostsListContainer.tsx
  src/components/Profile/ProfileHeader/ProfileHeaderContainer.tsx
  src/components/Timeline/TimelineContainer.tsx
  src/components/atoms/CommentList/CommentList.container.tsx
Labels: bug

#792 set dynamic url based on current env
  src/components/AddSocialMedia/AddSocialMedia.tsx
Labels: bug

#793 Created privacy Policy and TnC
  pages/privacy-policy.tsx
  pages/term-of-use.tsx
Labels: good first issue

#794 Fix showing public key on visited profile
  src/components/UserMenu/hooks/user-tabs.hooks.tsx
  src/components/UserSettings/UserSettings.container.tsx
  src/components/UserSettings/UserSettings.tsx
Labels: Fix

#795 Fix notification mark read
  pages/notification.tsx
  pages/profile/[id].tsx
  src/components/Notifications/Notifications.container.tsx
  src/components/Notifications/Notifications.styles.ts
  src/components/Notifications/Notifications.tsx
  src/components/Notifications/hooks/use-notification-list.hook.tsx
  src/components/Notifications/sidebar/Notifications.container.tsx
  src/components/Notifications/sidebar/Notifications.styles.ts
  src/components/Notifications/sidebar/Notifications.tsx
  src/components/Profile/ProfileComponent.tsx
  src/components/Profile/ProfileNotFound.tsx
  src/components/Profile/profile.style.ts
  src/components/template/Default/DefaultLayout.styles.ts
  src/components/template/Default/DefaultLayout.tsx
  src/helpers/date.ts
  src/interfaces/user.ts
  src/lib/api/notification.ts
  src/lib/api/user.ts
  src/reducers/notification/actions.ts
  src/reducers/notification/constants.ts
  src/reducers/notification/reducer.ts
  src/reducers/profile/actions.ts
  src/reducers/profile/reducer.ts
  src/themes/light-theme.ts
Labels: bug, Improvement

#796 add onclick on name of the card
  src/components/atoms/PostHeader/index.tsx
Labels: Fix

#797 Enabled showing remove icon only on hover
  src/components/Socials/Socials.styles.ts
  src/components/Socials/Socials.tsx
  src/components/atoms/ListItem/ListItemSocial.tsx
Labels: Fix

#798 fixed styling and improvement post visibility
  src/components/ExperienceEditor/Experience.styles.ts
  src/components/ExperienceEditor/ExperienceEditor.tsx
  src/components/PostVisibility/PostVisibility.container.tsx
  src/components/PostVisibility/PostVisibility.tsx
  src/components/Profile/edit/ProfileEdit.tsx
  src/components/Profile/edit/profile-edit.style.ts
Labels: bug, Fix

#799 Enabled showing success prompt after tipping from post profile
  src/components/Profile/PostTabPanel/PostTabPanel.container.tsx
Labels: Fix

#801 Fix search hashtag query
  pages/home.tsx
  pages/search.tsx
  src/helpers/string.ts
  src/lib/api/post.ts
Labels: bug

#800 fixed social media and account privacy in profile
  pages/profile/[id].tsx
  src/components/Profile/PostTabPanel/PostTabPanel.container.tsx
  src/components/UserSocials/UserSocial.container.tsx
  src/components/UserSocials/UserSocials.tsx
Labels: Fix, Feature

#802 fix styling on single image dropzone
  src/components/ExperienceEditor/Experience.container.tsx
  src/components/ExperienceEditor/ExperienceEditor.tsx
  src/components/Upload/Upload.tsx
  src/components/atoms/Dropzone/Dropzone.styles.ts
  src/components/atoms/Dropzone/Dropzone.tsx
Labels: Fix

#803 Fix font size & width on large device
  src/components/FriendsMenu/friend.style.tsx
  src/components/NFT/nft.style.ts
  src/components/PostDetail/PostDetail.styles.ts
  src/components/Profile/ProfileHeader/index.tsx
  src/components/Profile/ProfileHeader/profile-header.style.ts
  src/components/Profile/ProfileHeader/render/Metric/Metric.style.ts
  src/components/Profile/ProfileHeader/render/Metric/Metric.tsx
  src/components/Profile/ProfileHeader/render/Metric/index.ts
  src/components/Profile/ProfileHeader/render/Website/Website.tsx
  src/components/Profile/ProfileHeader/render/Website/Webstite.style.ts
  src/components/Profile/ProfileHeader/render/Website/index.ts
  src/components/Profile/profile.style.ts
  src/components/Trending/trending-list.styles.ts
  src/components/UserMenu/UserMenu.styles.ts
  src/components/atoms/AddCoin/AddCoin.component.tsx
  src/components/atoms/AddCoin/AddCoin.style.ts
  src/components/atoms/BannerStatus/BannerStatus.tsx
  src/components/atoms/BannerStatus/banner.style.ts
  src/components/atoms/CommentDetail/CommentDetail.styles.ts
  src/components/atoms/CommentDetail/CommentDetail.tsx
  src/components/atoms/CommentDetail/CommentRender.tsx
  src/components/atoms/Empty/Empty.styles.ts
  src/components/atoms/Empty/Empty.tsx
  src/components/atoms/Gallery/Gallery.styles.ts
  src/components/atoms/ListItem/ListItemPeople.tsx
  src/components/atoms/ListItem/index.tsx
  src/components/atoms/Modal/Modal.styles.ts
  src/components/atoms/Modal/Modal.tsx
  src/components/atoms/NSFW/NSFW.component.tsx
  src/components/atoms/NSFW/nsfw.style.ts
  src/components/atoms/PostAction/index.tsx
  src/components/atoms/PostAction/postAction.style.ts
  src/components/atoms/PostHeader/cardTitle/CardTitle.component.tsx
  src/components/atoms/PostHeader/cardTitle/cardTitle.style.ts
  src/components/atoms/PostHeader/postHeader.style.ts
  src/components/atoms/Prompt/prompt.component.tsx
  src/components/atoms/Prompt/prompt.style.ts
  src/components/atoms/Report/Report.component.tsx
  src/components/atoms/Report/report.style.ts
  src/components/atoms/ToasterSnack/ToasterSnack.tsx
  src/components/atoms/ToasterSnack/toastersnack.style.ts
  src/components/template/Default/DefaultLayout.styles.ts
  src/components/template/Login/Login.styles.ts
  src/components/template/Login/Login.tsx
  src/helpers/date.ts
  src/helpers/number.ts
  src/helpers/url.ts
  src/themes/light-theme.ts
Labels: Improvement

#804 showing toast when experience on max limit
  src/components/ExperienceList/ExperienceList.tsx
  src/components/ExperienceList/SearchedExperienceListContainer.tsx
  src/components/ExperiencePreview/ExperiencePreview.container.tsx
  src/components/ExperienceTabMenu/ExperienceTabMenu.tsx
  src/components/ExperienceTabMenu/ExperienceTabMenuContainer.tsx
  src/components/HeaderWithAction/HeaderWithAction.tsx
  src/components/HeaderWithAction/header-w-action.interfaces.ts
  src/components/HeaderWithAction/header-w-action.styles.ts
  src/components/Profile/ExperienceTabPanel/ExperienceTabPanel.container.tsx
  src/components/Search/SearchResultContainer.tsx
  src/components/atoms/Dropzone/Dropzone.tsx
  src/components/atoms/SimpleCard/SimpleCard.tsx
Labels: Improvement

#805 MYR-000: fixed importers list
  src/components/PostImporterList/PostImporter.tsx
  src/reducers/importers/actions.ts
Labels: Improvement

#806 remove image on empty experience and friends
  src/components/Timeline/Timeline.tsx
  src/components/Timeline/TimelineEmpty.tsx
Labels: Fix

#807 created submit feedback
  pages/term-of-use.tsx
  src/components/Settings/Settings.container.tsx
  src/components/Settings/Settings.tsx
  src/components/Settings/hooks/use-setting-list.hook.tsx
Labels: good first issue

#809 Added versioning
  .env-template
  .github/workflows/deploy.yml
  next.config.js
  src/components/atoms/BannerStatus/BannerStatus.tsx
  src/reducers/config/reducer.ts
Labels: enhancement

#808 bug fixed issues with filter feature on post tab
  src/components/Profile/PostTabPanel/PostTabPanel.container.tsx
Labels: bug, Fix

#810 added prompt in register account
  src/components/Login/render/Profile/Profile.tsx
Labels: Fix

#811 fix handle experience behavior
  src/components/ExperienceList/ExperienceList.tsx
  src/components/ExperienceTabMenu/ExperienceTabMenuContainer.tsx
  src/components/Timeline/hooks/use-timeline-filter.hook.ts
Labels: Fix

#812 Fixed incorrect phrases
  pages/maintenance.tsx
  src/components/ExperienceList/NonSelectableExperienceList.tsx
  src/components/ExperienceTabMenu/ExperienceTabMenu.tsx
  src/components/FriendsMenu/FriendList.tsx
  src/components/PostDedicated/PostDedicated.container.tsx
  src/components/PostDetail/hooks/use-comment-tabs.tsx
  src/components/PostImport/PostImport.tsx
  src/components/PostVisibility/PostVisibility.container.tsx
  src/components/PostVisibility/PostVisibility.tsx
  src/components/PostsList/PostsListContainer.tsx
  src/components/PrimaryCoinMenu/PrimaryCoinMenu.tsx
  src/components/Profile/PostTabPanel/PostTabPanel.container.tsx
  src/components/Profile/ProfileHeader/ProfileHeaderContainer.tsx
  src/components/Settings/hooks/use-setting-list.hook.tsx
  src/components/Timeline/TimelineContainer.tsx
  src/components/Timeline/default.ts
  src/components/TimelineFilter/hooks/use-filter-option.hook.ts
  src/components/UserSocials/UserSocials.tsx
  src/components/atoms/BannerStatus/BannerStatus.tsx
  src/components/atoms/CommentList/CommentList.container.tsx
  src/components/atoms/Empty/Empty.styles.ts
  src/components/template/Login/Login.tsx
  src/reducers/timeline/actions.ts
Labels: Fix

#813 Fixed get package version
  .github/workflows/deploy.yml
Labels: enhancement

#814 changed onMouseEnter to onClick when showing importer list
  src/components/atoms/PostHeader/subHeader/post-sub-header.component.tsx
Labels: Improvement

#816 Fixed banner versioning
  src/components/atoms/BannerStatus/BannerStatus.tsx
Labels: enhancement

#817 handle close when selecting the option and fix behavior experience
  src/components/ExperienceList/ExperienceList.tsx
  src/components/Profile/edit/ImageButton.component.tsx
Labels: bug, Fix

#818 Update display name validator
  src/components/Login/render/Profile/Profile.tsx
Labels: bug, Improvement

#819 Fix blocked user name
  src/components/atoms/CommentDetail/CommentDetail.tsx
Labels: bug

#820 Fix blocked user style
  src/components/atoms/CommentDetail/CommentDetail.tsx
Labels: bug

#821 bug fixed issues with filter feature on post tab
  src/components/Profile/PostTabPanel/PostTabPanel.container.tsx
Labels: bug, Fix

#822 Adjust screen resolution
  src/components/Error/Error.tsx
  src/components/FriendsMenu/friend.style.tsx
  src/components/NFT/nft.style.ts
  src/components/PostDetail/PostDetail.styles.ts
  src/components/Profile/profile.style.ts
  src/components/ProfileHeader/profile-header.style.ts
  src/components/UserMenu/UserMenu.styles.ts
  src/components/atoms/Gallery/Gallery.styles.ts
  src/components/atoms/SimpleCard/SimpleCard.style.ts
  src/components/template/Default/DefaultLayout.styles.ts
  src/components/template/Default/DefaultLayout.tsx
  src/themes/light-theme.ts
Labels: Improvement

#823 fixed friend list
  src/components/FriendsMenu/FriendList.tsx
  src/hooks/use-friends-hook.ts
  src/reducers/friend/reducer.ts
Labels: Improvement

#824 rework flow update profile
  src/components/Profile/edit/ProfileEdit.tsx
  src/components/Profile/edit/ProfileEditContainer.tsx
  src/hooks/use-profile.hook.ts
Labels: Fix

#825 fix showing notif wording on unlink socmed
  src/components/Notifications/hooks/use-notification-list.hook.tsx
  src/interfaces/notification.ts
Labels: Fix
