Repository myriadsocial/myriad-web, pull requests merged in 2021-09, with the labels that each got.

#411 Ci implement new flow
  .github/workflows/main.yml
  .github/workflows/release-candidate.yml
  .github/workflows/release.yml
Labels: CI

#412 CI/CD: integrated new flow
  .github/workflows/main.yml
  .github/workflows/release-candidate.yml
  .github/workflows/release.yml
Labels: CI

#414 CI/CD: integrated new flow
  .maintain/kubernetes/templates/ingressclass.yaml
Labels: CI

#415 CI/CD: integrated new flow
  .maintain/kubernetes/templates/ingressclass.yaml
Labels: CI

#417 CI/CD: integrated new flow
  .github/workflows/main.yml
  .github/workflows/release-candidate.yml
  .github/workflows/release.yml
  .maintain/kubernetes/templates/ingressclass.yaml
Labels: CI

#419 CI/CD: integrated new flow
  .github/workflows/main.yml
  .github/workflows/release-candidate.yml
  .github/workflows/release.yml
Labels: CI

#420 CI/CD: integrated new flow
  .maintain/kubernetes/templates/deployment.yaml
  .maintain/kubernetes/values.yaml
Labels: CI

#421 CI/CD: integrated new flow
  .github/workflows/main.yml
  .github/workflows/release-candidate.yml
  .github/workflows/release.yml
  .maintain/kubernetes/templates/certificate.yaml
  .maintain/kubernetes/templates/issuer.yaml
Labels: CI

#439 MYR-806: moved stories to component dirs and fixed build error
  src/components-v2/ExperienceList/ExperienceList.stories.tsx
  src/components-v2/RightMenuBar/RightMenuBar.tsx
  src/components-v2/RightMenuBar/index.ts
  src/components-v2/RightMenuBar/right-menubar.interfaces.ts
  src/components-v2/atoms/search/SearchBox.stories.tsx
  src/components-v2/profile-header/ProfileHeader.stories.tsx
  src/components-v2/template/home/HomePage.stories.tsx
  src/stories/RightMenuBar.stories.tsx
Labels: Fix

#441 MYR-806: created TopNavbar component
  src/components-v2/atoms/top-navbar/TopNavbar.stories.tsx
  src/components-v2/atoms/top-navbar/TopNavbar.tsx
  src/components-v2/atoms/top-navbar/index.ts
  src/components-v2/atoms/top-navbar/top-navbar.interfaces.ts
  src/components-v2/atoms/top-navbar/top-navbar.styles.ts
  src/themes/light-theme-v2.ts
Labels: Improvement

#465 CI/CD: renamed secret name
  .github/workflows/main.yml
  .github/workflows/release-candidate.yml
  .github/workflows/release.yml
Labels: CI

#466 CD/CD: changed base secret
  .maintain/kubernetes/templates/_helpers.tpl
Labels: CI

#481 MYR-000: fixed mjs build error with webpack storybook
  .storybook/main.js
  src/components/login/modal-accounts.component.tsx
  src/components/login/modal-no-extension.component.tsx
  src/hooks/auth.hook.ts
Labels: Fix
