Repository myriadsocial/myriad-web, pull requests merged in 2021-11, with the labels that each got.

#595 MYR-1044: fix block/unblock user
  pages/profile/[id].tsx
  src/components-v2/BlockUserList/BlockList.container.tsx
  src/components-v2/BlockUserList/BlockList.tsx
  src/components-v2/FriendsMenu/hooks/use-friend-request.hook.ts
  src/components-v2/Profile/ProfileComponent.tsx
  src/components-v2/Profile/ProfileHeader/ProfileHeaderContainer.tsx
  src/components-v2/Profile/ProfileHeader/index.tsx
  src/components-v2/Profile/ProfileHeader/profile-header.stories.tsx
  src/components-v2/Profile/profile.style.ts
  src/components-v2/template/profile/ProfilePage.tsx
  src/components/common/captcha.component.tsx
  src/components/experience/use-experience.hooks.ts
  src/components/post/post-options.component.tsx
  src/components/profile/header/header.component.tsx
  src/components/profile/use-profile-friend.hook.ts
  src/components/profile/use-profile.hook.ts
  src/hooks/use-comment.hook.ts
  src/hooks/use-friends-hook.ts
  src/lib/api/healthcheck.ts
  src/lib/api/notification.ts
  src/lib/api/post.ts
  src/reducers/block/actions.ts
  src/reducers/profile/actions.ts
  src/reducers/profile/constants.ts
  src/reducers/profile/reducer.ts
Labels: bug

#596 MYR-1080: fix preview url on import post
  src/components-v2/PostImport/PostImport.tsx
  src/components-v2/atoms/Embed/Embed.styles.ts
  src/components-v2/atoms/Embed/Embed.tsx
Labels: bug

#598 MYR-1094: set dropdown to appear in center and bottom
  src/components-v2/atoms/DropdownMenu/DropdownMenu.tsx
Labels: Improvement

#601 MYR-1031: check if notification user detail exist
  src/components-v2/Notifications/hooks/use-notification-list.hook.tsx
Labels: bug

#603 bug fixed empty user picture
  src/components-v2/Profile/ProfileHeader/index.tsx
  src/components-v2/Profile/ProfileHeader/profile-header.style.ts
  src/components-v2/Profile/edit/ProfileEdit.tsx
  src/components-v2/Profile/edit/profile-edit.style.ts
  src/components-v2/UsersList/UsersList.tsx
  src/components-v2/UsersList/UsersListItem.tsx
  src/helpers/string.ts
Labels: bug

#605 created page /maintenance component
  pages/maintenance.tsx
  src/images/Myriad_Full_Logo_Color_1-01_1.svg
  src/images/undraw_Fall_is_coming_yl0x_1.svg
Labels: Improvement

#607 Added custom 404 page
  pages/404.tsx
  src/images/404_Page_Not_Found__Isometric_2_1.svg
Labels: Improvement

#609 Bugfix: Handled unexpected error in History in Wallet Menu
  src/components-v2/HistoryDetailList/HistoryDetailList.tsx
Labels: bug

#610 MYR-1124: Send Tip
  src/components-v2/PostsList/PostsListContainer.tsx
Labels: bug

#612 Mandatory Field in Edit Experience Form
  src/components-v2/ExperienceEditor/ExperienceEditor.tsx
Labels: bug

#613 MYR-1113: add image loading placeholder
  src/components-v2/PostEditor/PostRender.tsx
  src/components-v2/atoms/Dropzone/Dropzone.tsx
  src/components-v2/atoms/Gallery/Gallery.styles.ts
  src/components-v2/atoms/Gallery/Gallery.tsx
  src/components-v2/atoms/Gallery/Gallery.types.ts
  src/components-v2/atoms/Gallery/util.ts
  src/images/Icons/myriad-grey.svg
  src/lib/api/post.ts
Labels: Feature

#614 MYR-997: improved UX when selecting People with Autocomplete
  src/components-v2/ExperienceEditor/ExperienceEditor.tsx
Labels: bug

#615 Added prompt when cancel edit, added cancel button
  src/components-v2/Profile/ExperienceTabPanel/ExperienceTabPanel.container.tsx
  src/components-v2/Profile/edit/ProfileEdit.tsx
  src/components-v2/Profile/edit/ProfileEditContainer.tsx
  src/components-v2/Profile/edit/profile-edit.style.ts
Labels: bug, Improvement

#618 MYR-1113: user can remove vote
  src/components-v2/PostDedicated/PostDedicated.container.tsx
  src/components-v2/PostDetail/PostDetail.tsx
  src/components-v2/PostsList/PostsList.tsx
  src/components-v2/PostsList/PostsListContainer.tsx
  src/components-v2/Profile/PostTabPanel/PostTabPanel.container.tsx
  src/components-v2/Profile/ProfileHeader/index.tsx
  src/components-v2/Report/use-post-report-list.hook.ts
  src/components-v2/Timeline/Timeline.tsx
  src/components-v2/Timeline/TimelineContainer.tsx
  src/components-v2/atoms/CommentList/CommentList.container.tsx
  src/components-v2/atoms/CommentList/CommentList.tsx
  src/components-v2/atoms/Dropzone/Dropzone.tsx
  src/components-v2/atoms/Video/Video.tsx
  src/components-v2/template/home/HomePage.tsx
  src/hooks/use-comment.hook.ts
  src/lib/api/post.ts
  src/reducers/timeline/actions.ts
  src/reducers/timeline/constants.ts
  src/reducers/timeline/reducer.ts
Labels: bug

#625 changed CTA/placeholder for posting comment
  src/components-v2/PostDetail/hooks/use-comment-tabs.tsx
  src/components-v2/atoms/CommentEditor/CommentEditor.tsx
Labels: bug, Improvement

#626 MYR-1069: filter post visibility
  pages/api/video.ts
  pages/post/[postId].tsx
  pages/profile/[id].tsx
  src/components-v2/PostEditor/PostRender.tsx
  src/components-v2/PostImport/PostImport.tsx
  src/components-v2/Profile/ProfileComponent.tsx
  src/components-v2/Profile/ProfileHeader/index.tsx
  src/components/profile/friend/friend-list.component.tsx
  src/lib/api/post.ts
  src/reducers/timeline/actions.ts
Labels: bug

#628 MYR-1132: fix post query
  src/lib/api/post.ts
Labels: bug

#630 MYR-1132: init firebase
  src/components-v2/template/Default/DefaultLayout.tsx
Labels: Fix

#631 MYR-1132: prevent show toaster on fcm tokens update
  src/components-v2/WelcomeModule/Welcome.container.tsx
  src/components/profile/use-profile.hook.ts
  src/hooks/use-user.hook.ts
  src/reducers/user/actions.ts
Labels: Fix

#632 fixed button margin in prompt
  src/components-v2/BlockUserList/BlockList.tsx
  src/components-v2/BlockUserList/blocklist.style.ts
  src/components-v2/PostDedicated/PostDedicated.container.tsx
  src/components-v2/Profile/PostTabPanel/PostTabPanel.container.tsx
  src/components-v2/Profile/ProfileHeader/profile-header.style.ts
  src/components-v2/Profile/edit/ProfileEdit.tsx
  src/components-v2/Profile/edit/profile-edit.style.ts
  src/components-v2/Socials/Socials.styles.ts
  src/components-v2/Socials/Socials.tsx
  src/components-v2/Timeline/TimelineContainer.tsx
  src/components-v2/WelcomeModule/Welcome.container.tsx
  src/components-v2/atoms/SimpleCard/SimpleCard.style.ts
Labels: bug

#633 bug fixed set banner not displayed when start render page
  src/components-v2/atoms/BannerStatus/BannerStatus.tsx
Labels: bug, good first issue

#635 MYR-966: remove dummy code
  pages/api/video.ts
Labels: bug

#638 CI/CD - improve release automation
  .github/workflows/release.yml
Labels: CI

#640 MYR-1132: update sort param
  src/lib/api/post.ts
Labels: bug

#645 CI/CD - change imagePullPolicy
  .github/workflows/alpha.yml
Labels: CI

#647 MYR-1132: prevent multiple push notif message
  public/firebase-messaging-sw.js
  src/components-v2/Notifications/sidebar/Notifications.container.tsx
  src/components-v2/PostEditor/PostEditor.tsx
  src/components-v2/PostEditor/Render/Mention/MentionSelect/index.tsx
  src/components-v2/atoms/Gallery/Gallery.tsx
  src/components-v2/atoms/Gallery/Gallery.types.ts
  src/components-v2/atoms/Gallery/util.ts
  src/components-v2/template/Default/DefaultLayout.tsx
  src/components/post/post-image.component.tsx
  src/hooks/use-user.hook.ts
Labels: bug

#648 CI/CD: Fixed deployment
  .github/workflows/alpha.yml
Labels: CI

#649 CI/CD - fixed alpha image tag typo
  .github/workflows/alpha.yml
Labels: CI

#653 fixed mention list display
  src/components-v2/atoms/ListItem/index.tsx
Labels: bug

#654 MYR-827: redirect mobile access
  package.json
  pages/experience/[experienceId]/clone.tsx
  pages/experience/[experienceId]/edit.tsx
  pages/experience/[experienceId]/preview.tsx
  pages/experience/create.tsx
  pages/friends.tsx
  pages/home.tsx
  pages/index.tsx
  pages/mobile.tsx
  pages/nft.tsx
  pages/notification.tsx
  pages/post/[postId].tsx
  pages/profile/[id].tsx
  pages/register.tsx
  pages/search.tsx
  pages/searchresults.tsx
  pages/settings.tsx
  pages/socials.tsx
  pages/socialtoken.tsx
  pages/topic/[type].tsx
  pages/wallet.tsx
  pages/welcome.tsx
  src/components-v2/Upload/Upload.tsx
  src/components-v2/atoms/Dropzone/Dropzone.tsx
  src/components-v2/atoms/Gallery/Gallery.tsx
  yarn.lock
Labels: Improvement

#657 MYR-1158: enable mention on comment
  pages/mobile.tsx
  src/components-v2/AddSocialMedia/AddSocialMedia.tsx
  src/components-v2/PostCreate/PostCreate.container.tsx
  src/components-v2/PostCreate/PostCreate.tsx
  src/components-v2/PostDetail/PostDetail.stories.tsx
  src/components-v2/PostDetail/hooks/use-comment-tabs.tsx
  src/components-v2/PostEditor/PostEditor.tsx
  src/components-v2/PostEditor/PostRender.tsx
  src/components-v2/PostEditor/formatter.ts
  src/components-v2/PostEditor/plugins/hashtag/withHashtag.ts
  src/components-v2/Timeline/Timeline.stories.tsx
  src/components-v2/WelcomeModule/Welcome.container.tsx
  src/components-v2/atoms/CommentDetail/CommentDetail.interface.ts
  src/components-v2/atoms/CommentDetail/CommentDetail.stories.tsx
  src/components-v2/atoms/CommentDetail/CommentDetail.styles.ts
  src/components-v2/atoms/CommentDetail/CommentDetail.tsx
  src/components-v2/atoms/CommentDetail/CommentRender.tsx
  src/components-v2/atoms/CommentEditor/CommentEditor.stories.tsx
  src/components-v2/atoms/CommentEditor/CommentEditor.style.ts
  src/components-v2/atoms/CommentEditor/CommentEditor.tsx
  src/components-v2/atoms/CommentEditor/formatter.ts
  src/components-v2/atoms/CommentList/CommentList.container.tsx
  src/components-v2/atoms/CommentList/CommentList.tsx
  src/components-v2/atoms/Dropzone/Dropzone.tsx
  src/components-v2/atoms/Tabs/Tabs.tsx
  src/components/post/comment/comment.component.tsx
  src/interfaces/comment.ts
  src/interfaces/user.ts
  src/lib/api/activity.ts
  src/lib/serializers/session.ts
Labels: Feature, Improvement

#661 Handled Receivers/Senders are missing in Transaction History
  src/components-v2/HistoryDetailList/HistoryDetailList.tsx
Labels: bug

#662 Remove Default Website for first time user
  src/components-v2/Profile/ProfileHeader/index.tsx
  src/components-v2/Profile/edit/ProfileEdit.tsx
Labels: Improvement

#667 Defined Latest Transaction as default sorting option in Wallet History
  src/components-v2/Timeline/default.ts
Labels: Improvement

#668 Changed hover state on Experience SimpleCard
  src/components-v2/atoms/SimpleCard/SimpleCard.style.ts
Labels: Improvement

#669 applied search Currencies on Enter key
  src/components-v2/atoms/AddCoin/AddCoin.component.tsx
Labels: bug

#671 Improvement for Input Validation in Tipping
  src/components-v2/SendTip/SendTip.tsx
Labels: bug

#670 minor bug fixing
  src/components-v2/atoms/CommentEditor/CommentEditor.tsx
  src/components-v2/atoms/PostAction/index.tsx
Labels: Fix

#677 feat added prompt in welcome page
  src/components-v2/WelcomeModule/Welcome.container.tsx
Labels: Fix, Improvement

#684 Apply white background when there is no Post to show on Friend/Experience filter
  src/components-v2/Timeline/TimelineEmpty.tsx
Labels: Improvement

#685 Improvement for Tipping - limiting length of user input
  src/components-v2/SendTip/SendTip.tsx
Labels: Improvement

#686 feat config setting for notifications
  src/components-v2/Settings/NotificationSettings.container.tsx
  src/components-v2/Settings/NotificationSettings.tsx
  src/components-v2/Settings/Settings.styles.ts
  src/components-v2/Settings/hooks/use-notification-setting.hook.ts
  src/interfaces/setting.ts
  src/lib/api/setting.ts
  src/reducers/config/actions.ts
  src/reducers/config/reducer.ts
Labels: Improvement

#690 MYR-1277: fix imported list
  pages/post/[postId].tsx
  src/components-v2/AddSocialMedia/AddSocialMedia.tsx
  src/components-v2/PostDetail/PostDetail.stories.tsx
  src/components-v2/Report/Report.styles.ts
  src/components-v2/Report/Report.tsx
  src/components-v2/Timeline/Timeline.stories.tsx
  src/components-v2/atoms/PostHeader/index.tsx
  src/components-v2/atoms/PostHeader/subHeader/post-sub-header.component.tsx
  src/components-v2/atoms/PostHeader/subHeader/post-sub-header.interface.ts
  src/components-v2/atoms/PostHeader/subHeader/post-sub-header.style.ts
  src/interfaces/post.ts
  src/lib/api/post.ts
Labels: bug
