Repository myriadsocial/myriad-web, pull requests merged in 2022-10, with the labels that each got.

#1478 fix: clear near storage when disconnect
  src/components/Manage/Manage.container.tsx
  src/hooks/use-connect.hook.ts
Labels: Improvement

#1480 fix: post search result
  src/lib/api/post.ts
Labels: Improvement

#1481 fix tab search user
  src/components/PostList/PostList.container.tsx
Labels: bug

#1482 fix: error near login
  src/lib/services/near-api-js.ts
Labels: Improvement

#1483 feat: disabled logout button only on anonymous mobile view
  src/components/Mobile/MenuDrawer/MenuDrawer.tsx
  src/components/ProfileCard/ProfileCard.container.tsx
  src/hooks/auth.hook.ts
Labels: Fix

#1490 fix: bucket endpoint
  src/components/common/Editor/Editor.tsx
  src/components/common/Editor/render/Toolbar/Button/ImageButton.tsx
  src/components/common/Editor/render/Toolbar/Button/MediaEmbedButton.tsx
  src/hooks/use-upload.hook.ts
  src/lib/api/upload.ts
Labels: Improvement

#1489 Completed screens when changing instance on homepage
  package.json
  src/components/InstanceCard.tsx
  src/components/Login/render/Options/Options.tsx
  src/components/Login/render/Profile/Profile.tsx
  src/components/Menu/Menu.container.test.tsx
  src/components/Menu/Menu.test.tsx
  src/components/Menu/Menu.tsx
  src/components/SelectServer.styles.ts
  src/components/SelectServer.tsx
  src/lib/api/base.ts
  src/locale/en.json
  src/locale/id.json
  src/reducers/index.ts
  test/test-utils.js
  test/test-utils.tsx
  yarn.lock
Labels: enhancement

#1491 fix: improve GET /friends query
  pages/profile/[id].tsx
  src/components/Profile/Profile.container.tsx
  src/components/Profile/Profile.tsx
  src/components/ProfileBanned/ProfileBanned.tsx
  src/components/ProfileHeader/ProfileHeaderContainer.tsx
  src/components/ProfileHeader/hooks/use-friend-options.hook.ts
  src/components/ProfileHeader/index.tsx
  src/components/UserMenu/hooks/user-tabs.hooks.tsx
  src/helpers/image.ts
  src/hooks/use-blocked-list.hook.ts
  src/hooks/use-friend-request.hook.ts
  src/hooks/use-friends-hook.ts
  src/hooks/use-profile-friend.hook.ts
  src/interfaces/friend.ts
  src/interfaces/user.ts
  src/lib/api/friends.ts
  src/lib/api/user.ts
  src/lib/api/wallet.ts
  src/reducers/friend-request/actions.ts
  src/reducers/friend/actions.ts
  src/reducers/profile/actions.ts
  src/reducers/profile/reducer.ts
Labels: Improvement

#1499 feat: Add kebab menu on experience card
  src/components/Expericence/Experience.tsx
  src/components/RightMenuBar/tabs/TrendingExperienceTab.tsx
  src/components/Timeline/Render/ExperienceCard.tsx
  src/components/Timeline/Render/experience-card.style.ts
Labels: Feature

#1500 chore: bump version to 2.1.21
  package.json
Labels: Feature

#1503 feat: slicing new design login web 2.0
  src/components/Login/Login.tsx
  src/components/Login/render/SignInMethod/SigninMethod.style.ts
  src/components/Login/render/SignInMethod/SigninMethod.tsx
  src/components/Login/render/SignInMethod/index.ts
  src/images/illustration/IcInfo.svg
  src/images/illustration/LoginWeb2.svg
  src/images/illustration/LoginWeb3.svg
  src/images/illustration/index.ts
Labels: enhancement

#1504 fix: navigate to web 3 login
  src/components/Login/render/SignInMethod/SigninMethod.style.ts
  src/components/Login/render/SignInMethod/SigninMethod.tsx
Labels: bug

#1506 feat: slicing create accounts
  src/components/Login/Login.tsx
  src/components/Login/render/CreateAccounts/CreateAccounts.style.ts
  src/components/Login/render/CreateAccounts/CreateAccounts.tsx
  src/components/Login/render/CreateAccounts/index.ts
  src/components/Login/render/Options/Options.tsx
  src/components/Login/render/SignInMethod/SigninMethod.tsx
  src/images/Icons/IcEmail.svg
  src/images/Icons/index.ts
Labels: enhancement

#1508 fix : add ticker
  src/components/Login/render/Profile/Profile.style.ts
  src/components/Login/render/Profile/Profile.tsx
  src/components/Login/render/SignInMethod/SigninMethod.tsx
Labels: bug
