Repository myriadsocial/myriad-web, pull requests merged in 2022-11, with the labels that each got.

#1509 feat : Add back button on web3 login method
  src/components/Login/render/Accounts/Accounts.tsx
  src/components/Login/render/CreateAccounts/CreateAccounts.tsx
  src/components/Login/render/Email/LoginByEmail.tsx
  src/components/Login/render/Options/Options.style.ts
  src/components/Login/render/Options/Options.tsx
  src/components/Login/render/Profile/Profile.tsx
Labels: enhancement

#1510 cd: improve ci/cd
  .github/workflows/deployer.yml
  .github/workflows/release.yml
Labels: Improvement

#1511 feat: Wiring check user by email
  src/components/Login/Login.tsx
  src/components/Login/render/CreateAccounts/CreateAccounts.tsx
  src/components/Login/render/Email/LoginByEmail.tsx
  src/lib/api/user.ts
Labels: Feature

#1512 fix: update spacing button
  src/components/Login/render/Profile/Profile.style.ts
  src/components/Login/render/Profile/Profile.tsx
Labels: enhancement

#1514 fix: disconnect with alphanumeric near address
  src/lib/api/wallet.ts
Labels: Improvement

#1517 chore: release 2.1.23
  .github/workflows/analyzer.yml
  .github/workflows/builder.yml
  package.json
Labels: CI

#1519 feat: add limit edit profile
  src/components/ProfileEdit/ProfileEdit.tsx
  src/components/ProfileEdit/ProfileEditContainer.tsx
  src/interfaces/user.ts
Labels: enhancement

#1522 feat: component card wallet
  src/components/MyWallet/MyWallet.tsx
  src/components/WalletBalance/index.tsx
Labels: enhancement

#1524 fix: handle register new user with near
  src/components/Login/render/Profile/Profile.tsx
Labels: Improvement

#1523 feat : add limitation for add friends, clone experiance, create experiance on lite version
  src/components/ExpericenceRightBar/Experience.tsx
  src/components/ProfileHeader/index.tsx
  src/components/RightMenuBar/tabs/ExperienceTab.tsx
  src/components/WalletBalance/index.tsx
  src/lib/api/wallet.ts
Labels: enhancement

#1527 feat : Create disclaimer on edit profile for lite version
  src/components/Profile/Profile.tsx
  src/components/ProfileEdit/ProfileEdit.tsx
  src/components/ProfileHeader/index.tsx
  src/components/RightMenuBar/tabs/ExperienceTab.tsx
  src/components/WalletBalance/index.tsx
  src/locale/en.json
  src/locale/id.json
  src/locale/ru.json
Labels: Feature

#1529 feat: Set limit on post/import post/comment creation
  src/components/ExpericenceRightBar/Experience.tsx
  src/components/PostCreate/PostCreate.container.tsx
  src/locale/en.json
  src/locale/id.json
  src/locale/ru.json
  src/reducers/timeline/actions.ts
Labels: enhancement

#1530 fix: handle page wallet for lite version
  pages/wallet.tsx
  src/components/HistoryDetailList/HistoryDetailList.tsx
  src/components/HistoryDetailList/HistoryDetailListContainer.tsx
  src/components/Tip/Tip.tsx
  src/components/WalletBalance/index.tsx
  src/components/common/Blockchain/Blockchain.provider.tsx
  src/hooks/use-claim-tip.hook.ts
  src/hooks/use-near-api.hook.ts
  src/hooks/use-polkadot-api.hook.ts
  src/hooks/use-transaction.hooks.ts
  src/reducers/transaction/actions.ts
Labels: Improvement

#1531 fix: handle page in lite version
  pages/experience/[experienceId]/clone.tsx
  pages/experience/[experienceId]/edit.tsx
  pages/experience/[experienceId]/index.tsx
  pages/experience/create.tsx
  pages/experience/index.tsx
  pages/experience/trending.tsx
  pages/friends.tsx
  pages/nft.tsx
  pages/notification.tsx
  pages/profile/[id].tsx
  pages/search.tsx
  pages/settings.tsx
  pages/socials.tsx
  pages/socialtoken.tsx
  pages/topic/[type].tsx
  pages/topic/index.tsx
  pages/town.tsx
Labels: Improvement

#1532 fix: tipping status in lite version
  src/components/Tip/Tip.container.tsx
  src/components/WalletBalance/index.tsx
  src/hooks/use-claim-tip.hook.ts
Labels: Improvement

#1534 feat: Wiring create user by email
  src/components/Login/render/CreateAccounts/CreateAccounts.tsx
  src/lib/api/auth-link.ts
  src/locale/en.json
  src/locale/id.json
  src/locale/ru.json
Labels: Feature

#1539 fix: limited access on create post
  src/components/PostCreate/PostCreate.container.tsx
  src/lib/api/user.ts
  src/locale/en.json
  src/locale/id.json
  src/locale/ru.json
Labels: Fix

#1540 fix limitation on experiance
  src/components/Expericence/Experience.tsx
  src/components/ExpericenceRightBar/Experience.tsx
  src/components/ExperienceList/ExperienceList.container.tsx
  src/components/ExperiencePreview/ExperiencePreview.container.tsx
  src/components/RightMenuBar/tabs/ExperienceTab.tsx
  src/components/Timeline/Render/ExperienceCard.tsx
Labels: bug

#1550 add popup lite version on comment and reply comment
  src/components/CommentList/CommentList.container.tsx
  src/components/PostCreate/PostCreate.container.tsx
  src/hooks/use-comment.hook.ts
Labels: Fix

#1551 fix: handle switch flag when user upgrade from lite version to full version
  src/hooks/use-connect.hook.ts
  src/reducers/user/actions.ts
  src/reducers/user/constants.ts
  src/reducers/user/reducer.ts
Labels: Improvement

#1552 fix: update instance description, tnc privacy, wo rding, extend timeout, new empty state friends
  src/components/FriendsMenu/FriendList.tsx
  src/components/Login/render/CreateAccounts/CreateAccounts.style.ts
  src/components/Login/render/CreateAccounts/CreateAccounts.tsx
  src/components/Login/render/MagicLink/LoginMagicLink.tsx
  src/components/LoginMagicLink.style.ts
  src/locale/en.json
Labels: Fix

#1554 fix: handle login page
  pages/login.tsx
  src/components/Login/Login.tsx
  src/components/Login/render/SignInMethod/SigninMethod.style.ts
  src/components/Login/render/SignInMethod/SigninMethod.tsx
  src/locale/en.json
  src/locale/id.json
  src/locale/ru.json
Labels: Improvement

#1556 fix : Clone button in experience menu doesn't work
  src/components/RightMenuBar/tabs/ExperienceTab.tsx
Labels: Fix

#1558 feat: implement validation for create account with email
  package.json
  src/components/Login/Login.tsx
  src/components/Login/render/CreateAccounts/CreateAccounts.style.ts
  src/components/Login/render/CreateAccounts/CreateAccounts.tsx
Labels: Feature

#1562 fix: wording federated instance description
  src/components/Login/render/CreateAccounts/CreateAccounts.tsx
  src/components/Login/render/MagicLink/LoginMagicLink.tsx
  src/components/Login/render/Profile/Profile.tsx
Labels: Improvement

#1564 fix: request email otp
  src/components/Login/render/Email/LoginByEmail.tsx
Labels: Improvement

#1567 fix: handling back behavior on magic link page
  src/components/Login/render/MagicLink/LoginMagicLink.tsx
Labels: Feature

#1568 fix: wording on magic link page
  src/components/Login/render/MagicLink/LoginMagicLink.tsx
  src/locale/en.json
  src/locale/id.json
  src/locale/ru.json
Labels: Fix

#1569 fix: lite version disclaimer shows on fullAccess profile
  src/components/ProfileHeader/index.tsx
Labels: bug

#1570 improvement: create experience
  src/components/ExperienceEditor/ExperienceEditor.tsx
Labels: enhancement

#1575 fix: handle experience page as anonymous
  pages/experience/[experienceId]/index.tsx
  pages/index.tsx
  src/lib/api/experience.ts
Labels: Improvement

#1576 fix: handle profile page as anonymous
  pages/profile/[id].tsx
  src/components/Profile/Profile.tsx
  src/components/ProfileHeader/index.tsx
  src/interfaces/user.ts
  src/lib/api/user.ts
  src/reducers/config/actions.ts
Labels: Improvement

#1578 chore: bump version to 2.2.1
  package.json
Labels: Feature

#1579 fix: handle add friend modal wording in lite version
  src/components/ProfileHeader/index.tsx
  src/components/UserMenu/UserMenu.tsx
  src/locale/en.json
  src/locale/id.json
  src/locale/ru.json
Labels: Improvement

#1580 fix: typos endpoint name
  package.json
  src/lib/api/experience.ts
  src/locale/en.json
  src/locale/id.json
  src/locale/ru.json
Labels: Improvement

#1581 fix: renamed walletaddress endpoint
  src/lib/api/comment.ts
  src/lib/api/post.ts
  src/lib/api/user.ts
Labels: Improvement

#1583 fix: wording for timeline
  package.json
  src/locale/en.json
Labels: Fix

#1572 fix: renamed auth endpoint
  src/lib/api/auth-link.ts
  src/lib/api/ext-auth.ts
  src/lib/api/wallet.ts
Labels: Improvement

#1584 fix: renamed auth endpoint
  src/lib/api/auth-link.ts
  src/lib/api/ext-auth.ts
  src/lib/api/wallet.ts
Labels: Improvement

#1585 fix: balance not showing
  src/hooks/use-connect.hook.ts
  src/reducers/user/actions.ts
Labels: Improvement

#1586 fix: improve code related to connect account
  src/components/Login/render/Options/Options.tsx
  src/components/Manage/Manage.tsx
  src/components/Manage/use-wallet-list.hook.tsx
Labels: Improvement

#1587 fix: missing space report user
  src/components/atoms/Report/Report.component.tsx
Labels: Fix

#1588 feat: add new network support for debio
  src/components/Login/render/Options/Options.tsx
  src/components/ProfileCard/NetworkOption/NetworkOption.tsx
  src/components/atoms/Icons/Network.tsx
  src/helpers/extension.ts
  src/helpers/wallet.ts
  src/images/network/debio.svg
  src/interfaces/network.ts
Labels: Feature
