Repository myriadsocial/myriad-web, pull requests merged in 2022-01, with the labels that each got.

#826 fixed styling for empty post tip history
  src/components/TipHistory/TipHistory.tsx
Labels: Fix

#827 created airdrop based on kudos
  src/components/Leaderboard/LeaderBoard.tsx
  src/lib/api/leaderboard.ts
Labels: Fix

#828 Styled tab panel properly
  src/components/UserMenu/UserMenu.tsx
  src/components/UserSettings/UserSettings.styles.ts
  src/components/UserSocials/UserSocials.styles.ts
Labels: Improvement

#830 fixed button width
  src/components/Profile/edit/ProfileEdit.tsx
  src/components/Profile/edit/profile-edit.style.ts
Labels: Fix

#829 wired arrow button to set primary coin
  src/components/PrimaryCoinMenu/DraggableBalanceCard.tsx
  src/components/PrimaryCoinMenu/PrimaryCoinMenu.tsx
  src/components/PrimaryCoinMenu/primary-coin-menu.style.ts
Labels: Fix

#831 implemented account privacy in experience and friend tab
  src/components/FriendsMenu/FriendList.container.tsx
  src/components/Profile/ExperienceTabPanel/ExperienceTabPanel.container.tsx
  src/components/Profile/PostTabPanel/PostTabPanel.container.tsx
  src/components/UserMenu/hooks/user-tabs.hooks.tsx
  src/components/UserSettings/UserSettings.styles.ts
  src/components/UserSocials/UserSocials.tsx
Labels: Fix, Improvement

#833 highlight list when hover to x button
  src/components/ExperienceEditor/Experience.styles.ts
  src/components/atoms/ListItem/ListItemPeople.tsx
Labels: Fix

#834 bug fixed prevent abusing accept friend request
  src/components/FriendsMenu/FriendRequest.container.tsx
  src/components/Profile/ProfileHeader/ProfileHeaderContainer.tsx
Labels: bug, Fix

#837 fixed sorting posts in profile
  src/components/Profile/PostTabPanel/PostTabPanel.container.tsx
  src/components/Timeline/hooks/use-timeline-filter.hook.ts
  src/interfaces/timeline.ts
  src/lib/api/post.ts
  src/reducers/timeline/actions.ts
  src/reducers/timeline/reducer.ts
Labels: Fix, Improvement

#832 Adjust screen size style & Redirect API path
  .env-template
  next.config.js
  package.json
  server/index.ts
  src/components/FriendsMenu/friend.style.tsx
  src/components/NFT/nft.style.ts
  src/components/PostDetail/PostDetail.styles.ts
  src/components/Profile/profile.style.ts
  src/components/ProfileHeader/profile-header.style.ts
  src/components/UserMenu/UserMenu.styles.ts
  src/components/atoms/SimpleCard/SimpleCard.style.ts
  src/components/template/Default/DefaultLayout.styles.ts
  src/lib/api/base.ts
  src/lib/api/healthcheck.ts
  src/themes/light-theme.ts
  yarn.lock
Labels: enhancement

#836 Change list item position to keep hover effect
  pages/index.tsx
  src/components/atoms/CommentDetail/CommentDetail.tsx
  src/components/atoms/ListItem/ListItemSocial.tsx
Labels: bug

#840 Fixed docker run
  .maintain/docker/Dockerfile
  package.json
Labels: Fix

#842 Fixed docker source file
  .maintain/docker/Dockerfile
Labels: Fix

#843 Limit character on editor
  server/index.ts
  src/components/PostEditor/PostEditor.styles.ts
  src/components/PostEditor/PostEditor.tsx
  src/components/PostEditor/plugins/charLimit/createCharLimitPlugin.ts
  src/components/PostEditor/plugins/charLimit/index.ts
  src/components/PostEditor/plugins/charLimit/withCharLimit.ts
  src/components/atoms/CommentEditor/CommentEditor.style.ts
  src/components/atoms/CommentEditor/CommentEditor.tsx
Labels: bug, enhancement

#844 fix styling and handle click on avatar
  src/components/FriendsMenu/FriendList.tsx
  src/components/FriendsMenu/friend.style.tsx
  src/components/atoms/Dropzone/Dropzone.styles.ts
  src/components/atoms/Dropzone/Dropzone.tsx
  src/components/atoms/SimpleCard/SimpleCard.style.ts
Labels: Fix

#835 Added checking transaction fee feature
  src/components/SendTip/SendTip.tsx
  src/hooks/use-polkadot-api.hook.ts
  src/lib/services/polkadot-js.ts
  src/reducers/wallet/actions.ts
  src/reducers/wallet/constants.ts
  src/reducers/wallet/reducer.ts
Labels: enhancement

#847 MYR-1501: corrected grammar on text
  src/components/ExperienceList/NonSelectableExperienceList.tsx
  src/components/FriendsMenu/FriendList.tsx
  src/components/Login/render/Options/Options.tsx
  src/components/Login/render/Profile/Profile.tsx
  src/components/Notifications/hooks/use-notification-list.hook.tsx
  src/components/PostDedicated/PostDedicated.container.tsx
  src/components/PostVisibility/PostVisibility.container.tsx
  src/components/PostVisibility/PostVisibility.tsx
  src/components/PostsList/PostsListContainer.tsx
  src/components/PrimaryCoinMenu/PrimaryCoinMenu.tsx
  src/components/Profile/PostTabPanel/PostTabPanel.container.tsx
  src/components/Profile/ProfileHeader/ProfileHeaderContainer.tsx
  src/components/Profile/ProfileHeader/index.tsx
  src/components/Profile/edit/ProfileEditContainer.tsx
  src/components/Timeline/Timeline.tsx
  src/components/Timeline/TimelineContainer.tsx
  src/components/UserSocials/UserSocials.tsx
  src/components/atoms/BannerStatus/BannerStatus.tsx
  src/components/atoms/CommentList/CommentList.container.tsx
  src/components/atoms/Search/SearchBox.tsx
  src/components/atoms/SimpleCard/SimpleCard.tsx
Labels: Improvement

#850 add load more comment and change handle failed import post
  src/components/PostCreate/PostCreate.container.tsx
  src/components/atoms/CommentList/CommentList.container.tsx
  src/components/atoms/Prompt/prompt.style.ts
  src/hooks/use-comment.hook.ts
  src/lib/api/comment.ts
  src/lib/api/interfaces/base-list.interface.ts
  src/reducers/timeline/actions.ts
Labels: bug, Fix

#846 fixed block behaviour
  src/components/FriendsMenu/FriendList.tsx
  src/components/Timeline/hooks/use-timeline-filter.hook.ts
  src/interfaces/timeline.ts
  src/lib/api/experience.ts
  src/lib/api/post.ts
  src/reducers/experience/actions.ts
Labels: Fix

#852 Handle editor text limit for multiple insert
  src/components/PostEditor/plugins/charLimit/withCharLimit.ts
Labels: bug

#853 redirect notification reply comment and fix wording link social media
  src/components/Notifications/hooks/use-notification-list.hook.tsx
  src/components/atoms/CommentDetail/CommentDetail.tsx
  src/components/atoms/CommentList/CommentList.tsx
Labels: Fix

#854 fixed arrow coin behaviour
  src/components/BalanceDetailList/BalanceDetailList.tsx
  src/components/BalanceDetailList/BalanceDetailListContainer.tsx
  src/components/PrimaryCoinMenu/PrimaryCoinMenu.tsx
  src/components/PrimaryCoinMenu/PrimaryCoinMenuContainer.tsx
  src/components/WalletBalance/WalletBalanceContainer.tsx
  src/components/template/Default/DefaultLayout.tsx
  src/hooks/use-currency.hook.ts
  src/interfaces/currency.ts
  src/lib/api/token.ts
  src/reducers/balance/actions.ts
  src/reducers/balance/constants.ts
  src/reducers/balance/reducer.ts
Labels: Fix, Improvement

#855 minor fixed a variable query
  src/lib/api/post.ts
Labels: Fix

#864 Add node selector
  .github/workflows/deploy.yml
Labels: CI

#856 fixed styling and cta
  src/components/AddSocialMedia/AddSocialMedia.tsx
  src/components/Profile/ProfileHeader/index.tsx
  src/components/Profile/ProfileHeader/profile-header.style.ts
  src/components/SocialMediaList/SocialMediaListContainer.tsx
  src/components/Socials/Socials.container.tsx
  src/components/UserSocials/UserSocials.styles.ts
  src/components/UserSocials/UserSocials.tsx
  src/components/atoms/Prompt/prompt.style.ts
Labels: Fix, Improvement

#858 fixed styling for profile header
  src/components/ProfileHeader/ProfileHeader.tsx
  src/components/ProfileHeader/profile-header.style.ts
Labels: Fix

#862 Improvement on Success Prompt after Sending Tip
  src/components/FriendsMenu/FriendList.tsx
  src/components/PostDedicated/PostDedicated.container.tsx
  src/components/PostsList/PostsListContainer.tsx
  src/components/Profile/PostTabPanel/PostTabPanel.container.tsx
  src/components/Timeline/TimelineContainer.tsx
  src/reducers/wallet/actions.ts
Labels: Fix

#865 Fix behavior when decline / reject button is abused
  src/components/FriendsMenu/FriendRequest.container.tsx
  src/components/Help/Help.tsx
  src/components/Profile/ProfileHeader/ProfileHeaderContainer.tsx
Labels: Fix

#857 Listen to balance change
  package.json
  src/components/BalanceDetailList/BalanceDetailList.tsx
  src/components/BalanceDetailList/BalanceDetailListContainer.tsx
  src/components/MyWallet/MyWalletContainer.tsx
  src/components/PrimaryCoinMenu/PrimaryCoinMenu.tsx
  src/components/SendTip/SendTipContainer.tsx
  src/components/WalletBalance/WalletBalance.stories.tsx
  src/components/WalletBalance/WalletBalanceContainer.tsx
  src/hooks/use-polkadot-api.hook.ts
  src/interfaces/balance.ts
  src/lib/services/errors/NoAccountException.ts
  src/lib/services/polkadot-js.ts
  src/reducers/balance/actions.ts
  src/reducers/balance/constants.ts
  src/reducers/balance/reducer.ts
  yarn.lock
Labels: bug, enhancement

#866 fixed button color and wording
  src/components/FriendsMenu/FriendList.tsx
  src/components/FriendsMenu/friend.style.tsx
Labels: Fix

#867 MYR-1484: forced username input toLowerCase
  src/components/Login/render/Profile/Profile.tsx
Labels: Fix

#868 Reduce multiple API call
  pages/api/auth/[...nextauth].ts
  pages/experience/[experienceId]/clone.tsx
  pages/experience/[experienceId]/edit.tsx
  pages/experience/[experienceId]/preview.tsx
  pages/experience/create.tsx
  pages/friends.tsx
  pages/home.tsx
  pages/post/[postId].tsx
  pages/profile/[id].tsx
  pages/search.tsx
  pages/settings.tsx
  pages/socials.tsx
  pages/socialtoken.tsx
  pages/topic/[type].tsx
  pages/wallet.tsx
  src/components/BlockUserList/BlockList.container.tsx
  src/components/ExperienceTabMenu/ExperienceTabMenuContainer.tsx
  src/components/FriendsMenu/FriendList.container.tsx
  src/components/FriendsMenu/FriendRequest.container.tsx
  src/components/MyWallet/MyWalletContainer.tsx
  src/components/PostCreate/PostCreate.container.tsx
  src/components/TipHistory/TipHistory.tsx
  src/components/atoms/CommentDetail/CommentDetail.interface.ts
  src/components/atoms/CommentDetail/CommentDetail.tsx
  src/components/atoms/CommentList/CommentList.container.tsx
  src/components/atoms/CommentList/CommentList.tsx
  src/components/template/Default/DefaultLayout.tsx
  src/hooks/use-experience-hook.ts
  src/hooks/use-friends-hook.ts
  src/lib/api/friends.ts
  src/reducers/friend-request/actions.ts
  src/reducers/friend/actions.ts
Labels: bug, Improvement

#870 Update next link implementation
  .eslintrc.js
  next.config.js
  src/components/ExperiencePreview/ExperiencePreview.tsx
  src/components/FriendsMenu/FriendList.tsx
  src/components/FriendsMenu/FriendRequest.tsx
  src/components/FriendsMenu/friend.style.tsx
  src/components/Leaderboard/LeaderBoard.tsx
  src/components/Login/render/Login/Login.tsx
  src/components/Notifications/Notifications.tsx
  src/components/PolkadotAccountList/PolkadotAccountList.tsx
  src/components/PostEditor/PostRender.tsx
  src/components/PostImporterList/PostImporter.tsx
  src/components/Profile/ProfileHeader/index.tsx
  src/components/Profile/edit/ProfileEdit.tsx
  src/components/Trending/TrendingList.tsx
  src/components/atoms/CommentDetail/CommentDetail.tsx
  src/components/atoms/CommentDetail/CommentRender.tsx
  src/components/atoms/ListItem/ListItemSocial.tsx
  src/components/atoms/PostHeader/subHeader/post-sub-header.component.tsx
  src/components/atoms/SimpleCard/SimpleCard.tsx
  src/components/common/banner-demo.component.tsx
Labels: bug

#871 Added Build ID
  .github/workflows/builder.yml
  .maintain/docker/Dockerfile
Labels: CI

#861 Add nsfw tag to imported post & Myriad logo redirect to home
  src/components/Menu/Menu.styles.ts
  src/components/Menu/Menu.tsx
  src/components/PostCreate/PostCreate.container.tsx
  src/components/PostCreate/PostCreate.tsx
  src/components/template/Default/DefaultLayout.tsx
  src/interfaces/post.ts
  src/lib/api/post.ts
  src/lib/services/polkadot-js.ts
  src/reducers/timeline/actions.ts
Labels: bug

#873 minor fixing
  src/components/Profile/ProfileHeader/index.tsx
  src/components/Report/Report.tsx
Labels: Fix

#874 Check device type instead of browser version
  pages/experience/[experienceId]/clone.tsx
  pages/experience/[experienceId]/edit.tsx
  pages/experience/[experienceId]/preview.tsx
  pages/experience/create.tsx
  pages/friends.tsx
  pages/home.tsx
  pages/index.tsx
  pages/leaderboard.tsx
  pages/mobile.tsx
  pages/nft.tsx
  pages/notification.tsx
  pages/post/[postId].tsx
  pages/profile/[id].tsx
  pages/search.tsx
  pages/settings.tsx
  pages/socials.tsx
  pages/socialtoken.tsx
  pages/topic/[type].tsx
  pages/wallet.tsx
  pages/welcome.tsx
Labels: bug

#876 Added web app secret
  .github/workflows/deploy.yml
Labels: CI

#878 Change meta & embed link of nswf post
  pages/embed.tsx
  pages/post/[postId].tsx
Labels: bug

#879 Use primary account on click social list
  src/components/SocialMediaList/use-social-media-list.hook.tsx
Labels: bug

#881 revise word
  src/components/Login/render/Profile/Profile.tsx
  src/components/Search/SearchResultContainer.tsx
  src/components/Settings/AccountSettingsContainer.tsx
  src/components/Settings/NotificationSettings.container.tsx
Labels: Fix

#877 improved add coin wallet
  src/components/atoms/AddCoin/AddCoin.component.tsx
  src/components/atoms/AddCoin/AddCoin.style.ts
Labels: Fix

#859 Refactor authentication flow
  package.json
  pages/api/[...all].ts
  pages/api/auth/[...nextauth].ts
  pages/experience/[experienceId]/clone.tsx
  pages/experience/[experienceId]/edit.tsx
  pages/experience/[experienceId]/preview.tsx
  pages/experience/create.tsx
  pages/friends.tsx
  pages/home.tsx
  pages/notification.tsx
  pages/profile/[id].tsx
  pages/search.tsx
  pages/settings.tsx
  pages/socials.tsx
  pages/topic/[type].tsx
  pages/wallet.tsx
  server/index.ts
  src/components/Login/Login.tsx
  src/components/Login/render/Accounts/Accounts.tsx
  src/components/Login/render/Profile/Profile.tsx
  src/hooks/auth.hook.ts
  src/hooks/use-profile.hook.ts
  src/interfaces/session.ts
  src/lib/api/base.ts
  src/lib/api/ext-auth.ts
  src/lib/api/user.ts
  src/lib/crypto.ts
  src/lib/serializers/session.ts
  src/lib/services/polkadot-js.ts
Labels: Feature

#880 implement i18n
  package.json
  pages/_app.tsx
  src/components/Settings/LanguageSetting.tsx
  src/components/Settings/LanguageSettingsContainer.tsx
  src/components/Settings/default.ts
  src/components/Settings/hooks/use-setting-list.hook.tsx
  src/interfaces/setting.ts
  src/locale/en.json
  src/locale/id.json
  src/locale/index.tsx
  src/reducers/config/actions.ts
  src/reducers/config/constants.ts
  src/reducers/config/reducer.ts
  yarn.lock
Labels: Feature

#882 Implement switch account with auth
  pages/home.tsx
  src/components/Login/Login.tsx
  src/components/Login/render/Accounts/Accounts.tsx
  src/components/Login/render/Login/Login.tsx
  src/components/ProfileHeader/ProfileHeaderContainer.tsx
  src/components/atoms/CommentDetail/CommentDetail.tsx
  src/hooks/auth.hook.ts
  src/hooks/use-polkadot-app.hook.ts
  src/interfaces/user.ts
  src/lib/api/base.ts
  src/lib/api/user.ts
  yarn.lock
Labels: enhancement, Feature

#883 Exclude deleted post from timeline
  pages/api/[...all].ts
  pages/post/[postId].tsx
  src/lib/api/post.ts
Labels: bug

#869 update params search post, and topic
  src/lib/api/post.ts
  src/locale/en.json
Labels: Fix

#884 Fix error message on toaster when RPC connection failed
  src/reducers/balance/actions.ts
Labels: Improvement

#885 Return to all post tab on create post
  src/components/Richtext/RichTextContainer.tsx
Labels: bug

#887 myr-1505: fix ux on handling save profile
  src/components/Profile/edit/ProfileEdit.tsx
Labels: bug, Fix

#889 revise wording
  src/components/AddSocialMedia/AddSocialMedia.tsx
  src/components/BlockUserList/BlockList.tsx
  src/components/Profile/ProfileComponent.tsx
  src/locale/en.json
Labels: good first issue, Fix

#890 improved replies comment
  src/components/atoms/CommentDetail/CommentDetail.tsx
Labels: good first issue, Fix

#891 minor fixing
  src/components/PostImporterList/PostImporter.tsx
  src/lib/api/post.ts
Labels: bug

#892 update comment data
  src/components/atoms/CommentDetail/CommentDetail.tsx
  src/hooks/use-replies.hook.ts
Labels: bug

#888 Cleanup
  .env-template
  .github/workflows/analyzer.yml
  .github/workflows/builder.yml
  .github/workflows/deployer.yml
  .github/workflows/tester.yml
  .maintain/docker/Dockerfile
  .prettierignore
  adapters/api.ts
  next.config.js
  pages/api/auth/[...nextauth].ts
  pages/embed.tsx
  pages/post/[postId].tsx
  pages/profile/[id].tsx
  src/components/AddSocialMedia/AddSocialMedia.tsx
  src/components/atoms/BannerStatus/BannerStatus.tsx
  src/hooks/auth.hook.ts
  src/lib/api/base.ts
Labels: CI

#893 update message and onclick notification on post removed
  pages/api/[...all].ts
  src/components/Notifications/Notifications.tsx
  src/components/Notifications/hooks/use-notification-list.hook.tsx
Labels: Fix

#894 bug fixed hide the profile after block
  pages/profile/[id].tsx
  src/components/Profile/ProfileComponent.tsx
Labels: bug, good first issue

#895 fix handle failed error message import post
  src/components/PostCreate/PostCreate.container.tsx
  src/reducers/timeline/actions.ts
Labels: Fix

#886 Create Pagination for User and Experience on search result
  src/components/ExperienceList/SearchedExperienceList.tsx
  src/components/ExperienceList/SearchedExperienceListContainer.tsx
  src/components/ExperienceList/experience-list.interfaces.ts
  src/components/Search/SearchResultContainer.tsx
  src/components/UsersList/UsersList.tsx
  src/components/UsersList/UsersListContainer.tsx
  src/hooks/use-experience-hook.ts
  src/hooks/use-search.hooks.ts
  src/lib/api/experience.ts
  src/lib/api/user.ts
  src/reducers/experience/actions.ts
  src/reducers/experience/constants.ts
  src/reducers/experience/reducer.ts
  src/reducers/search/actions.ts
  src/reducers/search/constants.ts
  src/reducers/search/reducer.ts
Labels: Improvement

#896 Anonym login
  pages/api/[...all].ts
  pages/api/auth/[...nextauth].ts
  pages/friends.tsx
  pages/post/[postId].tsx
  pages/profile/[id].tsx
  src/components/ProfileHeader/ProfileHeaderContainer.tsx
  src/hooks/use-user.hook.ts
  src/lib/api/user.ts
Labels: bug

#897 MYR-000: fixed friendlist
  src/components/FriendsMenu/FriendList.container.tsx
  src/components/FriendsMenu/FriendRequest.container.tsx
  src/hooks/use-friends-hook.ts
  src/reducers/friend/actions.ts
Labels: bug, good first issue

#898 Search anonymous
  pages/search.tsx
  src/components/Search/SearchResultContainer.tsx
  src/components/Settings/Settings.tsx
  src/lib/api/experience.ts
  src/lib/api/post.ts
  src/lib/api/user.ts
  src/reducers/search/actions.ts
  src/reducers/timeline/actions.ts
Labels: bug

#900 fixed profile header when login as anonymous
  src/components/FriendsMenu/FriendList.tsx
  src/components/Profile/ProfileHeader/ProfileHeaderContainer.tsx
  src/components/Profile/ProfileHeader/index.tsx
Labels: Fix

#901 Fixed next cache
  .dockerignore
  .eslintignore
  .gitignore
  .lintstagedrc.json
  docs/.gitkeep
  package.json
  tsconfig.json
Labels: Fix

#902 add userid on search fetch
  pages/search.tsx
Labels: bug

#903 bugfixed anonymous can't send report
  src/components/Report/Report.container.tsx
  src/hooks/use-report.hook.ts
Labels: bug

#904 bug fixed search hashtag
  src/lib/api/post.ts
Labels: bug

#905 Fixed shown balance length to 4 decimal place
  src/components/BalanceDetailList/BalanceDetailList.tsx
  src/components/HistoryDetailList/HistoryDetailList.tsx
  src/components/PrimaryCoinMenu/DraggableBalanceCard.tsx
  src/components/SendTip/SendTip.tsx
  src/components/WalletBalance/index.tsx
  src/components/atoms/CurrencyOption/index.tsx
Labels: Improvement

#906 Remove meta from imported post
  pages/post/[postId].tsx
Labels: bug

#908 cleared searched people from autocomplete list after adding new people
  src/components/ExperienceEditor/ExperienceEditor.tsx
Labels: Improvement

#909 fix styling
  src/components/ExperiencePreview/ExperiencePreview.tsx
  src/components/ExperiencePreview/experience.style.ts
  src/components/PostDetail/PostDetail.styles.ts
  src/components/PostEditor/Render/ShowMore/index.tsx
  src/components/Profile/ProfileHeader/index.tsx
  src/components/atoms/CommentDetail/CommentDetail.tsx
  src/components/atoms/SimpleCard/SimpleCard.style.ts
  src/components/atoms/SimpleCard/SimpleCard.tsx
  src/components/atoms/TopNavbar/top-navbar.styles.ts
Labels: Fix
