Repository myriadsocial/myriad-web, pull requests merged in 2022-06, with the labels that each got.

#1224 Add sleuth webhook
  .github/workflows/deployer.yml
Labels: CI

#1226 Update mobile layout on profile page
  src/components/Metric/Metric.style.ts
  src/components/Metric/Metric.tsx
  src/components/ProfileCard/ProfileContent.tsx
  src/components/ProfileCard/profileContent.style.ts
  src/components/ProfileEdit/ProfileEdit.tsx
  src/components/ProfileEdit/profile-edit.style.ts
  src/components/ProfileHeader/index.tsx
  src/components/ProfileHeader/profile-header.style.ts
  src/components/Timeline/Timeline.styles.ts
  src/components/TimelineFilter/TimelineFilter.tsx
  src/components/UserMenu/UserMenu.tsx
  src/components/atoms/DropdownMenu/DropdownMenu.styles.ts
  src/components/atoms/TabList/TabList.styles.ts
  src/components/atoms/TabList/TabList.tsx
  src/components/atoms/Tabs/Tabs.styles.ts
  src/locale/id.json
Labels: enhancement

#1228 Added responsive Login flow on mobile view
  pages/index.tsx
  src/components/Login/Login.tsx
  src/components/Login/render/Options/Options.style.ts
  src/components/Login/render/Options/Options.tsx
  src/components/Mobile/OnBoardingView/CarouselLoginView.tsx
  src/components/Mobile/OnBoardingView/OnBoardingView.container.tsx
  src/components/template/Login/Mobile.tsx
  src/components/template/Login/index.ts
  src/images/illustration/Ilustrasi_1.svg
  src/images/illustration/Ilustrasi_2.svg
  src/images/illustration/Ilustrasi_3.svg
  src/locale/en.json
  src/locale/id.json
Labels: Improvement

#1227 fix drawer, wallet, and trending experience on mobile view
  package.json
  pages/experience/trending.tsx
  src/components/BalanceDetailList/balance-detail-list.style.ts
  src/components/Menu/use-menu-list.tsx
  src/components/Mobile/MenuDrawer/MenuDrawer.tsx
  src/components/Mobile/MenuDrawer/menuDrawer.style.ts
  src/components/RightMenuBar/tabs/ExperienceTab.tsx
  src/components/atoms/TopNavbar/TopNavbar.interfaces.ts
  src/locale/en.json
  src/locale/id.json
Labels: Improvement

#1229 Fixed error when mobile signing in anonymously
  src/components/ProfileCard/ProfileContent.tsx
Labels: Improvement

#1232 fix style mobile view nft, social token
  src/components/NFT/nft.style.ts
Labels: Fix

#1233 Update mobile view for post create
  src/components/EmbedURL/EmbedURL.styles.ts
  src/components/NSFWTags/NSFWTags.tsx
  src/components/PostCreate/PostCreate.container.tsx
  src/components/PostCreate/PostCreate.styles.ts
  src/components/PostCreate/PostCreate.tsx
  src/components/PostEditor/PostEditor.styles.ts
  src/components/PostEditor/PostEditor.tsx
  src/components/PostEditor/Toolbar/ToolbarElement.tsx
  src/components/PostImport/PostImport.styles.ts
  src/components/PostTag/PostTags.styles.ts
  src/components/Upload/Upload.styles.ts
  src/components/atoms/DropdownMenu/DropdownMenu.styles.ts
  src/components/atoms/DropdownMenu/DropdownMenu.tsx
  src/components/atoms/Embed/Embed.styles.ts
  src/components/atoms/Embed/Embed.tsx
  src/components/atoms/Modal/Modal.styles.ts
  src/components/atoms/Modal/Modal.tsx
  src/components/atoms/TopNavbar/TopNavbar.interfaces.ts
  src/components/atoms/TopNavbar/TopNavbar.tsx
Labels: enhancement

#1225 Improvement connecting social media through blockchain
  pages/api/access-token.ts
  pages/socials.tsx
  src/components/AddSocialMedia/AddSocialMedia.styles.ts
  src/components/AddSocialMedia/AddSocialMedia.tsx
  src/components/SocialMediaList/SocialMediaList.container.tsx
  src/components/Socials/Socials.container.tsx
  src/components/Socials/Socials.tsx
  src/hooks/use-share-social.ts
  src/lib/api/social.ts
  src/lib/api/wallet.ts
  src/lib/services/polkadot-js.ts
  src/locale/en.json
  src/locale/id.json
  src/reducers/user/actions.ts
Labels: Improvement

#1236 fixed translation doesn't change
  pages/settings.tsx
  src/components/BalanceDetailList/BalanceDetailList.tsx
  src/components/CommentHistoryList/CommentHistoryList.tsx
  src/components/FriendsMenu/FriendList.tsx
  src/components/FriendsMenu/default.ts
  src/components/Profile/tabs/ExperienceTab.tsx
  src/components/RightMenuBar/tabs/TrendingExperienceTab.tsx
  src/components/Timeline/default.ts
  src/components/TipHistory/TipHistory.tsx
Labels: Fix

#1238 fix style responsive banner
  src/components/Menu/Menu.tsx
  src/components/Menu/use-menu-list.tsx
  src/components/atoms/BannerStatus/BannerStatus.tsx
  src/components/atoms/BannerStatus/banner.style.ts
Labels: Improvement

#1239 Fixed social media verification
  src/hooks/use-share-social.ts
Labels: Improvement

#1240 fix margin in login mobile
  src/components/Mobile/OnBoardingView/CarouselLoginView.tsx
Labels: Fix

#1242 Enlarged width for Cookies window
  src/components/common/CookieConsent/CookieConsent.style.ts
Labels: Fix

#1243 Ensured nearAccount is cleared when logging out
  src/components/Mobile/MenuDrawer/MenuDrawer.tsx
Labels: Fix

#1244 Update timeline empty placeholder style
  src/components/Timeline/TimelineEmpty.tsx
Labels: Improvement

#1246 Update create experience validation
  src/components/ExperienceEditor/Experience.styles.ts
  src/components/ExperienceEditor/ExperienceEditor.tsx
  src/components/ExperiencePreview/ExperienceClone.container.tsx
  src/components/ExperiencePreview/ExperienceEdit.container.tsx
  src/components/ProfileCard/ProfileContent.tsx
  src/components/ProfileCard/profileContent.style.ts
  src/components/atoms/Dropzone/Dropzone.styles.ts
  src/components/atoms/Dropzone/Dropzone.tsx
  src/locale/en.json
  src/locale/id.json
Labels: Improvement

#1247 Fix experience validation translation
  src/locale/en.json
  src/locale/id.json
Labels: Improvement

#1248 fix grammar on english translation and logout anonymous
  src/components/Mobile/MenuDrawer/MenuDrawer.tsx
  src/components/atoms/BannerStatus/banner.style.ts
  src/locale/en.json
Labels: bug, Improvement

#1249 fixed avatar and display name for banned user
  src/components/HistoryDetailList/HistoryDetailList.tsx
Labels: Fix

#1251 Fix anonymous tipping & prompt
  src/components/atoms/Prompt/prompt.component.tsx
  src/components/atoms/Prompt/prompt.style.ts
  src/components/atoms/Prompt/prompt.ts
  src/components/atoms/Tabs/Tabs.styles.ts
  src/components/common/Confirm/Confirm.style.ts
  src/components/common/SendTipButton/SendTipButton.tsx
  src/components/common/Tipping/Tipping.context.ts
  src/components/common/Tipping/Tipping.interface.ts
  src/components/common/Tipping/Tipping.provider.tsx
  src/components/template/Default/DefaultLayout.tsx
  src/reducers/balance/actions.ts
  src/reducers/balance/constants.ts
  src/reducers/balance/reducer.ts
  src/reducers/tip-summary/actions.ts
Labels: bug

#1252 Update validation on form change
  src/components/ExperienceEditor/ExperienceEditor.tsx
  src/locale/en.json
  src/locale/id.json
Labels: bug

#1253 Fix margin on profile
  src/components/CommentHistoryList/CommentHistoryList.container.tsx
  src/components/CommentHistoryList/CommentHistoryList.style.ts
  src/components/CommentHistoryList/CommentHistoryList.tsx
  src/components/FriendsMenu/FriendMenu.tsx
  src/components/FriendsMenu/friend.style.tsx
  src/components/FriendsMenu/friendRequest.style.ts
  src/components/PostDetail/PostDetail.tsx
  src/components/Profile/EmptyProfilePost.tsx
  src/components/Profile/tabs/ExperienceTab.tsx
  src/components/ProfileHeader/index.tsx
  src/components/ProfileHeader/profile-header.style.ts
  src/components/Timeline/TimelineEmpty.tsx
  src/components/UserSettings/UserSettings.styles.ts
  src/components/UserSettings/UserSettings.tsx
  src/components/UserSocials/UserSocials.styles.ts
  src/components/UserSocials/UserSocials.tsx
  src/components/atoms/Empty/Empty.styles.ts
  src/components/atoms/Tabs/Tabs.styles.ts
  src/components/atoms/Tabs/Tabs.tsx
  src/locale/en.json
  src/locale/id.json
Labels: Improvement

#1254 Update translation create experience
  src/components/ExperienceEditor/ExperienceEditor.tsx
  src/components/Profile/Profile.style.ts
Labels: Improvement

#1255 fix style responsive wallet menu
  pages/_app.tsx
  src/components/BalanceDetailList/balance-detail-list.style.ts
  src/components/HistoryDetailList/HistoryDetailList.styles.ts
  src/components/HistoryDetailList/HistoryDetailList.tsx
  src/components/HistoryDetailList/HistoryFilterModal.tsx
  src/components/Login/render/Options/Options.tsx
  src/components/Manage/Manage.container.tsx
  src/components/Manage/Manage.tsx
  src/components/Manage/manage.style.ts
  src/components/MyWallet/MyWallet.tsx
  src/components/MyWallet/myWallet.style.ts
  src/components/atoms/DropdownMenu/DropdownMenu.styles.ts
  src/components/atoms/DropdownMenu/DropdownMenu.tsx
  src/locale/en.json
  src/locale/id.json
Labels: bug, Improvement

#1258 Update translation tipping anonymous
  src/locale/en.json
  src/locale/id.json
Labels: bug

#1259 Fix topbar on profile page
  src/components/Profile/Profile.tsx
  src/components/atoms/TopNavbar/TopNavbar.styles.ts
  src/components/atoms/TopNavbar/TopNavbar.tsx
  src/locale/en.json
  src/locale/id.json
Labels: bug

#1262 show language setting on demo account
  package.json
  src/components/Settings/hooks/use-setting-list.hook.tsx
  yarn.lock
Labels: bug

#1263 updates friend interface
  src/components/FriendsMenu/FriendList.tsx
  src/components/FriendsMenu/FriendMenu.style.ts
  src/components/FriendsMenu/FriendMenu.tsx
  src/components/FriendsMenu/FriendRequest.tsx
  src/components/FriendsMenu/friend.style.tsx
  src/components/FriendsMenu/friendRequest.style.ts
Labels: Improvement

#1264 add russian language
  src/components/Settings/LanguageSetting.tsx
  src/components/Settings/default.ts
  src/components/atoms/DropdownMenu/DropdownMenu.tsx
  src/interfaces/setting.ts
  src/locale/index.tsx
  src/locale/ru.json
Labels: Improvement

#1265 Fix upload image
  next.config.js
  pages/experience/[experienceId]/index.tsx
  pages/post/[postId].tsx
  src/components/EmbedURL/EmbedURL.styles.ts
  src/components/Expericence/Experience.tsx
  src/components/ExperienceEditor/Experience.container.tsx
  src/components/ExperienceEditor/ExperienceEditor.tsx
  src/components/ExperiencePreview/ExperienceClone.container.tsx
  src/components/ExperiencePreview/ExperienceEdit.container.tsx
  src/components/PostEditor/PostEditor.styles.ts
  src/components/PostVisibility/PostVisibility.tsx
  src/components/PostVisibility/postVisibility.styles.ts
  src/components/Report/Report.styles.ts
  src/components/Report/Report.tsx
  src/components/TipHistory/TipHistory.styles.ts
  src/components/Upload/Upload.styles.ts
  src/components/Upload/Upload.tsx
  src/components/atoms/Dropzone/Dropzone.styles.ts
  src/components/atoms/Dropzone/Dropzone.tsx
  src/components/atoms/Dropzone/File.skeleton.tsx
  src/components/atoms/Dropzone/Render/PreviewImage/Multiple.tsx
  src/components/atoms/Dropzone/Render/PreviewImage/Single.tsx
  src/components/atoms/Dropzone/Render/PreviewVideo.tsx
  src/components/atoms/Modal/Modal.styles.ts
  src/components/atoms/Modal/Modal.tsx
  src/themes/light-theme.ts
Labels: bug

#1266 bump version 2.1.4
  package.json
  src/components/Settings/Settings.styles.ts
  src/components/atoms/DropdownMenu/DropdownMenu.tsx
Labels: Improvement

#1267 update social media interface
  src/components/AddSocialMedia/AddSocialMedia.styles.ts
  src/components/AddSocialMedia/AddSocialMedia.tsx
Labels: Improvement

#1268 update experience mobile interface
  pages/experience/[experienceId]/clone.tsx
  pages/experience/[experienceId]/edit.tsx
  pages/experience/create.tsx
  pages/experience/index.tsx
  src/components/Expericence/Experience.style.ts
  src/components/ExperienceEditor/Experience.container.tsx
  src/components/ExperienceEditor/Experience.styles.ts
  src/components/ExperiencePreview/ExperienceClone.container.tsx
  src/components/ExperiencePreview/ExperienceEdit.container.tsx
  src/components/ExperiencePreview/ExperiencePreview.container.tsx
  src/components/ExperiencePreview/ExperiencePreview.tsx
  src/components/ExperiencePreview/experience.style.ts
  src/components/RightMenuBar/tabs/ExperienceTab.tsx
  src/components/RightMenuBar/tabs/Tab.style.ts
  src/components/atoms/Dropzone/Dropzone.styles.ts
  src/components/atoms/Dropzone/Dropzone.tsx
Labels: Improvement

#1269 Force logout if near wallet is not connected
  src/reducers/balance/actions.ts
Labels: bug

#1270 fix styling setting
  pages/privacy-policy.tsx
  pages/term-of-use.tsx
  src/components/Settings/LanguageSetting.tsx
  src/components/Settings/Settings.styles.ts
Labels: Improvement

#1271 Reset api auth header for anonymous user & update encryption key
  src/lib/api/base.ts
  src/lib/crypto.ts
Labels: bug

#1272 bump version 2.1.5
  package.json
  src/locale/en.json
Labels: Fix

#1273 Update report and tipping error style
  src/components/BalanceDetailList/BalanceDetailList.tsx
  src/components/PostCreate/PostCreate.styles.ts
  src/components/Report/Report.styles.ts
  src/components/Report/Report.tsx
  src/components/TipHistory/TipHistory.tsx
  src/components/atoms/DropdownMenu/DropdownMenu.styles.ts
  src/components/atoms/DropdownMenu/DropdownMenu.tsx
  src/components/atoms/Gallery/Gallery.styles.ts
  src/components/atoms/Gallery/Gallery.tsx
  src/components/atoms/Modal/Modal.styles.ts
  src/components/atoms/Modal/Modal.tsx
  src/components/atoms/Prompt/prompt.component.tsx
  src/components/atoms/Prompt/prompt.style.ts
  src/components/common/SendTipButton/SendTipButton.tsx
  src/locale/en.json
  src/locale/id.json
  src/locale/ru.json
Labels: bug

#1274 Update API header on anonymous
  pages/experience/[experienceId]/clone.tsx
  pages/experience/[experienceId]/edit.tsx
  pages/experience/[experienceId]/index.tsx
  pages/experience/create.tsx
  pages/friends.tsx
  pages/home.tsx
  pages/notification.tsx
  pages/post/[postId].tsx
  pages/profile/[id].tsx
  pages/search.tsx
  pages/settings.tsx
  pages/socials.tsx
  pages/topic/[type].tsx
  pages/wallet.tsx
  src/lib/api/base.ts
  src/locale/en.json
  src/locale/ru.json
Labels: bug

#1275 fix styling notification
  pages/notification.tsx
  src/components/Mobile/MenuDrawer/MenuDrawer.tsx
  src/components/Notifications/Notifications.styles.ts
  src/components/ProfileCard/ProfileContent.tsx
Labels: Improvement

#1276 fix mobile drawer style on safari
  package.json
  src/components/Mobile/MenuDrawer/menuDrawer.style.ts
Labels: bug, Improvement

#1277 Update post visibility checklist style
  src/components/PostVisibility/postVisibility.styles.ts
  src/components/Report/Report.styles.ts
Labels: bug

#1278 fix style language setting
  src/components/Settings/LanguageSetting.tsx
Labels: bug

#1279 Fix Post and Search Bar Translation
  src/components/Richtext/RichTextContainer.tsx
  src/components/Richtext/index.tsx
  src/components/Richtext/richText.interface.ts
Labels: bug

#1280 Handle near wallet login with hex address
  src/components/Manage/Manage.container.tsx
  src/hooks/auth.hook.ts
  src/lib/api/wallet.ts
Labels: Improvement

#1282 fix get trxhash on prompt success send tip near
  src/components/Mobile/MenuDrawer/menuDrawer.style.ts
  src/components/common/Tipping/render/Tipping.success.tsx
Labels: bug

#1284 fix experience mobile interface
  src/components/ExperienceList/ExperienceList.empty.tsx
  src/components/ExperiencePreview/experience.style.ts
  src/components/atoms/Dropzone/Dropzone.styles.ts
  src/components/atoms/Prompt/prompt.style.ts
  src/locale/en.json
Labels: Fix

#1286 fixed navigation button in navbar
  src/components/atoms/TopNavbar/TopNavbar.tsx
Labels: Fix

#1287 Enable search people by name & username
  src/components/ExperienceEditor/ExperienceEditor.tsx
Labels: bug

#1288 replaced unwanted color in demo account
  src/hooks/auth.hook.ts
Labels: Fix

#1289 Change button active status style on mobile post editor
  package.json
  src/components/PostEditor/PostEditor.styles.ts
  yarn.lock
Labels: bug

#1291 fix behavior on ios devices
  src/components/Mobile/MenuDrawer/menuDrawer.style.ts
Labels: bug, Improvement

#1293 fixed the mutual count not show
  src/reducers/friend/actions.ts
Labels: bug

#1290 fix avatar size on notification
  src/components/atoms/PostHeader/avatar/post-avatar.component.tsx
Labels: Improvement

#1292 Fix padding and margin primary coin menu
  src/components/PrimaryCoinMenu/DraggableBalanceCard.tsx
  src/components/PrimaryCoinMenu/primary-coin-menu.style.ts
Labels: Improvement

#1297 Prevent reload current wallet
  pages/404.tsx
  pages/home.tsx
  src/components/ProfileCard/ProfileCard.container.tsx
Labels: bug

#1294 updated Russian translation
  src/locale/en.json
  src/locale/ru.json
Labels: Improvement

#1299 Update not found page
  pages/404.tsx
  pages/maintenance.tsx
  pages/post/[postId].tsx
  public/images/illustration/error.png
  public/images/illustration/maintenance.png
  public/images/illustration/private.png
  src/components/Error/Error.style.ts
  src/components/Error/Error.tsx
  src/components/common/ResourceDeleted/ResourceDeleted.styles.ts
  src/components/common/ResourceDeleted/ResourceDeleted.tsx
  src/images/illustration/resource-deleted.svg
  src/images/illustration/undraw_Fall_is_coming_yl0x_1.svg
  src/images/illustration/unexpected-error.svg
  src/locale/en.json
  src/locale/id.json
  src/locale/ru.json
Labels: Improvement

#1301 feat: implement tipping to non myriad user with near
  .env-template
  next.config.js
  src/components/Tip/Tip.tsx
  src/components/Tip/tip.style.ts
  src/components/atoms/CurrencyOption/currencyOption.interface.ts
  src/components/atoms/CurrencyOption/index.tsx
  src/components/common/Tipping/Tipping.tsx
  src/hooks/use-claim-tip.hook.ts
  src/hooks/use-near-api.hook.ts
  src/lib/services/near-api-js.ts
  src/lib/services/polkadot-js.ts
Labels: Feature

#1303 add check new posts on timeline
  src/components/Timeline/Timeline.styles.ts
  src/components/Timeline/TimelineContainer.tsx
  src/hooks/use-scroll.hook.ts
  src/locale/en.json
  src/locale/id.json
  src/locale/ru.json
  src/reducers/timeline/actions.ts
Labels: Improvement

#1304 change wording for comment delete by admin
  src/components/CommentDetail/CommentRender.tsx
  src/interfaces/comment.ts
  src/locale/en.json
  src/locale/id.json
  src/locale/ru.json
Labels: Improvement

#1305 bump version 2.1.7
  package.json
Labels: Improvement

#1307 fix: tipping with near
  src/hooks/use-near-api.hook.ts
Labels: Improvement

#1308 Add Language switch button on Myriad Login Page
  src/components/Login/Login.tsx
  src/components/Mobile/OnBoardingView/OnBoardingView.container.tsx
  src/components/template/Login/Login.tsx
  src/hooks/use-language.hook.ts
  src/locale/en.json
  src/locale/id.json
Labels: Feature

#1309 fix margin modal confirmation
  src/components/common/Confirm/Confirm.style.ts
Labels: Improvement

#1311 fixed indicator margin in Carousel
  src/components/template/Login/Login.styles.ts
  src/components/template/Login/Login.tsx
Labels: Fix

#1312 fix filtering coin on tip history
  src/components/TipHistory/TipHistory.container.tsx
  src/components/TipHistory/TipHistory.styles.ts
  src/components/TipHistory/TipHistory.tsx
  src/hooks/tip-history.hook.ts
Labels: Improvement

#1313 Hide comment editor when user is banned
  src/components/CommentDetail/CommentDetail.tsx
  src/components/CommentList/CommentList.container.tsx
  src/components/common/Authorization/Authorization.provider.tsx
  src/components/common/Banner/Banner.style.ts
  src/locale/en.json
  src/locale/id.json
  src/locale/ru.json
Labels: bug, enhancement

#1314 Fixed styling the tabs on profile page
  src/components/TimelineFilter/TimelineFilter.styles.ts
  src/components/TimelineFilter/TimelineFilter.tsx
  src/components/UserMenu/UserMenu.styles.ts
  src/components/UserMenu/UserMenu.tsx
  src/components/atoms/TabList/TabList.styles.ts
  src/components/atoms/Tabs/Tabs.styles.ts
Labels: Fix
