Repository myriadsocial/myriad-web, pull requests merged in 2022-02, with the labels that each got.

#907 Time format for timestamps
  src/components/HistoryDetailList/HistoryDetailList.tsx
  src/components/TipHistory/TipHistory.tsx
  src/components/atoms/PostHeader/subHeader/post-sub-header.component.tsx
  src/helpers/date.ts
Labels: Improvement

#911 Fixed styling for overlapping texts on TipHistory
  src/components/TipHistory/TipHistory.tsx
Labels: Improvement

#912 Added tx history for tipped sent from TipHistory modal
  src/components/HistoryDetailList/HistoryDetailList.tsx
  src/components/Timeline/TimelineContainer.tsx
  src/components/TipHistory/TipHistory.tsx
  src/helpers/number.ts
  src/hooks/use-polkadot-api.hook.ts
Labels: bug

#913 handle double hashtag
  src/components/ExperienceEditor/ExperienceEditor.tsx
Labels: bug

#914 minor fixing
  src/lib/api/post.ts
Labels: Fix

#915 Max hashtag char & format hashtag on pasted text
  src/components/PostEditor/PostEditor.tsx
  src/components/PostEditor/plugins/hashtag/createHashtagPlugin.ts
  src/components/PostEditor/plugins/hashtag/withHashtag.ts
  src/components/Profile/ProfileComponent.tsx
Labels: bug

#916 Handled showing balance correctly when tipping consecutively
  src/components/Notifications/hooks/use-notification-list.hook.tsx
  src/components/WalletBalance/WalletBalance.stories.tsx
  src/interfaces/balance.ts
  src/reducers/balance/actions.ts
  src/reducers/balance/reducer.ts
Labels: bug

#917 fix sorting post and block list
  src/components/BlockUserList/BlockList.container.tsx
  src/components/PostDetail/PostDetail.tsx
  src/components/UserMenu/UserMenu.container.tsx
  src/components/atoms/CommentList/CommentList.container.tsx
  src/components/atoms/PostHeader/index.tsx
  src/components/atoms/PostHeader/postHeader.interface.ts
Labels: bug

#918 Remove create post on anonym
  pages/404.tsx
  src/components/FriendsMenu/FriendList.tsx
  src/components/Menu/MenuContainer.tsx
  src/components/Richtext/RichTextContainer.tsx
Labels: bug

#919 Handle multiple hashtag on copy & paste text
  src/components/PostEditor/plugins/hashtag/withHashtag.ts
Labels: bug

#920 Remove meta if image exist
  pages/post/[postId].tsx
  src/components/PostDetail/PostDetail.tsx
  src/components/atoms/Gallery/Gallery.styles.ts
Labels: bug

#922 fix handling trigger update profile active button
  src/components/Profile/edit/ProfileEdit.tsx
Labels: Fix

#921 Handled sending tip from tip history via comments
  src/components/Timeline/TimelineContainer.tsx
  src/components/TipHistory/TipHistory.container.tsx
Labels: bug

#923 Handle hashtag at start of word
  src/components/PostEditor/plugins/hashtag/withHashtag.ts
Labels: bug

#925 Handled opening success prompt after sending tip
  src/components/Timeline/TimelineContainer.tsx
Labels: bug

#926 handle auto detect friend when unfriend
  src/components/Profile/ProfileHeader/index.tsx
  src/reducers/profile/actions.ts
  src/reducers/profile/constants.ts
  src/reducers/profile/reducer.ts
Labels: Fix

#928 hide post from other user who is not friend
  pages/post/[postId].tsx
  src/interfaces/setting.ts
Labels: bug

#927 Add skeleton loader on search
  package.json
  pages/home.tsx
  src/components/ExperienceList/SearchedExperienceListContainer.tsx
  src/components/PostDetail/PostDetail.skeleton.tsx
  src/components/PostDetail/index.ts
  src/components/PostsList/PostsListContainer.tsx
  src/components/Profile/ProfileComponent.tsx
  src/components/UsersList/UsersList.tsx
  src/components/UsersList/UsersListContainer.tsx
  src/components/UsersList/UsersListItem.skeleton.tsx
  src/components/atoms/SimpleCard/NonSelectableSimpleCard.skeleton.tsx
  src/hooks/use-experience-hook.ts
  src/hooks/use-search.hooks.ts
  src/reducers/experience/actions.ts
  src/reducers/experience/constants.ts
  src/reducers/experience/reducer.ts
  src/reducers/search/actions.ts
  src/reducers/search/constants.ts
  src/reducers/search/reducer.ts
  src/reducers/timeline/actions.ts
  src/reducers/timeline/constants.ts
  src/reducers/timeline/reducer.ts
  yarn.lock
Labels: bug

#929 Handled making explorerURL accessible after sending tip for transaction detail
  src/components/ExperienceList/ExperienceList.stories.tsx
  src/components/Timeline/TimelineContainer.tsx
  src/components/TipHistory/TipHistory.stories.tsx
  src/components/WalletBalance/WalletBalance.stories.tsx
  src/components/atoms/TabList/TabList.tsx
  src/hooks/use-polkadot-api.hook.ts
  src/interfaces/balance.ts
  src/interfaces/currency.ts
  src/lib/services/polkadot-js.ts
  src/reducers/wallet/actions.ts
  src/reducers/wallet/constants.ts
  src/reducers/wallet/reducer.ts
Labels: bug

#930 disable button comment and fix style
  src/components/PostDetail/hooks/use-comment-tabs.tsx
  src/components/atoms/CommentEditor/CommentEditor.style.ts
  src/components/atoms/CommentEditor/CommentEditor.tsx
Labels: Fix

#931 Fix hashtag multiple paragraph
  src/components/PostEditor/plugins/hashtag/withHashtag.ts
Labels: bug

#932 Handle no extension installed
  src/components/Login/render/Options/Options.tsx
Labels: bug

#933 Fix word break on comment
  src/components/atoms/CommentDetail/CommentRender.tsx
Labels: bug

#934 setup translation page and component
  pages/home.tsx
  pages/index.tsx
  src/components/Login/render/Accounts/Accounts.tsx
  src/components/Login/render/Login/Login.tsx
  src/components/Login/render/Options/Options.tsx
  src/components/Login/render/Profile/Profile.tsx
  src/components/PostCreate/PostCreate.container.tsx
  src/components/atoms/Search/SearchBox.tsx
  src/components/template/Login/Login.tsx
  src/locale/en.json
  src/locale/id.json
Labels: Feature

#935 Handle friend block/request error
  src/components/FriendsMenu/FriendList.container.tsx
  src/components/FriendsMenu/FriendList.tsx
  src/components/FriendsMenu/FriendMenu.style.ts
  src/components/FriendsMenu/FriendMenu.tsx
  src/components/FriendsMenu/FriendRequest.tsx
  src/components/FriendsMenu/default.ts
  src/components/FriendsMenu/friend.style.tsx
  src/components/FriendsMenu/hooks/use-friend-list.hook.ts
  src/components/PostCreate/PostCreate.container.tsx
  src/components/Profile/ProfileHeader/ProfileHeaderContainer.tsx
  src/components/UserMenu/hooks/user-tabs.hooks.tsx
  src/components/atoms/CommentList/CommentList.container.tsx
  src/reducers/friend-request/actions.ts
  src/reducers/friend/actions.ts
Labels: bug

#936 Enabled send tip via tip history on comment
  src/components/PostDedicated/PostDedicated.container.tsx
  src/components/PostsList/PostsListContainer.tsx
  src/components/Profile/PostTabPanel/PostTabPanel.container.tsx
Labels: bug

#937 minor fixing
  src/components/ExperienceEditor/ExperienceEditor.tsx
  src/components/Timeline/TimelineContainer.tsx
Labels: Fix

#938 Hashtag can include non-ascii char
  src/components/PostEditor/plugins/hashtag/withHashtag.ts
Labels: bug, enhancement

#940 updated wording mobile view
  pages/mobile.tsx
  src/components/Login/render/Login/Login.tsx
  src/locale/en.json
  src/locale/id.json
Labels: Fix

#941 Added transaction details on success prompt
  src/components/FriendsMenu/FriendList.tsx
  src/components/PostDedicated/PostDedicated.container.tsx
  src/components/PostsList/PostsListContainer.tsx
  src/components/Profile/PostTabPanel/PostTabPanel.container.tsx
  src/components/Profile/ProfileHeader/ProfileHeaderContainer.tsx
  src/components/atoms/CommentList/CommentList.container.tsx
Labels: Improvement

#943 Reload friends on request accept
  src/components/Profile/ProfileHeader/ProfileHeaderContainer.tsx
  src/components/template/Default/DefaultLayout.tsx
  src/hooks/use-search.hooks.ts
  src/interfaces/notification.ts
  src/lib/api/experience.ts
  src/lib/api/friends.ts
  src/lib/api/post.ts
  src/lib/api/user.ts
  src/lib/firebase.ts
  src/reducers/experience/actions.ts
  src/reducers/friend/actions.ts
  src/reducers/notification/actions.ts
  src/reducers/search/actions.ts
  src/reducers/search/constants.ts
  src/reducers/search/reducer.ts
Labels: bug

#944 Reset search result on resubmit search
  src/components/Search/SearchResultContainer.tsx
  src/components/Timeline/hooks/use-timeline.hook.ts
  src/hooks/use-experience-hook.ts
  src/hooks/use-search.hooks.ts
  src/reducers/experience/actions.ts
  src/reducers/experience/constants.ts
  src/reducers/experience/reducer.ts
  src/reducers/search/actions.ts
  src/reducers/search/constants.ts
  src/reducers/search/reducer.ts
Labels: bug

#945 Add title meta tag
  package.json
  pages/experience/[experienceId]/clone.tsx
  pages/experience/[experienceId]/edit.tsx
  pages/experience/[experienceId]/preview.tsx
  pages/experience/create.tsx
  pages/friends.tsx
  pages/maintenance.tsx
  pages/mobile.tsx
  pages/nft.tsx
  pages/notification.tsx
  pages/privacy-policy.tsx
  pages/search.tsx
  pages/settings.tsx
  pages/socials.tsx
  pages/socialtoken.tsx
  pages/term-of-use.tsx
  pages/topic/[type].tsx
  pages/wallet.tsx
  src/components/Settings/Settings.tsx
  src/locale/en.json
  src/locale/id.json
Labels: Fix

#946 Log blocker
  pages/profile/[id].tsx
  src/components/Profile/ProfileComponent.tsx
  src/components/Profile/profile.style.ts
Labels: bug

#948 Add rawText on create post & fix overlapping text on comment editor
  src/components/PostEditor/Render/Hashtag/HashtagElement.styles.ts
  src/components/PostEditor/formatter.ts
  src/components/Profile/PostTabPanel/PostTabPanel.container.tsx
  src/components/Timeline/Timeline.tsx
  src/components/Timeline/TimelineContainer.tsx
  src/components/atoms/CommentEditor/CommentEditor.style.ts
  src/components/template/home/HomePage.tsx
  src/interfaces/post.ts
Labels: bug

#947 Implemented load more with loading state when searching for more users
  src/components/Search/SearchResultContainer.tsx
  src/components/UsersList/UsersList.tsx
  src/components/UsersList/UsersListContainer.tsx
  src/components/atoms/Loading/LoadingDots.tsx
  src/hooks/use-search.hooks.ts
  src/reducers/search/actions.ts
  src/reducers/search/constants.ts
  src/reducers/search/reducer.ts
Labels: Improvement

#949 display experience on anonymous acount
  pages/experience/[experienceId]/preview.tsx
  pages/friends.tsx
  pages/home.tsx
  pages/nft.tsx
  pages/post/[postId].tsx
  pages/profile/[id].tsx
  pages/search.tsx
  pages/settings.tsx
  pages/socials.tsx
  pages/socialtoken.tsx
  pages/topic/[type].tsx
  src/components/ExperiencePreview/ExperiencePreview.container.tsx
  src/components/ExperiencePreview/ExperiencePreview.tsx
  src/components/ExperienceTabMenu/ExperienceTabMenu.tsx
  src/components/ExperienceTabMenu/ExperienceTabMenuContainer.tsx
  src/components/Login/render/Login/Login.tsx
  src/components/atoms/SimpleCard/SimpleCard.tsx
  src/components/template/Login/Login.tsx
  src/lib/api/experience.ts
  src/locale/id.json
  src/reducers/experience/actions.ts
Labels: Fix, Feature

#950 Enabled sending tip with substrate-based tokens
  src/components/SendTip/SendTip.tsx
Labels: bug

#955 Fix handle visited and search banned user, handle button on own experience, and clean code
  pages/api/[...all].ts
  pages/profile/[id].tsx
  src/components/ExperiencePreview/ExperiencePreview.tsx
  src/components/Notifications/hooks/use-notification-list.hook.tsx
  src/components/Profile/ProfileComponent.tsx
  src/components/ResourceDeleted/ResourceDeleted.tsx
  src/interfaces/notification.ts
  src/lib/api/user.ts
Labels: bug, Fix

#957 Improved build id for multi-server
  .github/workflows/builder.yml
  .github/workflows/deployer.yml
  .maintain/docker/Dockerfile
  next.config.js
  package.json
Labels: Improvement

#956 Handled disabling tipping own comment via tip history
  src/components/FriendsMenu/FriendList.tsx
  src/components/TipHistory/TipHistory.container.tsx
  src/components/TipHistory/TipHistory.tsx
  src/hooks/tip-history.hook.ts
  src/reducers/tip-summary/actions.ts
  src/reducers/tip-summary/constants.ts
  src/reducers/tip-summary/reducer.ts
Labels: bug

#958 CI removed unused folder on docker build
  .maintain/docker/Dockerfile
Labels: CI

#954 limit website characters
  src/components/ProfileEdit/ProfileEdit.tsx
  src/components/ProfileHeader/render/Website/Website.tsx
  src/components/ProfileHeader/render/Website/Webstite.style.ts
Labels: Fix

#959 Remove duplicate
  pages/mobile.tsx
  src/components/CommentDetail/CommentDetail.tsx
  src/components/ExperienceEditor/Experience.container.tsx
  src/components/ExperiencePreview/ExperienceClone.container.tsx
  src/components/ExperiencePreview/ExperienceEdit.container.tsx
  src/components/FriendsMenu/FriendList.tsx
  src/components/Login/render/Login/Login.style.ts
  src/components/Login/render/Login/Login.tsx
  src/components/Login/render/Options/Options.style.ts
  src/components/Login/render/Options/Options.tsx
  src/components/PolkadotAccountList/PolkadotAccountList.styles.ts
  src/components/PolkadotAccountList/PolkadotAccountList.tsx
  src/components/PostEditor/formatter.ts
  src/components/Profile/tabs/ExperienceTab.tsx
  src/components/ProfileCard/ProfileCard.container.tsx
  src/components/Timeline/TimelineContainer.tsx
  src/components/TimelineFilter/TimelineFilter.tsx
  src/components/atoms/DropdownMenu/DropdownMenu.tsx
  src/components/atoms/FilterDropdownMenu/FilterDropdownMenu.tsx
  src/components/atoms/FilterDropdownMenu/filter-dropdown-menu.styles.ts
  src/components/atoms/FilterDropdownMenu/index.ts
  src/components/atoms/Icons/Core.tsx
  src/components/atoms/PostHeader/avatar/post-avatar.component.tsx
  src/components/atoms/PostHeader/avatar/post-avatar.style.ts
  src/components/common/MyriadIcon.tsx
  src/components/common/PolkadotLink.component.tsx
  src/hooks/use-importer-hook.ts
  src/images/Icons/myriad-circle.svg
  src/lib/api/experience.ts
  src/lib/api/post.ts
Labels: enhancement

#961 Add validation on send report and fix non clickable upload image button experience
  src/components/ExperienceEditor/ExperienceEditor.tsx
  src/components/Report/Report.tsx
Labels: bug, Fix

#953 fix search friend styling
  src/components/FriendsMenu/FriendList.tsx
  src/components/atoms/Search/SearchBox.interfaces.ts
  src/components/atoms/Search/SearchBox.tsx
  src/components/atoms/Search/SearchBoxContainer.tsx
  src/components/atoms/Search/search-box.styles.ts
Labels: Fix

#960 created login mobile view
  pages/index.tsx
  src/components/Mobile/OnBoardingView/CarouselLoginView.tsx
  src/components/Mobile/OnBoardingView/MobileLoginView.tsx
  src/components/Mobile/OnBoardingView/OnBoardingView.container.tsx
  src/images/illustration/amico.svg
  src/images/illustration/gdpr_-_amico.svg
  src/images/illustration/money_income_-_amico.svg
  src/locale/en.json
  src/locale/id.json
Labels: Feature

#964 handle validation on report account
  src/components/atoms/Report/Report.component.tsx
  src/components/atoms/Report/report.style.ts
Labels: bug, Fix

#963 created drawer component
  pages/home.tsx
  src/components/Menu/Menu.tsx
  src/components/Menu/use-menu-list.tsx
  src/components/Metric/Metric.style.ts
  src/components/Metric/Metric.tsx
  src/components/Metric/index.ts
  src/components/Mobile/MenuDrawer/MenuDrawer.tsx
  src/components/Mobile/MenuDrawer/menuDrawer.style.tsx
  src/components/Mobile/Navbar.tsx
  src/components/PostDetail/PostDetail.styles.ts
  src/components/ProfileCard/ProfileCard.interfaces.ts
  src/components/ProfileCard/ProfileCard.style.ts
  src/components/ProfileCard/ProfileCard.tsx
  src/components/ProfileCard/ProfileContent.tsx
  src/components/ProfileCard/index.ts
  src/components/ProfileHeader/index.tsx
  src/components/ProfileHeader/render/Metric/Metric.style.ts
  src/components/atoms/Icons/Core.tsx
  src/components/atoms/ListItem/index.tsx
  src/components/atoms/Search/search-box.styles.ts
  src/components/template/Default/DefaultLayout.styles.ts
  src/themes/light-theme.ts
Labels: Feature

#966 Add sort by most tipped
  pages/home.tsx
  src/components/PostsList/PostsList.tsx
  src/components/Profile/tabs/PostTabs.tsx
  src/components/Timeline/TimelineContainer.tsx
  src/components/Timeline/default.ts
  src/components/Timeline/helper.ts
  src/components/Timeline/hooks/use-timeline-filter.hook.ts
  src/components/Timeline/hooks/use-timeline.hook.ts
  src/components/TimelineFilter/TimelineFilter.container.tsx
  src/components/TimelineFilter/TimelineFilter.tsx
  src/components/TimelineFilter/hooks/use-filter-option.hook.ts
  src/hooks/use-timeline.hook.ts
  src/interfaces/timeline.ts
  src/lib/api/post.ts
  src/reducers/timeline/actions.ts
  src/reducers/timeline/reducer.ts
Labels: Feature

#968 MYR-1760: add new env
  .github/workflows/deployer.yml
Labels: CI

#962 Change post avatar image size
  .env-template
  next.config.js
  src/components/BalanceDetailList/BalanceDetailList.tsx
  src/components/BlockUserList/BlockList.tsx
  src/components/BlockUserList/blocklist.style.ts
  src/components/CommentDetail/CommentDetail.styles.ts
  src/components/CommentDetail/CommentDetail.tsx
  src/components/CommentEditor/CommentEditor.style.ts
  src/components/CommentEditor/CommentEditor.tsx
  src/components/FriendsMenu/FriendList.tsx
  src/components/FriendsMenu/FriendRequest.tsx
  src/components/FriendsMenu/friend.style.tsx
  src/components/HistoryDetailList/HistoryDetailList.tsx
  src/components/Notifications/Notifications.styles.ts
  src/components/Notifications/Notifications.tsx
  src/components/PostImporterList/PostImporter.styles.ts
  src/components/PostImporterList/PostImporter.tsx
  src/components/PrimaryCoinMenu/DraggableBalanceCard.tsx
  src/components/ProfileCard/ProfileCard.stories.tsx
  src/components/ProfileCard/ProfileContent.tsx
  src/components/SendTip/SendTip.tsx
  src/components/UsersList/UsersList.tsx
  src/components/UsersList/UsersListItem.tsx
  src/components/atoms/AddCoin/AddCoin.component.tsx
  src/components/atoms/AddCoin/AddCoin.style.ts
  src/components/atoms/Avatar/Avatar.interfaces.ts
  src/components/atoms/Avatar/Avatar.style.ts
  src/components/atoms/Avatar/Avatar.tsx
  src/components/atoms/Avatar/CustomAvatar.tsx
  src/components/atoms/Avatar/custom-avatar.interfaces.ts
  src/components/atoms/Avatar/index.ts
  src/components/atoms/CurrencyOption/currencyOption.style.ts
  src/components/atoms/CurrencyOption/index.tsx
  src/components/atoms/ListItem/ListItemSocial.tsx
  src/components/atoms/PostHeader/avatar/post-avatar.component.tsx
  src/components/common/Avatar.component.tsx
  src/helpers/image.ts
  src/interfaces/interaction.ts
  src/interfaces/post.ts
  src/lib/api/experience.ts
  src/lib/api/interaction.ts
  src/lib/api/interfaces/pagination-params.interface.ts
  src/lib/api/post.ts
  src/reducers/experience/actions.ts
  src/reducers/timeline/actions.ts
  src/reducers/timeline/constants.ts
  src/reducers/timeline/reducer.ts
  src/reducers/user/actions.ts
  src/stories/CustomAvatar.stories.tsx
Labels: enhancement

#969 improved navbar
  pages/friends.tsx
  pages/home.tsx
  pages/profile/[id].tsx
  src/components/Mobile/MenuDrawer/menuDrawer.style.ts
  src/components/Mobile/Navbar.tsx
  src/components/Mobile/Navbar/Navbar.tsx
  src/components/Mobile/Navbar/navbar.style.ts
  src/components/atoms/Search/SearchBox.interfaces.ts
  src/components/atoms/Search/SearchBox.tsx
  src/components/atoms/Search/SearchBoxContainer.tsx
  src/components/atoms/Search/search-box.styles.ts
  src/components/atoms/TopNavbar/TopNavbar.tsx
  src/components/atoms/TopNavbar/top-navbar.interfaces.ts
  src/components/atoms/TopNavbar/top-navbar.styles.ts
Labels: Improvement

#970 fix wording on notif list
  src/components/Notifications/hooks/use-notification-list.hook.tsx
  src/interfaces/notification.ts
Labels: Fix

#965 improve handle banned behavior
  src/components/CommentDetail/CommentDetail.tsx
  src/components/FriendsMenu/hooks/use-friend-list.hook.ts
  src/components/TipHistory/TipHistory.tsx
  src/interfaces/user.ts
  src/lib/api/experience.ts
Labels: Fix

#973 Fix experience interaction
  src/components/Expericence/Experience.tsx
  src/components/ExperienceList/ExperienceList.container.tsx
  src/components/Profile/tabs/ExperienceTab.tsx
  src/hooks/use-experience-hook.ts
  src/reducers/user/actions.ts
Labels: bug

#975 Change paragraph break word on post
  src/components/PostDetail/PostDetail.styles.ts
Labels: bug

#976 Handle if hashtag has no other words as siblings
  src/components/PostEditor/plugins/hashtag/withHashtag.ts
Labels: bug

#974 improved home page styling
  src/components/PostDetail/PostDetail.styles.ts
  src/components/PostDetail/PostDetail.tsx
  src/components/Richtext/RichTextContainer.tsx
  src/components/Richtext/index.tsx
  src/components/Richtext/richtext.style.ts
  src/components/Timeline/Timeline.styles.ts
  src/components/Timeline/TimelineContainer.tsx
  src/components/atoms/DropdownMenu/DropdownMenu.styles.ts
  src/components/atoms/DropdownMenu/DropdownMenu.tsx
  src/components/atoms/Icons/Core.tsx
  src/components/atoms/PostAction/index.tsx
  src/components/atoms/PostAction/postAction.style.ts
  src/components/atoms/PostHeader/index.tsx
  src/components/atoms/PostHeader/postHeader.style.ts
  src/components/atoms/TabList/TabList.styles.ts
  src/components/atoms/Voting/voting.style.ts
  src/images/Icons/Sort.svg
  src/themes/light-theme.ts
Labels: Improvement

#967 Added info tooltip related to existential deposit
  src/components/SendTip/SendTip.styles.ts
  src/components/SendTip/SendTip.tsx
  src/components/SendTip/ToolTip.tsx
  src/components/SendTip/index.ts
  src/components/atoms/Icons/Core.tsx
  src/images/Icons/InfoIcon.svg
Labels: Improvement

#977 improved wallet and friends ui
  pages/wallet.tsx
  src/components/BalanceDetailList/balance-detail-list.style.ts
  src/components/FriendsMenu/FriendMenu.style.ts
  src/components/FriendsMenu/FriendMenu.tsx
  src/components/FriendsMenu/friend.style.tsx
  src/components/MyWallet/MyWallet.tsx
  src/components/MyWallet/MyWalletContainer.tsx
  src/components/MyWallet/myWallet.style.ts
  src/components/atoms/Box/index.tsx
Labels: Improvement

#978 improved setting for mobile ui
  pages/nft.tsx
  pages/notification.tsx
  pages/post/[postId].tsx
  pages/search.tsx
  pages/settings.tsx
  pages/socials.tsx
  pages/socialtoken.tsx
  src/components/Mobile/MenuDrawer/MenuDrawer.tsx
  src/components/NFT/NFT.container.tsx
  src/components/NFT/nft.style.ts
  src/components/Settings/Settings.container.tsx
  src/components/Settings/Settings.styles.ts
  src/components/SocialToken/SocialToken.container.tsx
Labels: Improvement

#979 fix styling, search behavior and remove param on get post
  src/components/CommentDetail/CommentDetail.styles.ts
  src/components/Search/SearchResultContainer.tsx
  src/lib/api/post.ts
Labels: bug, Fix

#980 Change mention to all public user
  src/components/PostCreate/PostCreate.container.tsx
  src/components/PostCreate/PostCreate.stories.tsx
  src/components/PostCreate/PostCreate.tsx
Labels: bug

#982 Fixed 422 API error when tipping directly to user
  src/hooks/use-polkadot-api.hook.ts
Labels: bug, Fix

#983 improved search, socmed mobile ui
  pages/socials.tsx
  src/components/Mobile/Navbar/Navbar.tsx
  src/components/PostsList/PostsList.styles.ts
  src/components/PostsList/PostsList.tsx
  src/components/Search/SearchResultContainer.tsx
  src/components/Socials/Socials.styles.ts
  src/components/Socials/Socials.tsx
Labels: Improvement

#986 Fix empty styling & update post api adapter
  pages/search.tsx
  src/components/ExperienceEditor/ExperienceEditor.tsx
  src/components/ExperienceList/ExperienceList.empty.tsx
  src/components/ExperienceList/SearchExperienceList.container.tsx
  src/components/Profile/EmptyProfilePost.tsx
  src/components/Profile/tabs/ExperienceTab.tsx
  src/components/Profile/tabs/PostTabs.tsx
  src/components/ProfileCard/ProfileCard.style.ts
  src/components/ProfileCard/ProfileCard.tsx
  src/components/Trending/TrendingList.styles.ts
  src/components/UserSocials/UserSocials.tsx
  src/components/UsersList/UsersList.tsx
  src/components/atoms/Empty/Empty.styles.ts
  src/components/template/Default/DefaultLayout.tsx
  src/lib/api/post.ts
Labels: bug

#987 improved experience preview for mobile view
  pages/experience/[experienceId]/preview.tsx
  src/components/ExperiencePreview/ExperienceClone.container.tsx
  src/components/ExperiencePreview/ExperienceEdit.container.tsx
  src/components/ExperiencePreview/ExperiencePreview.container.tsx
  src/components/ExperiencePreview/ExperiencePreview.tsx
  src/components/ExperiencePreview/experience.style.ts
Labels: Improvement

#990 Fix handle empty search
  src/components/FriendsMenu/FriendList.container.tsx
  src/components/FriendsMenu/FriendList.tsx
  src/components/atoms/Video/Video.tsx
  src/lib/api/friends.ts
  src/reducers/friend/actions.ts
Labels: bug

#989 created prompt component for mobile view
  src/components/AddSocialMedia/AddSocialMedia.tsx
  src/components/ExperiencePreview/ExperienceSignIn.tsx
  src/components/Mobile/PromptDrawer/Prompt.tsx
  src/components/Mobile/PromptDrawer/prompt.style.ts
  src/components/PostDetail/PostDetail.tsx
  src/components/Richtext/RichTextContainer.tsx
  src/components/Socials/Socials.container.tsx
  src/components/Socials/Socials.tsx
  src/components/atoms/Prompt/prompt.style.ts
  src/components/atoms/Voting/index.tsx
Labels: Improvement

#992 Fix storage bucket url
  .env-template
  next.config.js
  src/helpers/image.ts
  src/lib/api/friends.ts
Labels: enhancement

#991 Disable tipping for all tokens (excluding MYRIA) on unclaimed imported posts
  src/components/CommentDetail/CommentDetail.tsx
  src/components/PostDetail/PostDetail.container.tsx
  src/components/PostDetail/PostDetail.tsx
  src/components/PostsList/PostsListContainer.tsx
  src/components/SendTip/SendTip.tsx
  src/components/Timeline/TimelineContainer.tsx
  src/components/atoms/CurrencyOption/index.tsx
  src/reducers/timeline/actions.ts
  src/reducers/timeline/reducer.ts
Labels: Fix

#993 Fix sort search post
  src/components/MyWallet/MyWallet.tsx
  src/components/PostsList/PostsList.tsx
  src/components/PostsList/PostsListContainer.tsx
  src/components/Timeline/TimelineContainer.tsx
  src/components/Timeline/hooks/use-timeline.hook.ts
  src/components/atoms/AddCoin/AddCoin.component.tsx
  src/components/atoms/CurrencyOption/index.tsx
  src/lib/api/post.ts
  src/reducers/timeline/actions.ts
  src/reducers/timeline/constants.ts
  src/reducers/timeline/reducer.ts
Labels: bug, enhancement

#995 fix styling on mobile
  src/components/Expericence/Experience.tsx
  src/components/ExperienceList/ExperienceList.container.tsx
  src/components/ExperienceList/ExperienceList.tsx
  src/components/Metric/Metric.tsx
  src/components/Mobile/MenuDrawer/MenuDrawer.tsx
  src/components/Mobile/MenuDrawer/menuDrawer.style.ts
  src/components/Mobile/OnBoardingView/MobileLoginView.tsx
  src/components/Report/Report.tsx
  src/components/atoms/Report/Report.component.tsx
Labels: Fix

#996 Filter duplicate friends
  src/components/FriendsMenu/FriendList.container.tsx
  src/hooks/use-friends-hook.ts
  src/hooks/use-profile-friend.hook.ts
Labels: bug

#997 Prevent reload page on create post
  package.json
  src/components/Richtext/RichTextContainer.tsx
  src/components/Timeline/TimelineContainer.tsx
Labels: Fix

#998 Fix search tab styling
  src/components/ExperienceList/SearchExperienceList.container.tsx
  src/components/PostsList/PostsList.styles.ts
  src/components/PostsList/PostsList.tsx
  src/components/RightMenuBar/RightMenuBar.tsx
  src/components/Search/SearchResultContainer.tsx
  src/components/Timeline/Timeline.styles.ts
  src/components/Timeline/TimelineContainer.tsx
  src/components/UserMenu/UserMenu.container.tsx
  src/components/UserMenu/UserMenu.tsx
  src/components/UserMenu/hooks/user-tabs.hooks.tsx
  src/components/UsersList/UsersList.tsx
  src/components/atoms/TabList/TabList.styles.ts
  src/components/atoms/TabList/TabList.tsx
  src/components/atoms/TabList/TabList.types.ts
  src/components/atoms/TabPanel/TabPanel.tsx
  src/components/atoms/Tabs/Tabs.tsx
  src/components/atoms/Tabs/Tabs.types.ts
  src/components/atoms/Video/Video.tsx
Labels: bug
