Repository myriadsocial/myriad-web, pull requests merged in 2022-09, with the labels that each got.

#1457 fix: handled missing userExperienceList when first load
  src/components/Expericence/ModalAddToPost/ModalAddToPost.provider.tsx
  src/interfaces/experience.ts
Labels: Fix

#1459 fix: improvement new tipping flow
  src/components/Tip/Tip.container.tsx
  src/components/common/Blockchain/Blockchain.provider.tsx
  src/components/template/Default/DefaultLayout.tsx
  src/helpers/wallet.ts
  src/hooks/use-claim-tip.hook.ts
  src/lib/api/server.ts
Labels: Improvement

#1460 fix: showed claimTip balance
  src/hooks/use-claim-tip.hook.ts
  src/hooks/use-polkadot-api.hook.ts
  src/lib/services/polkadot-js.ts
Labels: Improvement

#1461 fix: filtered to only show not subscribed userExperiences
  src/components/Expericence/ModalAddToPost/ModalAddToPost.provider.tsx
  src/components/ExperienceList/ExperienceList.tsx
Labels: Fix

#1463 Handled show list
  src/components/Expericence/ModalAddToPost/ModalAddToPost.provider.tsx
  src/components/Expericence/ModalAddToPost/ModalAddToPost.styles.tsx
  src/components/ExperienceList/ExperienceList.tsx
Labels: Fix

#1462 fix: improve get post query
  src/components/PostList/hooks/use-timeline-filter.hook.ts
  src/hooks/auth.hook.ts
  src/lib/api/post.ts
  src/lib/api/user.ts
  src/reducers/timeline/actions.ts
Labels: Improvement

#1465 fix: improve GET /comments query
  src/lib/api/comment.ts
Labels: Improvement

#1467 ci: added rpcURL
  .github/workflows/deployer.yml
  .github/workflows/release.yml
Labels: CI

#1468 fix: private account when anonymous
  pages/profile/[id].tsx
  src/lib/api/comment.ts
Labels: Improvement

#1471 fix: nested debates not shown
  src/components/CommentDetail/CommentDetail.tsx
  src/components/CommentList/CommentList.container.tsx
  src/components/CommentList/CommentList.tsx
  src/hooks/use-comment.hook.ts
  src/hooks/use-replies.hook.ts
Labels: Improvement

#1472 feat: remapped transaction data structure
  src/components/HistoryDetailList/HistoryDetailList.tsx
  src/components/TipHistory/TipHistory.tsx
  src/interfaces/transaction.ts
  src/lib/api/transaction.ts
Labels: Improvement

#1473 feat: implement disconnect wallet
  adapters/api.ts
  pages/experience/[experienceId]/clone.tsx
  pages/experience/[experienceId]/edit.tsx
  pages/experience/[experienceId]/index.tsx
  pages/experience/create.tsx
  pages/experience/index.tsx
  pages/experience/trending.tsx
  pages/friends.tsx
  pages/home.tsx
  pages/nft.tsx
  pages/notification.tsx
  pages/post/[postId].tsx
  pages/profile/[id].tsx
  pages/search.tsx
  pages/settings.tsx
  pages/socials.tsx
  pages/socialtoken.tsx
  pages/topic/[type].tsx
  pages/topic/index.tsx
  pages/town.tsx
  pages/wallet.tsx
  src/components/Manage/Manage.container.tsx
  src/components/Manage/Manage.tsx
  src/components/Manage/manage.style.ts
  src/hooks/use-connect.hook.ts
  src/lib/api/wallet.ts
  src/locale/en.json
  src/locale/id.json
  src/locale/ru.json
  src/reducers/user/actions.ts
Labels: Improvement
