Repository myriadsocial/myriad-web, pull requests merged in 2022-08, with the labels that each got.

#1423 Changing logo to dynamic url
  next.config.js
  pages/experience/[experienceId]/clone.tsx
  pages/experience/[experienceId]/edit.tsx
  pages/experience/[experienceId]/index.tsx
  pages/experience/create.tsx
  pages/experience/index.tsx
  pages/experience/trending.tsx
  pages/friends.tsx
  pages/home.tsx
  pages/nft.tsx
  pages/notification.tsx
  pages/post/[postId].tsx
  pages/profile/[id].tsx
  pages/search.tsx
  pages/settings.tsx
  pages/socials.tsx
  pages/socialtoken.tsx
  pages/topic/[type].tsx
  pages/topic/index.tsx
  pages/town.tsx
  pages/wallet.tsx
  src/components/Menu/Menu.container.tsx
  src/components/Menu/Menu.tsx
  src/components/Tip/Tip.container.tsx
  src/components/template/Default/DefaultLayout.tsx
  src/hooks/use-claim-tip.hook.ts
  src/lib/api/server.ts
  src/lib/api/wallet.ts
Labels: enhancement, Feature

#1418 Update push notification handler
  public/firebase-messaging-sw.js
  public/images/logo.jpg
  src/components/template/Default/DefaultLayout.tsx
  src/hooks/auth.hook.ts
  src/hooks/use-user.hook.ts
  src/lib/firebase.ts
  src/lib/firebase/analytic.ts
  src/lib/firebase/app.ts
  src/lib/firebase/messaging.ts
Labels: bug

#1424 Update post style
  src/components/PostDetail/PostDetail.styles.ts
  src/components/PostDetail/PostDetail.tsx
  src/components/PostDetail/render/Header/Header.style.ts
  src/components/PostDetail/render/Header/Header.tsx
  src/components/PostDetail/render/Reddit.tsx
  src/components/PostDetail/render/Twitter.tsx
  src/components/atoms/Badge/Badge.tsx
  src/components/atoms/Gallery/Gallery.styles.ts
  src/components/atoms/Gallery/Gallery.tsx
  src/components/atoms/LinkPreview/LinkPreview.styles.ts
  src/components/atoms/NSFW/nsfw.style.ts
  src/components/atoms/SocialAvatar/SocialAvatar.interface.ts
  src/components/atoms/SocialAvatar/SocialAvatar.tsx
  src/components/atoms/Video/Video.tsx
  src/components/common/Editor/render/Element/Hashtag/HashtagElement.tsx
  src/components/common/NodeViewer/NodeViewer.style.ts
  src/themes/light-theme.ts
Labels: bug, enhancement

#1422 fix: improve blockchain connection
  package.json
  pages/wallet.tsx
  src/components/BalanceDetailList/BalanceDetailList.tsx
  src/components/HistoryDetailList/HistoryDetailList.tsx
  src/components/Login/render/Profile/Profile.tsx
  src/components/Manage/Manage.container.tsx
  src/components/Mobile/MenuDrawer/MenuDrawer.tsx
  src/components/MyWallet/MyWalletContainer.tsx
  src/components/PolkadotAccountList/PolkadotAccountList.tsx
  src/components/PrimaryCoinMenu/DraggableBalanceCard.tsx
  src/components/ProfileCard/NetworkOption/NetworkOption.tsx
  src/components/ProfileCard/ProfileCard.container.tsx
  src/components/ProfileCard/ProfileCard.tsx
  src/components/ProfileCard/ProfileContent.tsx
  src/components/Tip/Tip.claim.reference.tsx
  src/components/Tip/Tip.container.tsx
  src/components/Tip/Tip.tsx
  src/components/TotalTips/TipTotal.tsx
  src/components/WalletBalance/WalletBalanceContainer.tsx
  src/components/WalletBalance/index.tsx
  src/components/common/Blockchain/Blockchain.context.ts
  src/components/common/Blockchain/Blockchain.provider.tsx
  src/components/common/Blockchain/use-blockchain.hook.ts
  src/components/common/Tipping/Tipping.interface.ts
  src/components/common/Tipping/Tipping.provider.tsx
  src/components/common/Tipping/Tipping.tsx
  src/components/common/Tipping/render/InputAmount/InputAmount.tsx
  src/components/template/Default/DefaultLayout.tsx
  src/helpers/wallet.ts
  src/hooks/auth.hook.ts
  src/hooks/use-claim-tip.hook.ts
  src/hooks/use-connect.hook.ts
  src/hooks/use-near-api.hook.ts
  src/hooks/use-polkadot-api.hook.ts
  src/hooks/use-wallet-hook.ts
  src/interfaces/blockchain-interface.ts
  src/interfaces/network.ts
  src/interfaces/user.ts
  src/lib/api/wallet.ts
  src/lib/services/blockchain-provider.ts
  src/lib/services/near-api-js.ts
  src/lib/services/polkadot-js.ts
  src/reducers/balance/actions.ts
  src/reducers/user/actions.ts
Labels: bug, Improvement

#1425 fix: loader skeleton component, experience card styles
  src/components/Expericence/Experience.skeleton.tsx
  src/components/ExperienceList/ExperienceList.empty.tsx
  src/components/RightMenuBar/tabs/ExperienceTab.tsx
  src/components/RightMenuBar/tabs/Tab.style.ts
Labels: bug

#1427 Update gallery style
  src/components/atoms/Gallery/Gallery.styles.ts
  src/components/atoms/Gallery/Gallery.tsx
Labels: bug

#1429 fix: claim reference for near
  src/components/Menu/Menu.tsx
  src/hooks/use-claim-tip.hook.ts
Labels: Improvement

#1430 Fix logout anonym
  src/components/atoms/Gallery/Gallery.tsx
  src/hooks/auth.hook.ts
Labels: bug

#1431 Handle notification not granted
  src/components/template/Default/DefaultLayout.tsx
  src/lib/firebase/messaging.ts
Labels: bug

#1432 change myriad logo testnet on mobile
  pages/home.tsx
  pages/search.tsx
  src/components/Mobile/Navbar/Navbar.tsx
  src/components/Search/SearchResultContainer.tsx
Labels: Improvement

#1428 feat: added cancel add friend
  src/components/ProfileHeader/ProfileHeaderContainer.tsx
  src/components/ProfileHeader/index.tsx
  src/hooks/use-friend-request.hook.ts
Labels: Improvement

#1426 feat: added view button in trending experience
  src/components/CommentList/CommentList.tsx
  src/components/ExperienceList/ExperienceList.container.tsx
  src/components/ExperienceList/SearchExperienceList.container.tsx
  src/components/RightMenuBar/tabs/Tab.style.ts
  src/components/RightMenuBar/tabs/TrendingExperienceTab.tsx
  src/components/Search/SearchResultContainer.tsx
  src/components/atoms/LoadMore/LoadMore.tsx
  src/lib/api/experience.ts
  src/locale/en.json
  src/locale/id.json
  src/locale/ru.json
  src/reducers/experience/actions.ts
  src/reducers/experience/reducer.ts
Labels: bug, Improvement

#1433 fix: handle connect near account
  src/components/Manage/Manage.container.tsx
  src/components/Menu/Menu.tsx
  src/components/common/Blockchain/Blockchain.provider.tsx
  src/components/template/Default/DefaultLayout.tsx
  src/hooks/use-claim-tip.hook.ts
  src/hooks/use-connect.hook.ts
  src/hooks/use-polkadot-api.hook.ts
  src/hooks/use-wallet-hook.ts
Labels: Improvement

#1435 fix: unclickable menu
  src/components/Menu/Menu.tsx
Labels: Improvement

#1434 Setup testing on component
  __tests__/banner-demo.test.tsx
  jest.config.js
  package.json
  src/components/Menu/Menu.container.test.tsx
  src/components/Menu/Menu.container.tsx
  src/components/Menu/Menu.test.tsx
  src/components/Menu/Menu.tsx
  src/components/atoms/ListItem/index.tsx
  test/setupTest.ts
  yarn.lock
Labels: Improvement

#1437 fix: styling claim tip
  src/components/Tip/Shimer.tsx
  src/components/Tip/Tip.tsx
  src/components/Tip/tip.style.ts
Labels: Fix

#1436 feat: added translation in some component
  src/components/ProfileHeader/index.tsx
  src/components/Tip/Tip.claim.reference.tsx
  src/components/TotalTips/TipTotal.tsx
  src/locale/en.json
  src/locale/id.json
  src/locale/ru.json
Labels: Improvement

#1438 Prevent auto reload mismatch calculation when new post added
  src/reducers/timeline/reducer.ts
Labels: bug

#1439 fix: handle near tipping to hex account
  src/lib/services/near-api-js.ts
Labels: Improvement

#1440 implement unit test on social media list
  src/components/Menu/Menu.test.tsx
  src/components/Menu/Menu.tsx
  src/components/SocialMediaList/SocialMediaList.container.test.tsx
  src/components/SocialMediaList/SocialMediaList.container.tsx
  test/setupTest.ts
Labels: Improvement

#1442 fix: near balance of hex account
  src/lib/services/near-api-js.ts
Labels: Improvement

#1443 fix: removed unused word
  src/components/Tip/Tip.claim.reference.tsx
Labels: bug, Fix

#1441 disable near feature
  package.json
  src/components/Login/Login.tsx
  src/components/Login/render/Options/Options.tsx
  src/components/Manage/Manage.container.tsx
  src/components/Manage/Manage.tsx
  src/components/ProfileCard/ProfileCard.tsx
  src/components/common/Blockchain/Blockchain.provider.tsx
Labels: bug

#1445 fix: security breach near auth
  src/components/Login/Login.tsx
  src/components/Login/render/Options/Options.tsx
  src/components/Manage/Manage.container.tsx
  src/components/Manage/Manage.tsx
  src/components/ProfileCard/ProfileCard.tsx
  src/components/common/Blockchain/Blockchain.context.ts
  src/components/common/Blockchain/Blockchain.provider.tsx
  src/components/template/Default/DefaultLayout.tsx
  src/hooks/auth.hook.ts
  src/hooks/use-near-api.hook.ts
  src/lib/services/near-api-js.ts
Labels: Improvement

#1446 fix: logut as anonymous user
  src/hooks/auth.hook.ts
Labels: Improvement

#1448 fix: handle force logout near
  package.json
  pages/api/auth/[...nextauth].ts
  src/components/Login/Login.tsx
  src/hooks/auth.hook.ts
Labels: bug, Improvement

#1447 feat: added loadmore in importers post
  src/components/PostImporterList/PostImporter.styles.ts
  src/components/PostImporterList/PostImporter.tsx
  src/lib/api/importers.ts
  src/locale/ru.json
Labels: Fix, Improvement

#1449 feat: added mynearwallet auth
  src/components/Login/Login.tsx
  src/components/Login/render/Options/Options.tsx
  src/components/Login/render/Profile/Profile.tsx
  src/components/Manage/Manage.container.tsx
  src/components/NearSelector/NearSelectorList.styles.ts
  src/components/NearSelector/NearSelectorList.tsx
  src/components/NearSelector/index.ts
  src/components/atoms/Icons/Wallet.tsx
  src/components/common/Blockchain/Blockchain.provider.tsx
  src/components/template/Default/DefaultLayout.tsx
  src/hooks/auth.hook.ts
  src/hooks/use-near-api.hook.ts
  src/images/wallet/my-near-wallet.svg
  src/interfaces/blockchain-interface.ts
  src/interfaces/network.ts
  src/interfaces/wallet.ts
  src/lib/services/blockchain-provider.ts
  src/lib/services/near-api-js.ts
Labels: Feature, Improvement

#1450 feat: added information of the selected experience on the timeline
  src/components/Timeline/Render/ExperienceCard.tsx
  src/components/Timeline/Render/experience-card.style.ts
  src/components/Timeline/Timeline.layout.tsx
Labels: Feature

#1451 fix: added mynearwallet for mobile
  src/components/Login/render/Options/Options.tsx
Labels: Improvement

#1452 fix: added log for near auth
  src/components/Login/Login.tsx
  src/components/Login/render/Options/Options.tsx
  src/components/Manage/Manage.container.tsx
  src/components/common/Blockchain/Blockchain.provider.tsx
  src/hooks/auth.hook.ts
  src/hooks/use-near-api.hook.ts
  src/lib/services/near-api-js.ts
Labels: Improvement

#1453 chore: bump version to 2.1.17
  package.json
Labels: Feature

#1454 change wording and update style banner
  src/components/common/Banner/AppStatus.tsx
  src/locale/en.json
  src/locale/id.json
  src/locale/ru.json
Labels: Fix

#1455 fix: handle tipping with 2FA
  src/lib/services/near-api-js.ts
Labels: Improvement

#1456 chore: bump version to 2.1.18
  package.json
Labels: Improvement
