Repository myriadsocial/myriad-web, pull requests merged in 2022-03, with the labels that each got.

#999 minor fixing mobile view
  src/components/CommentDetail/CommentDetail.styles.ts
  src/components/CommentDetail/CommentDetail.tsx
  src/components/Menu/use-menu-list.tsx
  src/components/Mobile/MenuDrawer/MenuDrawer.tsx
  src/components/Socials/Socials.tsx
Labels: Fix

#1000 fix minor on mobile
  pages/experience/index.tsx
  pages/topic/[type].tsx
  src/components/Mobile/OnBoardingView/CarouselLoginView.tsx
Labels: Fix

#1001 disable clone and subscribe experience for private account
  src/components/Expericence/Experience.tsx
  src/components/ExperiencePreview/ExperienceClone.container.tsx
  src/components/ExperiencePreview/ExperienceEdit.container.tsx
  src/components/ExperiencePreview/ExperiencePreview.container.tsx
  src/components/ExperiencePreview/ExperiencePreview.tsx
  src/interfaces/experience.ts
  src/lib/api/experience.ts
  src/reducers/experience/actions.ts
  src/reducers/experience/reducer.ts
Labels: Fix

#1002 MYR-000: fixed experience post
  src/components/Expericence/Experience.tsx
Labels: bug

#1004 improved settings mobile ui
  src/components/Settings/Settings.styles.ts
  src/components/Settings/Settings.tsx
  src/components/Settings/hooks/use-setting-list.hook.tsx
  src/components/atoms/PostAction/postAction.style.ts
Labels: Improvement

#1005 fixed can't load post experience
  src/components/Expericence/Experience.tsx
  src/components/ExperiencePreview/ExperienceClone.container.tsx
  src/components/ExperiencePreview/ExperienceEdit.container.tsx
  src/components/ExperiencePreview/ExperiencePreview.container.tsx
  src/components/ExperiencePreview/ExperiencePreview.tsx
  src/interfaces/experience.ts
  src/lib/api/experience.ts
  src/reducers/experience/actions.ts
  src/reducers/experience/reducer.ts
Labels: Fix

#1006 fix filter timeline by experience
  pages/topic/[type].tsx
  src/components/ExperienceList/ExperienceList.container.tsx
  src/components/ExperienceList/ExperienceList.tsx
  src/components/Timeline/hooks/use-timeline-filter.hook.ts
  src/lib/api/experience.ts
  src/reducers/experience/actions.ts
  src/reducers/profile/actions.ts
  src/reducers/user/actions.ts
Labels: bug

#1008 Fix comment tab
  src/components/atoms/Tabs/Tabs.tsx
Labels: bug

#1009 Fix selected experience
  src/components/ExperienceList/ExperienceList.tsx
  src/components/TimelineFilter/TimelineFilter.container.tsx
  src/hooks/use-query-params.hooks.ts
Labels: bug

#1012 fix experience title format & public key background
  src/components/Expericence/Experience.style.ts
  src/components/UserSettings/UserSettings.styles.ts
Labels: bug

#1014 Fix login label placement & chip label style
  src/components/Login/render/Profile/Profile.tsx
  src/themes/light-theme.ts
Labels: bug

#1015 bug fixed styling
  src/components/Login/render/Options/Options.tsx
  src/components/Mobile/OnBoardingView/CarouselLoginView.tsx
  src/components/ProfileHeader/profile-header.style.ts
Labels: bug, Fix

#1013 Change comment list default sort
  src/components/UserSettings/UserSettings.styles.ts
  src/hooks/use-comment.hook.ts
  src/hooks/use-replies.hook.ts
  src/lib/api/comment.ts
Labels: enhancement, Fix

#1016 Optimize page first load
  .storybook/preview.js
  @types/index.d.ts
  next.config.js
  package.json
  pages/profile/[id].tsx
  src/components/CommentList/CommentList.container.tsx
  src/components/ExperienceEditor/Experience.container.tsx
  src/components/ExperiencePreview/ExperienceClone.container.tsx
  src/components/ExperiencePreview/ExperienceEdit.container.tsx
  src/components/ExperiencePreview/ExperiencePreview.container.tsx
  src/components/FriendsMenu/FriendList.container.tsx
  src/components/FriendsMenu/FriendList.tsx
  src/components/FriendsMenu/FriendMenu.tsx
  src/components/FriendsMenu/FriendRequest.container.tsx
  src/components/PostCreate/PostCreate.container.tsx
  src/components/PostDetail/PostDetail.container.tsx
  src/components/PostDetail/PostDetail.tsx
  src/components/PostDetail/hooks/use-comment-tabs.tsx
  src/components/PostDetail/hooks/use-post-delete.hook.ts
  src/components/PostDetail/hooks/use-post-interaction.hook.ts
  src/components/PostDetail/render/Reddit.tsx
  src/components/PostDetail/render/Twitter.tsx
  src/components/PostImport/PostImport.tsx
  src/components/PostVisibility/PostVisibility.container.tsx
  src/components/PostsList/PostsListContainer.tsx
  src/components/Profile/Profile.tsx
  src/components/ProfileEdit/ProfileEditContainer.tsx
  src/components/ProfileHeader/ProfileHeaderContainer.tsx
  src/components/Richtext/RichTextContainer.tsx
  src/components/SendTip/SendTipContainer.tsx
  src/components/Timeline/TimelineContainer.tsx
  src/components/atoms/Embed/Embed.stories.tsx
  src/components/atoms/Embed/Embed.tsx
  src/components/atoms/Gallery/Gallery.styles.ts
  src/components/atoms/Gallery/Gallery.tsx
  src/components/atoms/Gallery/Image.skeleton.tsx
  src/components/atoms/Tabs/Tabs.types.ts
  src/components/atoms/TopNavbar/TopNavbar.interfaces.ts
  src/components/atoms/TopNavbar/TopNavbar.styles.ts
  src/components/atoms/TopNavbar/TopNavbar.tsx
  src/components/atoms/TopNavbar/index.ts
  src/reducers/exchange-rate/actions.ts
  yarn.lock
Labels: enhancement

#1018 Fix dependency priority
  package.json
Labels: Fix, CI

#1017 Add delete comment
  src/components/CommentDetail/CommentDetail.interface.ts
  src/components/CommentDetail/CommentDetail.tsx
  src/components/CommentList/CommentList.container.tsx
  src/components/CommentList/CommentList.tsx
  src/hooks/use-comment.hook.ts
  src/hooks/use-replies.hook.ts
  src/lib/api/comment.ts
  src/reducers/timeline/reducer.ts
Labels: Feature

#1021 improved profile card UI
  src/components/ExperienceEditor/ExperienceEditor.tsx
  src/components/ProfileCard/ProfileCard.style.ts
  src/components/ProfileCard/ProfileCard.tsx
  src/components/ProfileCard/ProfileContent.tsx
  src/components/ProfileCard/profileContent.style.ts
  src/components/atoms/Icons/Network.tsx
  src/images/network/Near24.svg
  src/images/network/Polkadot24.svg
Labels: Fix, Feature, Improvement

#1022 improved wallet UI
  src/components/BalanceDetailList/BalanceDetailList.tsx
  src/components/BalanceDetailList/BalanceDetailListContainer.tsx
  src/components/BalanceDetailList/balance-detail-list.style.ts
  src/components/HistoryDetailList/HistoryDetailList.tsx
  src/components/HistoryDetailList/HistoryDetailListContainer.tsx
  src/components/HistoryDetailList/history-detail-list.styles.ts
  src/components/Manage/Manage.container.tsx
  src/components/Manage/Manage.tsx
  src/components/Manage/manage.style.ts
  src/components/MyWallet/MyWallet.tsx
  src/components/Tip/Tip.container.tsx
  src/components/Tip/Tip.tsx
  src/components/Tip/tip.style.ts
  src/components/atoms/Icons/Network.tsx
  src/themes/light-theme.ts
Labels: Feature, Improvement

#1023 Create comment history page
  src/components/CommentEditor/CommentEditor.tsx
  src/components/CommentHistory/CommentHistory.style.ts
  src/components/CommentHistory/CommentHistory.tsx
  src/components/CommentHistory/index.ts
  src/components/CommentHistoryList/CommentHistoryList.container.tsx
  src/components/CommentHistoryList/CommentHistoryList.style.ts
  src/components/CommentHistoryList/CommentHistoryList.tsx
  src/components/CommentHistoryList/hooks/use-comment-history.hook.ts
  src/components/CommentHistoryList/index.ts
  src/components/FriendsMenu/FriendList.container.tsx
  src/components/FriendsMenu/FriendList.tsx
  src/components/FriendsMenu/default.ts
  src/components/Timeline/hooks/use-timeline-filter.hook.ts
  src/components/TimelineFilter/TimelineFilter.container.tsx
  src/components/TimelineFilter/TimelineFilter.tsx
  src/components/TimelineFilter/hooks/use-filter-option.hook.ts
  src/components/UserMenu/hooks/user-tabs.hooks.tsx
  src/components/atoms/PostHeader/subHeader/post-sub-header.component.tsx
  src/components/common/TimeAgo.component.tsx
  src/hooks/use-friends-hook.ts
  src/hooks/use-profile-friend.hook.ts
  src/interfaces/comment.ts
  src/interfaces/timeline.ts
  src/lib/api/comment.ts
  src/lib/api/interfaces/pagination-params.interface.ts
  src/lib/api/post.ts
  src/reducers/comment/actions.ts
  src/reducers/comment/constants.ts
  src/reducers/comment/reducer.ts
  src/reducers/index.ts
  src/reducers/timeline/actions.ts
  src/reducers/timeline/reducer.ts
Labels: Feature

#1025 Create confirm provider & hook
  src/components/BlockUserList/BlockList.style.ts
  src/components/BlockUserList/BlockList.tsx
  src/components/atoms/Prompt/prompt.component.tsx
  src/components/common/Confirm/Confirm.context.ts
  src/components/common/Confirm/Confirm.interface.ts
  src/components/common/Confirm/Confirm.provider.tsx
  src/components/common/Confirm/use-confirm.hook.ts
  src/components/template/Default/DefaultLayout.tsx
Labels: enhancement, Feature

#1027 Log custom error from axios
  src/lib/api/base.ts
Labels: bug

#1031 Fix back button on navbar
  src/components/Settings/hooks/use-setting-list.hook.tsx
  src/components/atoms/TopNavbar/TopNavbar.tsx
Labels: bug

#1032 fix behavior banned
  pages/experience/[experienceId]/preview.tsx
  src/components/ExperiencePreview/ExperiencePreview.tsx
  src/components/PostDetail/hooks/use-comment-tabs.tsx
  src/components/PostImporterList/PostImporter.tsx
  src/components/TipHistory/TipHistory.tsx
  src/components/atoms/Avatar/Avatar.style.ts
  src/components/atoms/ListItem/index.tsx
  src/hooks/use-comment.hook.ts
  src/hooks/use-experience-hook.ts
  src/interfaces/people.ts
Labels: Fix

#1033 wiring balance tab multiwallet
  src/components/BalanceDetailList/BalanceDetailList.tsx
  src/components/BalanceDetailList/Shimer.tsx
  src/components/BalanceDetailList/index.ts
Labels: Feature

#1034 Scroll to post on comment
  src/components/CommentDetail/CommentDetail.interface.ts
  src/components/CommentDetail/CommentDetail.tsx
  src/components/CommentDetail/index.ts
  src/components/CommentList/CommentList.container.tsx
  src/components/CommentList/CommentList.style.ts
  src/components/CommentList/CommentList.tsx
  src/components/PostDetail/PostDetail.tsx
  src/components/PostDetail/hooks/use-comment-tabs.tsx
Labels: bug, enhancement

#1035 Replace prompt component with confirm hook
  pages/_app.tsx
  pages/api/captcha.ts
  pages/maintenance.tsx
  src/components/CommentDeleted/CommentDeleted.tsx
  src/components/CommentDetail/CommentDetail.styles.ts
  src/components/CommentDetail/CommentDetail.tsx
  src/components/CommentList/CommentList.container.tsx
  src/components/Expericence/Experience.tsx
  src/components/ExperiencePreview/ExperiencePreview.tsx
  src/components/FriendsMenu/FriendList.tsx
  src/components/Login/render/Profile/Profile.tsx
  src/components/PostDetail/PostDetail.container.tsx
  src/components/PostVisibility/PostVisibility.container.tsx
  src/components/ProfileEdit/ProfileEdit.tsx
  src/components/ProfileEdit/ProfileEditContainer.tsx
  src/components/ProfileHeader/index.tsx
  src/components/Settings/LanguageSettingsContainer.tsx
  src/components/Socials/Socials.tsx
  src/components/Timeline/TimelineContainer.tsx
  src/components/common/Confirm/Confirm.provider.tsx
  src/components/common/Confirm/Confirm.style.ts
  src/components/template/Default/DefaultLayout.tsx
  src/themes/light-theme.ts
Labels: enhancement, Fix

#1036 Change avatar background for banned & deleted
  src/components/CommentList/CommentList.tsx
  src/components/atoms/Avatar/Avatar.interfaces.ts
  src/components/atoms/Avatar/Avatar.style.ts
  src/components/atoms/ListItem/index.tsx
Labels: bug

#1037 Update comment action button style
  src/components/CommentDeleted/CommentDeleted.tsx
  src/components/CommentDetail/CommentDetail.tsx
Labels: bug

#1038 Fix post layout
  src/components/PostDetail/PostDetail.styles.ts
  src/components/PostDetail/PostDetail.tsx
  src/components/PostDetail/render/Twitter.tsx
  src/components/atoms/Gallery/Gallery.styles.ts
  src/components/atoms/PostAction/index.tsx
  src/components/atoms/PostAction/postAction.style.ts
  src/components/atoms/Video/Video.tsx
  src/components/atoms/Voting/index.tsx
  src/components/atoms/Voting/voting.style.ts
  src/themes/light-theme.ts
Labels: bug, Improvement

#1039 Fix reply nested indent
  src/components/CommentDetail/CommentDetail.interface.ts
  src/components/CommentDetail/CommentDetail.styles.ts
  src/components/CommentDetail/CommentDetail.tsx
  src/components/CommentList/CommentList.container.tsx
  src/components/CommentList/CommentList.style.ts
  src/components/CommentList/CommentList.tsx
  src/components/EmbedURL/EmbedURL.tsx
  src/components/PostEditor/PostEditor.tsx
  src/lib/api/wallet.ts
Labels: bug

#1020 Combined implementation of near and myriad API authentication
  .env-template
  .gitignore
  next.config.js
  package.json
  pages/api/auth/[...nextauth].ts
  src/components/Login/Login.tsx
  src/components/Login/render/Options/Options.tsx
  src/components/Login/render/Profile/Profile.style.ts
  src/components/Login/render/Profile/Profile.tsx
  src/components/atoms/Icons/Network.tsx
  src/components/atoms/Icons/Wallet.tsx
  src/hooks/auth.hook.ts
  src/hooks/use-near-api.hook.ts
  src/images/network/polkadot.svg
  src/interfaces/login-near.ts
  src/interfaces/session.ts
  src/interfaces/user.ts
  src/lib/api/ext-auth.ts
  src/lib/api/user.ts
  src/lib/api/wallet.ts
  src/lib/serializers/session.ts
  src/lib/services/near-api-js.ts
  src/locale/en.json
  yarn.lock
Labels: Feature

#1042 Fix ingress className
  .github/workflows/deployer.yml
Labels: CI

#1044 add excluded tags on experience
  src/components/ExperienceEditor/Experience.container.tsx
  src/components/ExperienceEditor/ExperienceEditor.tsx
  src/components/ExperiencePreview/ExperienceEdit.container.tsx
  src/components/ExperiencePreview/ExperiencePreview.tsx
  src/components/ExperiencePreview/experience.style.ts
  src/hooks/use-experience-hook.ts
  src/interfaces/experience.ts
Labels: Improvement

#1043 Fx automatic decrease comment count on delete comment
  adapters/api.ts
  pages/profile/[id].tsx
  src/components/atoms/PostAction/index.tsx
  src/hooks/use-comment.hook.ts
  src/hooks/use-replies.hook.ts
  src/lib/api/comment.ts
  src/lib/api/user.ts
  src/lib/api/wallet.ts
  src/reducers/timeline/actions.ts
  src/reducers/timeline/constants.ts
  src/reducers/timeline/reducer.ts
  src/reducers/user/actions.ts
Labels: bug

#1045 Update post metric on delete
  src/components/CommentDetail/CommentDetail.tsx
  src/components/CommentList/CommentList.container.tsx
  src/components/PostDetail/PostDetail.styles.ts
  src/components/PostDetail/PostDetail.tsx
  src/components/PostDetail/hooks/use-comment-tabs.tsx
  src/hooks/use-comment.hook.ts
  src/hooks/use-replies.hook.ts
  src/lib/api/comment.ts
  src/reducers/timeline/actions.ts
Labels: bug

#1047 Resolve RPC connection error
  src/interfaces/user.ts
  src/lib/api/wallet.ts
  src/reducers/balance/actions.ts
Labels: bug, Fix

#1046 wiring profile card switch wallet and address
  pages/experience/[experienceId]/clone.tsx
  pages/experience/[experienceId]/edit.tsx
  pages/experience/[experienceId]/preview.tsx
  pages/experience/create.tsx
  pages/experience/index.tsx
  pages/friends.tsx
  pages/home.tsx
  pages/nft.tsx
  pages/notification.tsx
  pages/post/[postId].tsx
  pages/profile/[id].tsx
  pages/search.tsx
  pages/settings.tsx
  pages/socials.tsx
  pages/socialtoken.tsx
  pages/wallet.tsx
  src/components/MyWallet/MyWallet.tsx
  src/components/ProfileCard/NetworkOption/NetworkOption.tsx
  src/components/ProfileCard/NetworkOption/networkOption.style.ts
  src/components/ProfileCard/ProfileCard.container.tsx
  src/components/ProfileCard/ProfileCard.interfaces.ts
  src/components/ProfileCard/ProfileCard.tsx
  src/components/ProfileCard/ProfileContent.tsx
  src/components/ProfileCard/profileContent.style.ts
  src/interfaces/user.ts
  src/lib/api/wallet.ts
  src/reducers/user/actions.ts
  src/reducers/user/constants.ts
  src/reducers/user/reducer.ts
Labels: Feature

#1048 Bugfix/myr 1801
  adapters/api.ts
  src/components/ProfileHeader/ProfileHeaderContainer.tsx
  src/components/SendTip/SendTip.tsx
  src/lib/api/user.ts
  src/lib/api/wallet.ts
  src/reducers/user/actions.ts
Labels: bug, Fix

#1050 Fix github workflow setup gcloud step
  .github/workflows/analyzer.yml
  .github/workflows/builder.yml
  .github/workflows/deployer.yml
  .github/workflows/tester.yml
Labels: CI

#1051 Fix tipping on friend list
  src/components/FriendsMenu/FriendList.tsx
  src/lib/api/friends.ts
Labels: bug

#1052 Google auth with workload identity federation
  .github/workflows/deployer.yml
Labels: CI

#1053 Fix downvote & upvote indicator
  pages/post/[postId].tsx
  src/components/CommentDeleted/CommentDeleted.tsx
  src/components/CommentDetail/CommentDetail.tsx
  src/components/atoms/PostAction/index.tsx
  src/components/atoms/Voting/Voting.stories.tsx
  src/components/atoms/Voting/index.tsx
  src/components/atoms/Voting/voting.interface.ts
  src/components/atoms/Voting/voting.style.ts
  src/lib/api/post.ts
  src/reducers/user/actions.ts
Labels: bug

#1054 Fetch user wallet on topic page
  pages/topic/[type].tsx
Labels: bug

#1056 handle onMouseWheel on input amount & include transaction hash on explorer url
  src/components/common/Tipping/Tipping.interface.ts
  src/components/common/Tipping/Tipping.provider.tsx
  src/components/common/Tipping/Tipping.style.ts
  src/components/common/Tipping/Tipping.tsx
  src/components/common/Tipping/render/InputAmount/InputAmount.style.ts
  src/components/common/Tipping/render/InputAmount/InputAmount.tsx
  src/hooks/use-polkadot-api.hook.ts
Labels: bug

#1057 Checked if imported post already claimed
  src/components/common/Tipping/Tipping.tsx
  src/lib/api/post.ts
Labels: bug, Fix

#1058 add button notify on tipping imported post
  src/components/common/Tipping/Tipping.interface.ts
  src/components/common/Tipping/Tipping.provider.tsx
  src/components/common/Tipping/Tipping.tsx
  src/components/common/Tipping/render/ButtonNotify.styles.tsx
  src/components/common/Tipping/render/ButtonNotify.tsx
Labels: Feature

#1059 fixed wallet address in profile card
  pages/experience/[experienceId]/clone.tsx
  pages/experience/[experienceId]/edit.tsx
  pages/experience/[experienceId]/preview.tsx
  pages/experience/create.tsx
  pages/experience/index.tsx
  pages/friends.tsx
  pages/home.tsx
  pages/nft.tsx
  pages/notification.tsx
  pages/post/[postId].tsx
  pages/profile/[id].tsx
  pages/search.tsx
  pages/settings.tsx
  pages/socials.tsx
  pages/socialtoken.tsx
  pages/topic/[type].tsx
  pages/wallet.tsx
  src/components/ProfileCard/ProfileCard.container.tsx
Labels: bug

#1055 Add cookies consent component
  src/components/common/CookieConsent/CookieConsent.style.ts
  src/components/common/CookieConsent/CookieConsent.tsx
  src/components/common/CookieConsent/index.ts
  src/components/template/Default/DefaultLayout.tsx
  src/components/template/Login/Login.tsx
Labels: Feature

#1061 Change wallet address styling
  src/components/ProfileCard/ProfileCard.style.ts
  src/components/ProfileCard/ProfileCard.tsx
Labels: bug

#1062 Fix racing condition on loading transaction fee
  src/components/common/Tipping/Tipping.tsx
  src/lib/api/post.ts
Labels: bug

#1063 fixed prompt confirmation in profile card
  src/components/BalanceDetailList/BalanceDetailList.tsx
  src/components/ProfileCard/NetworkOption/NetworkOption.tsx
  src/components/atoms/DropdownMenu/DropdownMenu.tsx
Labels: bug

#1066 Enable click component block by cookies modal
  src/components/common/CookieConsent/CookieConsent.style.ts
  src/components/common/CookieConsent/CookieConsent.tsx
  src/components/template/Default/DefaultLayout.tsx
Labels: bug

#1065 bump version 2.0.0
  package.json
Labels: Feature

#1060 wiring tab manage
  pages/wallet.tsx
  src/components/Manage/Manage.container.tsx
  src/components/Manage/Manage.tsx
  src/components/Manage/use-wallet-list.hook.tsx
  src/components/PolkadotAccountList/PolkadotAccountList.tsx
  src/components/ProfileCard/NetworkOption/NetworkOption.tsx
  src/components/ProfileCard/ProfileCard.interfaces.ts
  src/components/atoms/Icons/Network.tsx
  src/hooks/auth.hook.ts
  src/interfaces/user.ts
  src/lib/api/wallet.ts
  src/lib/services/near-api-js.ts
  src/reducers/user/actions.ts
  src/reducers/user/constants.ts
  src/reducers/user/reducer.ts
Labels: Feature

#1064 Added Sender Wallet in Login screen
  src/components/Login/render/Login/Login.style.ts
  src/components/Login/render/Login/Login.tsx
  src/components/Login/render/Options/Options.style.ts
  src/components/Login/render/Options/Options.tsx
  src/components/atoms/Icons/Wallet.tsx
  src/components/common/NearLink.component.tsx
  src/images/wallet/sender-wallet-disabled.svg
  src/images/wallet/sender-wallet.svg
  src/lib/api/ext-auth.ts
  src/locale/en.json
Labels: bug, Fix

#1068 Added logics to show 0 unit balance
  src/components/common/Tipping/Tipping.tsx
Labels: Fix

#1069 created new Ui tab tip
  pages/wallet.tsx
  src/components/Tip/Tip.container.tsx
  src/components/Tip/Tip.tsx
  src/components/Tip/tip.style.ts
  src/components/atoms/Icons/Core.tsx
Labels: Feature

#1070 updated sort tip history
  src/components/HistoryDetailList/HistoryDetailList.tsx
  src/components/Timeline/default.ts
Labels: Fix

#1072 Fix loading tipping fee
  src/components/common/Tipping/Tipping.interface.ts
  src/components/common/Tipping/Tipping.provider.tsx
  src/components/common/Tipping/Tipping.tsx
  src/components/common/Tipping/render/InputAmount/InputAmount.tsx
  src/components/common/Tipping/render/Summary/Summary.style.ts
  src/components/common/Tipping/render/Summary/Summary.tsx
Labels: bug

#1073 Disable send tip if amount is invalid
  src/components/common/Tipping/Tipping.tsx
  src/components/common/Tipping/render/InputAmount/InputAmount.tsx
Labels: bug

#1074 fix format naming network
  src/components/BalanceDetailList/BalanceDetailList.tsx
  src/components/ProfileCard/ProfileCard.tsx
  src/components/ProfileCard/ProfileContent.tsx
Labels: Fix

#1076 Adjusted fetching query for transactions in history tab
  src/components/HistoryDetailList/HistoryDetailList.tsx
  src/components/TipHistory/TipHistory.tsx
  src/interfaces/transaction.ts
  src/reducers/transaction/actions.ts
Labels: Fix

#1071 restructure initialize near and read balance
  next.config.js
  src/components/WalletBalance/WalletBalanceContainer.tsx
  src/hooks/use-near-api.hook.ts
  src/hooks/use-polkadot-api.hook.ts
  src/interfaces/currency.ts
  src/interfaces/user.ts
  src/lib/services/near-api-js.ts
  src/reducers/balance/actions.ts
Labels: Feature

#1077 fix balance id on near wallet
  src/reducers/balance/actions.ts
Labels: bug
