Repository myriadsocial/myriad-web, pull requests merged in 2022-07, with the labels that each got.

#1315 Show comment missing action on mobile
  src/components/CommentDetail/CommentDetail.tsx
  src/components/template/Default/DefaultLayout.tsx
Labels: bug

#1316 Handled translation for error handling in create account form
  src/components/Login/render/Profile/Profile.tsx
  src/locale/en.json
Labels: bug

#1317 fix showing counter on timeline post
  pages/home.tsx
  pages/topic/[type].tsx
  src/components/Timeline/TimelineContainer.tsx
Labels: bug, Improvement

#1319 fix scroll to top reset counter
  src/components/Timeline/TimelineContainer.tsx
Labels: bug

#1320 bump version 2.1.8
  package.json
Labels: Document

#1323 fix visit public post when not logged in
  package.json
  src/components/CommentList/CommentList.container.tsx
  src/components/template/Default/DefaultLayout.tsx
Labels: bug

#1296 fix: connect social media
  src/components/AddSocialMedia/AddSocialMedia.tsx
  src/components/Manage/Manage.container.tsx
  src/components/SocialMediaList/SocialMediaList.container.tsx
  src/components/Socials/Socials.container.tsx
  src/components/Socials/Socials.tsx
  src/hooks/auth.hook.ts
  src/hooks/use-share-social.ts
  src/lib/api/social.ts
  src/lib/api/wallet.ts
  src/lib/services/polkadot-js.ts
Labels: Improvement

#1324 fix commenters avatar size on mobile
  src/components/CommentDetail/CommentDetail.tsx
  src/components/CommentEditor/CommentEditor.tsx
  src/components/common/Confirm/Confirm.style.ts
Labels: Improvement

#1325 fixed missing post's comment counter in mobile view
  src/components/PostAction/index.tsx
  src/components/PostAction/postAction.style.ts
Labels: bug

#1326 handle clear editor after submit comment
  src/components/CommentEditor/CommentEditor.tsx
Labels: bug

#1327 fix: showed unclaimable tip
  src/components/Tip/Tip.container.tsx
  src/components/Tip/Tip.tsx
  src/hooks/use-claim-tip.hook.ts
  src/lib/api/wallet.ts
  src/lib/services/near-api-js.ts
  src/lib/services/polkadot-js.ts
  src/reducers/balance/actions.ts
Labels: Improvement

#1329 Prevent prefetch on timeline
  src/components/PostDetail/render/Header/Header.tsx
  src/components/PostHeader/subHeader/post-sub-header.component.tsx
Labels: enhancement

#1321 ci: improve ci-cd
  .github/pull_request_template.md
  .github/workflows/builder.yml
  .github/workflows/create-tags.yml
  .github/workflows/deployer.yml
  .github/workflows/release.yml
  .github/workflows/update-version.yml
Labels: CI

#1332 Minimize import size
  src/components/BalanceDetailList/BalanceDetailList.tsx
  src/components/CommentEditor/CommentEditor.container.tsx
  src/components/CommentList/CommentList.container.tsx
  src/components/ExperienceEditor/Experience.container.tsx
  src/components/ExperiencePreview/ExperienceClone.container.tsx
  src/components/ExperiencePreview/ExperienceEdit.container.tsx
  src/components/FriendsMenu/FriendList.container.tsx
  src/components/FriendsMenu/FriendRequest.container.tsx
  src/components/Login/Login.tsx
  src/components/PostCreate/PostCreate.container.tsx
  src/components/PostEditor/PostRender.tsx
  src/components/PrimaryCoinMenu/PrimaryCoinMenu.tsx
  src/components/ProfileEdit/ProfileEdit.tsx
  src/components/ProfileHeader/ProfileHeaderContainer.tsx
  src/components/TipHistory/TipHistory.tsx
  src/components/atoms/CurrencyOption/index.tsx
  src/components/atoms/Search/SearchBox.tsx
  src/components/atoms/Voting/index.tsx
  src/components/common/Authorization/Authorization.context.tsx
  src/components/common/Authorization/Authorization.interface.ts
  src/components/common/Authorization/Authorization.provider.tsx
  src/components/common/Authorization/WithAuthorizeAction.tsx
  src/components/common/Linkify.component.tsx
  src/helpers/balance.ts
  src/helpers/wallet.ts
  src/hooks/use-claim-tip.hook.ts
  src/hooks/use-comment.hook.ts
  src/hooks/use-experience-hook.ts
  src/hooks/use-polkadot-api.hook.ts
  src/hooks/use-query-params.hooks.ts
  src/hooks/use-replies.hook.ts
  src/hooks/use-resize.hook.ts
  src/hooks/use-scroll.hook.ts
  src/lib/services/near-api-js.ts
Labels: bug

#1333 Fix video upload
  src/components/atoms/Dropzone/Dropzone.tsx
  src/components/atoms/Dropzone/Render/PreviewVideo.tsx
Labels: bug

#1334 Update vote alert on anonymous user
  src/components/atoms/Voting/index.tsx
  src/components/common/Authorization/WithAuthorizeAction.tsx
Labels: bug

#1335 Reduce image & bundle size
  pages/_app.tsx
  pages/_document.tsx
  pages/socials.tsx
  public/MyriadLogo.png
  public/favicon.ico
  public/favicon.svg
  src/components/Expericence/Experience.tsx
  src/components/ExperienceList/ExperienceList.container.tsx
  src/components/Mobile/Navbar/Navbar.tsx
  src/components/ProfileCard/NetworkOption/NetworkOption.tsx
  src/components/ProfileCard/ProfileCard.tsx
  src/components/RightMenuBar/tabs/ExperienceTab.tsx
  src/components/RightMenuBar/tabs/TrendingExperienceTab.tsx
  src/components/SocialMediaList/SocialMediaList.container.tsx
  src/components/Socials/Socials.container.tsx
  src/components/Tip/Tip.tsx
  src/components/TipHistory/TipHistory.provider.tsx
  src/components/common/Snackbar/useEnqueueSnackbar.hook.tsx
  src/components/template/Default/DefaultLayout.tsx
  src/hooks/use-claim-tip.hook.ts
  src/hooks/use-experience-hook.ts
  src/hooks/use-user.hook.ts
  src/interfaces/network.ts
  src/lib/services/polkadot-js.ts
Labels: bug

#1336 style: code formatting
  .github/workflows/analyzer.yml
  .github/workflows/builder.yml
  .github/workflows/create-tags.yml
  .github/workflows/deployer.yml
  .github/workflows/release.yml
  .github/workflows/tester.yml
  .github/workflows/update-version.yml
  .vscode/settings.json
Labels: CI

#1331 added experience name under post
  src/components/PostDetail/render/ExperienceInfo/ExperienceInfo.tsx
  src/components/PostDetail/render/ExperienceInfo/experience-info.style.ts
  src/components/PostDetail/render/Header/Header.tsx
  src/components/PostDetail/render/SubHeader/SubHeader.interface.ts
  src/components/PostDetail/render/SubHeader/SubHeader.style.ts
  src/components/PostDetail/render/SubHeader/SubHeader.tsx
  src/components/PostHeader/subHeader/post-sub-header.component.tsx
  src/components/PostHeader/subHeader/post-sub-header.style.ts
  src/hooks/use-experience-hook.ts
  src/interfaces/post.ts
  src/lib/api/experience.ts
  src/locale/en.json
  src/locale/id.json
  src/locale/ru.json
  src/reducers/experience/actions.ts
Labels: Fix, Feature

#1337 fix import near type and reduce bundle size
  src/lib/services/near-api-js.ts
Labels: bug

#1338 Fix mobile view post action
  pages/topic/[type].tsx
  src/components/PostDetail/PostDetail.styles.ts
  src/components/PostDetail/PostDetail.tsx
  src/components/PostList/PostList.container.tsx
Labels: bug

#1339 feat: implement near claim tips
  src/components/MyWallet/MyWallet.tsx
  src/components/Tip/Tip.container.tsx
  src/hooks/use-claim-tip.hook.ts
  src/hooks/use-near-api.hook.ts
  src/lib/api/wallet.ts
  src/lib/services/near-api-js.ts
Labels: Feature

#1341 fix styling pop up screen
  src/components/PostDetail/PostDetail.container.tsx
  src/components/common/SendTipButton/SendTipButton.style.ts
  src/components/common/SendTipButton/SendTipButton.tsx
Labels: Improvement

#1342 Fix toggle comment on downvote
  src/components/PostDetail/PostDetail.container.tsx
Labels: bug

#1343 Check new timeline based on current timeline filter
  src/components/TimelineFilter/TimelineFilter.container.tsx
  src/reducers/timeline/actions.ts
  src/reducers/timeline/reducer.ts
Labels: bug

#1344 Refactor Empty Component
  src/components/Expericence/ModalAddToPost/ModalAddToPost.provider.tsx
  src/components/ExperienceList/ExperienceList.empty.tsx
  src/components/ExperiencePreview/ExperiencePreview.tsx
  src/components/atoms/Empty/Empty.styles.ts
  src/components/atoms/Empty/Empty.tsx
  src/locale/en.json
  src/locale/id.json
  src/locale/ru.json
Labels: Improvement

#1322 Updated russian translation
  src/locale/id.json
  src/locale/ru.json
Labels: Fix

#1347 Parse filter post on topic page
  pages/topic/[type].tsx
  src/components/PostList/hooks/use-timeline-filter.hook.ts
  src/components/TipHistory/TipHistory.container.tsx
  src/hooks/tip-history.hook.ts
Labels: bug

#1348 Update post editor style
  src/components/PostEditor/PostEditor.styles.ts
Labels: bug

#1349 [WEB] Implement NEAR Claim Reference on Myriad Social
  next.config.js
  src/components/Tip/Tip.container.tsx
  src/components/Tip/TipNear.tsx
  src/components/Tip/tip.style.ts
  src/components/TotalTips/TipTotalNear.tsx
  src/components/TotalTips/totalTips.style.ts
  src/hooks/use-claim-tip.hook.ts
  src/hooks/use-near-api.hook.ts
  src/interfaces/network.ts
  src/lib/api/claim-reference.ts
  src/locale/en.json
  src/locale/id.json
  src/locale/ru.json
Labels: Feature

#1351 fix: claim reference
  src/components/Tip/Tip.container.tsx
  src/hooks/use-claim-tip.hook.ts
  src/lib/api/claim-reference.ts
Labels: Improvement

#1352 Fix vote behavior on post detail page
  package.json
  pages/embed.tsx
  pages/post/[postId].tsx
  src/components/CommentDetail/CommentDetail.tsx
  src/components/CommentList/CommentList.container.tsx
  src/components/CommentList/CommentList.tsx
  src/components/PostDetail/PostDetail.container.tsx
  src/components/PostDetail/PostDetail.interface.ts
  src/components/PostDetail/PostDetail.tsx
  src/components/PostList/PostList.container.tsx
  src/components/Timeline/TimelineAutoReloader.tsx
  src/components/atoms/Voting/index.tsx
  src/interfaces/post.ts
  src/lib/api/post.ts
  src/reducers/timeline/actions.ts
  src/reducers/timeline/reducer.ts
  yarn.lock
Labels: bug

#1353 ci: fix create tags & release
  .github/workflows/create-tags.yml
  .github/workflows/release.yml
  .github/workflows/tester.yml
Labels: CI

#1357 fixed switch primary coin
  src/components/BalanceDetailList/BalanceDetailListContainer.tsx
  src/components/PrimaryCoinMenu/PrimaryCoinMenu.tsx
  src/components/PrimaryCoinMenu/PrimaryCoinMenuContainer.tsx
  src/components/WalletBalance/WalletBalanceContainer.tsx
  src/components/template/Default/DefaultLayout.tsx
  src/hooks/use-currency.hook.ts
  src/lib/api/token.ts
Labels: bug

#1358 updated russian translation
  src/locale/ru.json
Labels: Fix

#1362 set own experience as default on right menu bar
  src/components/RightMenuBar/RightMenuBar.tsx
Labels: Fix

#1363 add non space break on list item
  src/components/TipHistory/TipHistory.tsx
  src/components/atoms/ListItem/index.tsx
Labels: Fix

#1365 fixed profile picture removed
  src/components/ProfileEdit/ProfileEditContainer.tsx
Labels: bug

#1367 Show Token Appchain on Myriad Network
  src/components/atoms/CurrencyOption/index.tsx
  src/hooks/auth.hook.ts
  src/hooks/use-near-api.hook.ts
  src/lib/services/polkadot-js.ts
Labels: Feature, Improvement

#1368 Fix filter & sort on profile post
  src/components/PostList/hooks/use-timeline-filter.hook.ts
  src/components/Profile/tabs/PostTabs.tsx
  src/components/UserMenu/hooks/user-tabs.hooks.tsx
  src/reducers/timeline/actions.ts
  src/reducers/timeline/reducer.ts
Labels: bug

#1369 Fix post owner check on tip button
  pages/post/[postId].tsx
  src/components/PostDetail/PostDetail.tsx
  src/components/Profile/tabs/PostTabs.tsx
  src/components/TipHistory/TipHistory.container.tsx
  src/components/TipHistory/TipHistory.tsx
  src/components/common/SendTipButton/SendTipButton.tsx
  src/hooks/tip-history.hook.ts
Labels: bug

#1370 Change show tip button condition
  src/components/PostDetail/PostDetail.tsx
Labels: bug

#1364 Implement claim reference in MYRIAD network
  src/components/MyWallet/MyWallet.tsx
  src/components/Tip/Tip.container.tsx
  src/components/Tip/Tip.tsx
  src/components/common/Tipping/Tipping.tsx
  src/hooks/use-claim-tip.hook.ts
  src/hooks/use-near-api.hook.ts
  src/hooks/use-polkadot-api.hook.ts
  src/lib/api/wallet.ts
  src/lib/services/near-api-js.ts
  src/lib/services/polkadot-js.ts
Labels: Feature

#1371 Fix search post user
  src/components/PostDetail/render/Header/Header.tsx
  src/components/Search/SearchResultContainer.tsx
  src/components/UserMenu/UserMenu.styles.ts
  src/components/atoms/TabList/TabList.styles.ts
Labels: bug

#1373 fix showing zero balance on near wallet
  src/lib/services/near-api-js.ts
Labels: bug

#1376 chore: bump version to 2.1.11
  package.json
Labels: Fix

#1377 experience preview image doesn't work properly
  src/components/atoms/Dropzone/Dropzone.tsx
Labels: bug

#1378 fix: removed data when PATCH notifications
  src/lib/api/notification.ts
  src/reducers/notification/actions.ts
Labels: Improvement

#1379 fix styling popup screen
  src/components/ExperiencePreview/ExperienceSignIn.tsx
  src/components/ExperiencePreview/experience.style.ts
Labels: Fix

#1382 feat: improved experience editor
  src/components/ExperienceEditor/Experience.styles.ts
  src/components/ExperienceEditor/ExperienceEditor.tsx
  src/components/atoms/Dropzone/Dropzone.styles.ts
  src/components/atoms/Dropzone/Dropzone.tsx
  src/locale/en.json
  src/locale/id.json
  src/locale/ru.json
Labels: Improvement

#1383 fix: fixed the date not translated
  src/components/PostDetail/render/SubHeader/SubHeader.tsx
  src/hooks/use-date.hooks.ts
Labels: bug

#1385 fix: profile and post url
  src/components/PostDetail/render/Header/Header.tsx
Labels: bug

#1386 fix: changed emoticon version
  package.json
  yarn.lock
Labels: Fix

#1381 Add modal when sending to the user that hasn't own a wallet
  src/components/common/Tipping/render/Summary/Summary.style.ts
  src/components/common/Tipping/render/Summary/Summary.tsx
  src/images/Icons/InfoIconYellow.svg
  src/interfaces/people.ts
  src/interfaces/user.ts
Labels: Feature

#1388 Customize mention plugin
  src/components/common/Editor/BasicEditor.tsx
  src/components/common/Editor/Editor.tsx
  src/components/common/Editor/plugins/CharLimit/withCharLimit.ts
  src/components/common/Editor/render/Counter.tsx
  src/components/common/Editor/render/Element/Mention/MentionCombobox.tsx
  src/components/common/Editor/render/Element/Mention/index.ts
  src/components/common/NodeViewer/NodeViewer.tsx
  src/reducers/search/actions.ts
  src/reducers/search/constants.ts
  src/reducers/search/reducer.ts
Labels: bug

#1384 feat: Tipping all appchain token
  pages/api/access-token.ts
  src/components/Tip/Tip.claim.reference.tsx
  src/components/Tip/Tip.container.tsx
  src/components/TotalTips/TipTotal.tsx
  src/components/atoms/CurrencyOption/index.tsx
  src/components/common/Tipping/Tipping.interface.ts
  src/components/common/Tipping/render/Summary/Summary.tsx
  src/helpers/balance.ts
  src/hooks/use-claim-tip.hook.ts
  src/hooks/use-polkadot-api.hook.ts
  src/interfaces/people.ts
  src/interfaces/user.ts
  src/lib/services/polkadot-js.ts
Labels: Feature

#1389 fix: improve imported post image
  src/components/atoms/Gallery/Gallery.tsx
  src/components/atoms/Gallery/util.ts
  src/helpers/image.ts
Labels: Improvement

#1390 fix: remove send tip button when imported post has owner
  src/components/PostDetail/PostDetail.tsx
  src/interfaces/people.ts
  src/interfaces/post.ts
Labels: Improvement

#1391 Fix dispaying editor component
  src/components/common/Editor/Editor.tsx
  src/components/common/Editor/plugins/CharLimit/withCharLimit.ts
  src/components/common/Editor/render/Element/MediaEmbed/MediaEmbed.tsx
  src/components/common/Editor/render/Toolbar/Button/MediaEmbedButton.tsx
  src/components/common/NodeViewer/NodeViewer.tsx
  src/components/common/NodeViewer/formatter.ts
Labels: bug

#1392 Enable user to subscribe experience more than 10
  src/components/ExperienceList/ExperienceList.container.tsx
  src/components/ExperiencePreview/ExperiencePreview.container.tsx
  src/components/RightMenuBar/tabs/ExperienceTab.tsx
  src/components/TimelineFilter/TimelineFilter.container.tsx
  src/hooks/use-experience-hook.ts
  src/lib/api/experience.ts
  src/lib/api/interfaces/base-list.interface.ts
  src/reducers/user/actions.ts
  src/reducers/user/reducer.ts
Labels: Improvement

#1393 Fix mention & preview post
  pages/embed.tsx
  pages/post/[postId].tsx
  src/components/CommentEditor/CommentAction.tsx
  src/components/CommentEditor/CommentEditor.style.ts
  src/components/CommentEditor/CommentEditor.tsx
  src/components/PostCreate/PostCreate.tsx
  src/components/PostDetail/PostDetail.interface.ts
  src/components/PostDetail/PostDetail.tsx
  src/components/common/Editor/BasicEditor.tsx
  src/components/common/Editor/Editor.style.ts
  src/components/common/Editor/Editor.tsx
  src/components/common/Editor/plugins/CharLimit/withCharLimit.ts
  src/components/common/Editor/plugins/Mention/createMentionPlugin.ts
  src/components/common/Editor/plugins/Mention/index.ts
  src/components/common/Editor/plugins/Mention/withMention.ts
  src/components/common/Editor/plugins/index.ts
  src/components/common/Editor/render/Element/MediaEmbed/MediaEmbed.tsx
  src/components/common/NodeViewer/NodeViewer.tsx
Labels: bug

#1394 fix: handle redit regex
  src/components/PostImport/PostImport.tsx
Labels: Improvement

#1395 Add missing insert text
  src/components/common/Editor/plugins/CharLimit/withCharLimit.ts
Labels: bug

#1396 Handle mention & hashtag click
  src/components/PostCreate/PostCreate.tsx
  src/components/common/Editor/Editor.tsx
  src/components/common/Editor/plugins/CharLimit/withCharLimit.ts
  src/components/common/Editor/render/Element/Hashtag/HashtagElement.style.ts
  src/components/common/Editor/render/Element/Hashtag/HashtagElement.tsx
  src/components/common/NodeViewer/NodeViewer.tsx
  src/reducers/timeline/actions.ts
Labels: bug

#1397 fix load pagination experience list on right side menu
  package.json
  src/components/ExperienceList/ExperienceList.container.tsx
Labels: bug

#1398 Remove unmount combobox
  src/components/common/Editor/Editor.tsx
Labels: bug

#1399 feat: updated russian translation
  src/components/ExperienceEditor/ExperienceEditor.tsx
  src/locale/en.json
  src/locale/id.json
  src/locale/ru.json
Labels: Improvement

#1400 fix: fix Russian translation
  src/locale/ru.json
Labels: bug

#1402 fix: handle image in post metadata
  pages/post/[postId].tsx
  src/components/PostCreate/formatter.ts
  src/components/PostDetailExperience/PostDetailExperience.tsx
  src/interfaces/post.ts
Labels: Improvement

#1403 Button save changes disabled if user only remove profile picture
  src/components/ProfileEdit/ProfileEdit.tsx
Labels: Improvement

#1404 Add emoji button on desktop comment editor
  src/components/CommentEditor/CommentAction.tsx
  src/components/CommentEditor/CommentEditor.tsx
  src/components/CommentHistory/CommentHistory.tsx
  src/components/common/Editor/BasicEditor.tsx
Labels: bug, enhancement

#1406 make the thumnail image bigger on medsos sharing
  pages/experience/[experienceId]/index.tsx
  pages/post/[postId].tsx
  pages/profile/[id].tsx
Labels: Improvement

#1405 Reset scroll timeline on refresh
  src/components/Timeline/Timeline.layout.tsx
Labels: bug

#1407 Prevent load post editor when anonymous
  src/components/PostCreate/PostCreate.container.tsx
Labels: bug

#1408 fix size thumnail on telegram sharing
  pages/experience/[experienceId]/index.tsx
  pages/post/[postId].tsx
  pages/profile/[id].tsx
Labels: Improvement

#1409 fix profile banner and experience card styles
  src/components/Expericence/Experience.style.ts
  src/components/ProfileEdit/ProfileEdit.tsx
  src/components/ProfileEdit/ProfileEditContainer.tsx
Labels: bug

#1411 fix: implement new notification type
  src/components/Notifications/hooks/use-notification-list.hook.tsx
  src/interfaces/notification.ts
Labels: Improvement

#1412 Fix editor text counter
  src/components/common/NodeViewer/NodeViewer.tsx
  src/components/common/NodeViewer/formatter.ts
Labels: bug

#1410 fix button save changes disabled if user remove/change picture
  src/components/ProfileEdit/ProfileEdit.tsx
Labels: bug

#1401 fix: tipping improvement
  pages/experience/[experienceId]/clone.tsx
  pages/experience/[experienceId]/edit.tsx
  pages/experience/[experienceId]/index.tsx
  pages/experience/create.tsx
  pages/friends.tsx
  pages/home.tsx
  pages/post/[postId].tsx
  pages/profile/[id].tsx
  pages/search.tsx
  pages/settings.tsx
  pages/socials.tsx
  pages/socialtoken.tsx
  pages/topic/[type].tsx
  pages/wallet.tsx
  src/components/BalanceDetailList/BalanceDetailList.tsx
  src/components/BalanceDetailList/BalanceDetailListContainer.tsx
  src/components/PrimaryCoinMenu/PrimaryCoinMenu.tsx
  src/components/PrimaryCoinMenu/PrimaryCoinMenuContainer.tsx
  src/components/ProfileCard/NetworkOption/NetworkOption.tsx
  src/components/Tip/Tip.container.tsx
  src/components/Tip/Tip.tsx
  src/components/WalletBalance/WalletBalanceContainer.tsx
  src/components/WalletBalance/index.tsx
  src/components/atoms/CurrencyOption/index.tsx
  src/components/common/Tipping/Tipping.interface.ts
  src/components/common/Tipping/Tipping.provider.tsx
  src/components/common/Tipping/Tipping.tsx
  src/components/common/Tipping/render/FormatCurrency.tsx
  src/components/common/Tipping/render/Summary/Summary.tsx
  src/components/template/Default/DefaultLayout.tsx
  src/helpers/balance.ts
  src/hooks/auth.hook.ts
  src/hooks/use-claim-tip.hook.ts
  src/hooks/use-currency.hook.ts
  src/hooks/use-near-api.hook.ts
  src/hooks/use-polkadot-api.hook.ts
  src/lib/api/user.ts
  src/lib/services/near-api-js.ts
  src/lib/services/polkadot-js.ts
  src/reducers/balance/actions.ts
  src/reducers/user/actions.ts
Labels: Improvement

#1413 Add embed myriad town
  pages/town.tsx
  public/images/animated_new.gif
  src/components/Menu/Menu.container.tsx
  src/components/Menu/Menu.tsx
  src/components/Menu/use-menu-list.tsx
  src/components/Mobile/MenuDrawer/MenuDrawer.tsx
  src/components/Town/Town.container.tsx
  src/components/Town/town.style.ts
  src/components/atoms/ListItem/index.tsx
  src/components/atoms/TopNavbar/TopNavbar.interfaces.ts
  src/locale/en.json
  src/locale/id.json
  src/locale/ru.json
Labels: Feature

#1414 fix: button save edit profile, profile picture is not removed
  src/components/ProfileEdit/ProfileEdit.tsx
  src/components/ProfileEdit/ProfileEditContainer.tsx
Labels: bug

#1415 Fix heroicon color
  src/components/CommentEditor/CommentEditor.style.ts
Labels: bug

#1416 fix overlapping text version in mobile
  src/components/Settings/Settings.styles.ts
  src/components/Settings/Settings.tsx
Labels: bug

#1419 Update post detail style
  src/components/PostDetail/render/Reddit.tsx
  src/components/atoms/Gallery/Gallery.styles.ts
  src/components/atoms/NSFW/nsfw.style.ts
  src/components/atoms/Video/Video.tsx
  src/components/common/Editor/render/Element/MediaEmbed/MediaEmbed.tsx
Labels: bug

#1417 fix: mismatch tipping amount
  src/components/Tip/Tip.container.tsx
  src/components/common/Tipping/Tipping.tsx
  src/components/common/Tipping/render/InputAmount/InputAmount.tsx
  src/hooks/use-polkadot-api.hook.ts
  src/lib/services/polkadot-js.ts
Labels: bug

#1420 fix: show appchain token
  src/components/Tip/Tip.tsx
  src/lib/services/polkadot-js.ts
Labels: Improvement

#1421 add disclaimer on myriad town page
  package.json
  src/components/Town/Town.container.tsx
  src/components/Town/town.style.ts
  src/locale/en.json
  src/locale/id.json
  src/locale/ru.json
Labels: Feature
