Repository myriadsocial/myriad-web, pull requests merged in 2022-05, with the labels that each got.

#1154 MYR-1895: add meta to experience detail page
  pages/experience/[experienceId]/preview.tsx
Labels: Feature

#1153 Remove walletType from Wallet
  src/components/BalanceDetailList/BalanceDetailListContainer.tsx
  src/components/CommentDeleted/CommentDeleted.stories.tsx
  src/components/CommentDetail/CommentDetail.stories.tsx
  src/components/CommentEditor/CommentEditor.stories.tsx
  src/components/ExperienceList/ExperienceList.stories.tsx
  src/components/Manage/use-wallet-list.hook.tsx
  src/components/PostDetail/PostDetail.stories.tsx
  src/components/ProfileCard/NetworkOption/NetworkOption.tsx
  src/components/ProfileCard/ProfileCard.tsx
  src/components/ProfileCard/ProfileContent.tsx
  src/components/ProfileEdit/ProfileEdit.stories.tsx
  src/components/ProfileEdit/ProfileEdit.tsx
  src/components/ProfileEdit/ProfileEditContainer.tsx
  src/components/ProfileHeader/index.tsx
  src/components/ProfileHeader/profile-header.stories.tsx
  src/components/Socials/Socials.stories.tsx
  src/components/Timeline/Timeline.stories.tsx
  src/components/TipHistory/TipHistory.stories.tsx
  src/components/UserMenu/UserMenu.stories.tsx
  src/components/WalletBalance/WalletBalance.stories.tsx
  src/components/WalletBalance/WalletBalanceContainer.tsx
  src/components/atoms/PostHeader/PostHeader.stories.tsx
  src/components/common/Tipping/Tipping.tsx
  src/components/template/Default/DefaultLayout.tsx
  src/helpers/extension.ts
  src/hooks/auth.hook.ts
  src/hooks/use-near-api.hook.ts
  src/hooks/use-polkadot-api.hook.ts
  src/interfaces/network.ts
  src/interfaces/user.ts
  src/interfaces/wallet.ts
  src/lib/api/ext-auth.ts
  src/lib/api/wallet.ts
  src/reducers/balance/actions.ts
  src/reducers/user/actions.ts
Labels: Improvement

#1155 Allow anonymous on share experience page
  pages/experience/[experienceId]/preview.tsx
Labels: bug

#1157 created trending experience
  src/components/Expericence/Experience.tsx
  src/components/ExperienceList/hooks/use-experience-list.hook.ts
  src/components/RightMenuBar/RightMenuBar.tsx
  src/components/RightMenuBar/tabs/Tab.style.ts
  src/components/RightMenuBar/tabs/TrendingExperienceTab.tsx
  src/hooks/use-experience-hook.ts
  src/lib/api/experience.ts
  src/reducers/experience/actions.ts
  src/reducers/experience/constants.ts
  src/reducers/experience/reducer.ts
  src/themes/light-theme.ts
Labels: Feature

#1159 Fix clone experience implementation
  src/components/Expericence/Experience.tsx
  src/components/ExperiencePreview/ExperienceClone.container.tsx
  src/hooks/use-experience-hook.ts
  src/lib/api/experience.ts
  src/reducers/experience/actions.ts
  src/reducers/timeline/actions.ts
Labels: bug

#1161 fixed params order get experience
  src/components/ExperienceList/ExperienceList.container.tsx
  src/components/ExperienceList/ExperienceList.tsx
  src/components/Timeline/hooks/use-timeline-filter.hook.ts
  src/lib/api/experience.ts
Labels: Fix

#1160 add bug issue template
  .github/issue_bug_template.md
Labels: Document

#1162 Add modal share experience
  src/components/Expericence/Experience.style.ts
  src/components/Expericence/Experience.tsx
  src/components/PostEditor/PostEditor.tsx
Labels: bug

#1163 rename issue_template
  .github/issue_template.md
Labels: CI

#1164 Redirect to comment section from notification
  src/components/Notifications/hooks/use-notification-list.hook.tsx
  src/components/PostDetail/PostDetail.tsx
  src/components/PostDetail/hooks/use-comment-tabs.tsx
  src/components/atoms/Tabs/Tabs.types.ts
  src/interfaces/notification.ts
Labels: bug

#1165 Add proxy req log
  pages/api/[...all].ts
  src/lib/api/base.ts
Labels: bug

#1166 Update search user API
  pages/api/[...all].ts
  src/lib/api/user.ts
Labels: enhancement

#1168 Fixed switch network
  src/components/Login/Login.tsx
  src/components/Login/render/Profile/Profile.tsx
  src/components/ProfileCard/NetworkOption/NetworkOption.tsx
  src/hooks/auth.hook.ts
  src/lib/api/ext-auth.ts
  src/lib/api/user.ts
  src/lib/api/wallet.ts
  src/reducers/balance/actions.ts
Labels: Improvement

#1169 Update comment counter
  src/components/PostDetail/hooks/use-comment-tabs.tsx
  src/components/atoms/PostAction/postAction.style.ts
Labels: bug

#1171 fix button modal success prompt after tipping with near
  src/components/common/Tipping/render/Tipping.success.tsx
Labels: bug

#1172 Wrap rightbar svgicon
  src/components/RightMenuBar/RightMenuBar.tsx
Labels: bug

#1173 Bugfix when switch network
  src/components/ProfileCard/NetworkOption/NetworkOption.tsx
Labels: Improvement

#1174 fix on handling selected experience
  src/components/Expericence/ModalAddToPost/ModalAddToPost.provider.tsx
  src/components/common/Tipping/render/Tipping.success.tsx
  src/lib/api/experience.ts
Labels: bug

#1175 added translation in friends page
  pages/friends.tsx
  src/components/FriendsMenu/FriendList.tsx
  src/components/FriendsMenu/FriendMenu.tsx
  src/components/FriendsMenu/FriendRequest.tsx
  src/components/FriendsMenu/default.ts
  src/locale/en.json
  src/locale/id.json
Labels: Feature

#1176 Add tipping success component on search & friends page
  pages/friends.tsx
  pages/search.tsx
  src/components/common/Tipping/render/Tipping.success.tsx
Labels: bug

#1177 Update axios cookies config
  pages/experience/[experienceId]/clone.tsx
  pages/experience/[experienceId]/edit.tsx
  pages/experience/[experienceId]/preview.tsx
  pages/experience/create.tsx
  pages/friends.tsx
  pages/home.tsx
  pages/index.tsx
  pages/notification.tsx
  pages/post/[postId].tsx
  pages/profile/[id].tsx
  pages/search.tsx
  pages/settings.tsx
  pages/socials.tsx
  pages/topic/[type].tsx
  pages/wallet.tsx
  src/lib/api/activity.ts
  src/lib/api/base.ts
  src/lib/api/comment.ts
  src/lib/api/exchange.ts
  src/lib/api/experience.ts
  src/lib/api/ext-auth.ts
  src/lib/api/friends.ts
  src/lib/api/importers.ts
  src/lib/api/interaction.ts
  src/lib/api/leaderboard.ts
  src/lib/api/network.ts
  src/lib/api/notification.ts
  src/lib/api/people.ts
  src/lib/api/post.ts
  src/lib/api/setting.ts
  src/lib/api/social.ts
  src/lib/api/tag.ts
  src/lib/api/token.ts
  src/lib/api/transaction.ts
  src/lib/api/upload.ts
  src/lib/api/user.ts
  src/lib/api/wallet.ts
  src/reducers/tip-summary/actions.ts
Labels: bug

#1181 Enable scroll in mention select
  src/components/CommentDetail/CommentDetail.tsx
  src/components/CommentEditor/CommentEditor.tsx
  src/components/CommentList/CommentList.container.tsx
  src/components/PostCreate/PostCreate.tsx
  src/components/PostEditor/PostEditor.stories.tsx
  src/components/PostEditor/PostEditor.tsx
  src/components/PostEditor/Render/Mention/MentionSelect/MentionSelect.styles.ts
  src/components/PostEditor/Render/Mention/MentionSelect/index.tsx
  src/components/TimelineFilter/TimelineFilter.container.tsx
Labels: bug

#1182 Added translation in wallet page
  pages/wallet.tsx
  src/components/BalanceDetailList/BalanceDetailList.tsx
  src/components/HistoryDetailList/HistoryDetailList.tsx
  src/components/HistoryDetailList/default.ts
  src/components/Manage/Manage.tsx
  src/components/MyWallet/MyWallet.tsx
  src/components/MyWallet/MyWalletContainer.tsx
  src/components/PrimaryCoinMenu/PrimaryCoinMenu.tsx
  src/components/Timeline/default.ts
  src/components/Tip/Tip.container.tsx
  src/components/Tip/Tip.tsx
  src/locale/en.json
  src/locale/id.json
Labels: Feature

#1183 added translation in Profile page
  pages/profile/[id].tsx
  src/components/CommentHistory/CommentHistory.tsx
  src/components/CommentHistoryList/CommentHistoryList.container.tsx
  src/components/CommentHistoryList/CommentHistoryList.tsx
  src/components/Expericence/Experience.tsx
  src/components/ExperienceList/ExperienceList.container.tsx
  src/components/FriendsMenu/FriendList.container.tsx
  src/components/FriendsMenu/FriendList.tsx
  src/components/Metric/Metric.tsx
  src/components/Profile/EmptyProfilePost.tsx
  src/components/Profile/PrivateProfile.tsx
  src/components/Profile/Profile.tsx
  src/components/Profile/tabs/ExperienceTab.tsx
  src/components/ProfileEdit/ProfileEdit.tsx
  src/components/ProfileEdit/ProfileEditContainer.tsx
  src/components/ProfileHeader/ProfileHeaderContainer.tsx
  src/components/ProfileHeader/index.tsx
  src/components/Timeline/default.ts
  src/components/UserMenu/hooks/user-tabs.hooks.tsx
  src/components/UserSettings/UserSettings.container.tsx
  src/components/UserSocials/UserSocials.tsx
  src/locale/en.json
  src/locale/id.json
Labels: Feature

#1184 Recreate axios instance when cookie changed
  pages/experience/[experienceId]/clone.tsx
  pages/experience/[experienceId]/edit.tsx
  pages/experience/[experienceId]/preview.tsx
  pages/experience/create.tsx
  pages/friends.tsx
  pages/home.tsx
  pages/notification.tsx
  pages/post/[postId].tsx
  pages/profile/[id].tsx
  pages/search.tsx
  pages/settings.tsx
  pages/socials.tsx
  pages/topic/[type].tsx
  pages/wallet.tsx
  src/lib/api/base.ts
Labels: bug

#1185 Added EN-ID translations for Settings interface
  pages/settings.tsx
  src/components/BlockUserList/BlockList.tsx
  src/components/Settings/AccountSettings.tsx
  src/components/Settings/LanguageSetting.tsx
  src/components/Settings/NotificationSettings.tsx
  src/components/Settings/Settings.tsx
  src/components/Settings/default.ts
  src/components/Settings/hooks/use-account-setting.hook.ts
  src/components/Settings/hooks/use-notification-setting.hook.ts
  src/components/atoms/TopNavbar/TopNavbar.tsx
  src/components/common/Help/Help.tsx
  src/locale/en.json
  src/locale/id.json
Labels: enhancement

#1188 added translation in Experience Editor
  src/components/ExperienceEditor/Experience.container.tsx
  src/components/ExperienceEditor/ExperienceEditor.tsx
  src/components/ExperiencePreview/ExperienceClone.container.tsx
  src/components/ExperiencePreview/ExperienceEdit.container.tsx
  src/components/atoms/Dropzone/Dropzone.tsx
  src/locale/en.json
  src/locale/id.json
Labels: Improvement

#1186 Update fetch balance condition
  src/components/BalanceDetailList/BalanceDetailListContainer.tsx
  src/components/Profile/EmptyProfilePost.tsx
  src/hooks/auth.hook.ts
  src/lib/api/base.ts
  src/reducers/balance/actions.ts
  src/reducers/balance/reducer.ts
Labels: bug

#1191 Enable clone and subscribe trending experience
  src/components/RightMenuBar/tabs/TrendingExperienceTab.tsx
Labels: bug

#1192 add minor fixing
  src/components/FriendsMenu/FriendList.tsx
  src/components/PostDetailExperience/PostDetailExperienceHeader.tsx
  src/locale/en.json
  src/locale/id.json
Labels: Improvement

#1193 add translation on tipping popup and tipping history popup
  src/components/TipHistory/TipHistory.tsx
  src/components/TipHistory/default.ts
  src/components/atoms/CurrencyOption/index.tsx
  src/components/common/TermOfService/TermOfService.tsx
  src/components/common/Tipping/Tipping.provider.tsx
  src/components/common/Tipping/Tipping.tsx
  src/components/common/Tipping/render/ButtonNotify.tsx
  src/components/common/Tipping/render/Info.tsx
  src/components/common/Tipping/render/InputAmount/InputAmount.tsx
  src/components/common/Tipping/render/Summary/Summary.tsx
  src/components/common/Tipping/render/Tipping.success.tsx
  src/hooks/use-polkadot-api.hook.ts
  src/locale/en.json
  src/locale/id.json
Labels: Improvement

#1195 bump version 2.1.1
  package.json
Labels: Improvement

#1197 fix translation on handling error input amount tipping
  src/components/common/Tipping/render/InputAmount/InputAmount.tsx
  src/locale/en.json
  src/locale/id.json
Labels: Improvement

#1198 Fix translation navbar
  pages/post/[postId].tsx
  src/components/atoms/TopNavbar/TopNavbar.tsx
  src/locale/en.json
Labels: bug, Improvement

#1194 Show notification counter
  src/components/CommentDetail/CommentDetail.tsx
  src/components/PostDetail/hooks/use-comment-tabs.tsx
  src/components/ProfileCard/ProfileContent.tsx
  src/components/ProfileHeader/ProfileHeaderContainer.tsx
  src/components/ProfileHeader/index.tsx
  src/components/atoms/PostAction/index.tsx
  src/components/atoms/Voting/index.tsx
  src/hooks/tip-history.hook.ts
  src/hooks/use-tip-summary.hook.ts
  src/locale/en.json
  src/locale/id.json
  src/reducers/tip-summary/actions.ts
  src/reducers/tip-summary/reducer.ts
  src/themes/light-theme.ts
Labels: bug, enhancement

#1199 Added post visibility card translations
  src/components/PostVisibility/PostVisibility.container.tsx
  src/components/PostVisibility/PostVisibility.tsx
  src/components/PostVisibility/use-post-visibility-list.hook.ts
  src/locale/en.json
  src/locale/id.json
Labels: Improvement

#1200 Added translations for Post Delete Prompt
  src/components/PostDetail/PostDetail.container.tsx
  src/components/Timeline/TimelineContainer.tsx
  src/locale/en.json
  src/locale/id.json
Labels: Improvement

#1201 Add missing tip payload
  src/components/ProfileCard/Network.skeleton.tsx
  src/components/ProfileCard/NetworkOption/NetworkOption.tsx
  src/components/ProfileCard/ProfileCard.tsx
  src/components/common/Tipping/render/Tipping.success.tsx
  src/reducers/balance/actions.ts
Labels: bug

#1202 added translation
  pages/nft.tsx
  pages/socialtoken.tsx
  src/components/EmbedURL/EmbedURL.tsx
  src/components/NFT/NFT.container.tsx
  src/components/PostEditor/PostEditor.tsx
  src/components/PostEditor/Toolbar/ToolbarMedia.tsx
  src/components/ProfileCard/ProfileContent.tsx
  src/components/SocialToken/SocialToken.container.tsx
  src/components/Upload/Upload.tsx
  src/components/UsersList/UsersList.tsx
  src/components/WalletBalance/WalletBalanceContainer.tsx
  src/components/WalletBalance/index.tsx
  src/components/atoms/Dropzone/Dropzone.tsx
  src/locale/en.json
  src/locale/id.json
Labels: Improvement

#1205 Added translations for Comment tabs and placeholders
  src/components/PostDetail/hooks/use-comment-tabs.tsx
  src/locale/en.json
  src/locale/id.json
Labels: Improvement

#1206 Added translations for Create and Import Post
  src/locale/en.json
  src/locale/id.json
  src/reducers/timeline/actions.ts
Labels: Improvement

#1207 Added translations for error text and header
  src/components/PostImport/PostImport.tsx
  src/locale/en.json
  src/locale/id.json
Labels: Improvement

#1208 Update showmore component
  src/components/CommentEditor/CommentEditor.style.ts
  src/components/PostEditor/Render/ShowMore/ShowMore.styles.ts
  src/components/PostEditor/Render/ShowMore/index.tsx
Labels: bug

#1210 fixed position translation
  src/locale/en.json
Labels: bug, Fix

#1211 Added translations for Search page
  src/components/PostsList/PostsList.tsx
  src/components/Search/SearchResultContainer.tsx
  src/locale/en.json
  src/locale/id.json
Labels: Improvement

#1212 Added translations for importer list
  src/components/PostImporterList/PostImporter.tsx
  src/locale/en.json
  src/locale/id.json
Labels: Improvement

#1213 Added translations for post subheader for imported posts
  src/components/atoms/PostHeader/subHeader/post-sub-header.component.tsx
  src/locale/en.json
  src/locale/id.json
Labels: Improvement

#1214 translation improvement
  src/components/ExperienceList/ExperienceList.empty.tsx
  src/components/RightMenuBar/RightMenuBar.tsx
  src/components/RightMenuBar/tabs/ExperienceTab.tsx
  src/components/RightMenuBar/tabs/TrendingExperienceTab.tsx
  src/components/SocialMediaList/SocialMediaList.tsx
  src/components/Timeline/Timeline.tsx
  src/components/atoms/BannerStatus/BannerStatus.tsx
  src/components/common/CookieConsent/CookieConsent.tsx
  src/locale/en.json
  src/locale/id.json
Labels: Improvement

#1215 add translation on comment section
  src/components/CommentDetail/CommentDetail.tsx
  src/components/PostEditor/Render/ShowMore/index.tsx
  src/components/Richtext/index.tsx
  src/components/common/TimeAgo.component.tsx
  src/locale/en.json
  src/locale/id.json
Labels: Improvement

#1216 add translation on report component for post and user
  src/components/Report/Report.tsx
  src/components/Report/use-post-report-list.hook.ts
  src/components/atoms/Report/Report.component.tsx
  src/hooks/use-report.hook.ts
  src/locale/en.json
  src/locale/id.json
Labels: Improvement

#1217 Fix duplicate package
  package.json
  yarn.lock
Labels: enhancement

#1219 add translation on maintenance and 404 page
  pages/404.tsx
  pages/maintenance.tsx
  src/components/CommentDeleted/CommentDeleted.tsx
  src/components/CommentDetail/CommentRender.tsx
  src/components/CommentList/CommentList.container.tsx
  src/locale/en.json
  src/locale/id.json
Labels: Improvement

#1220 Fix Near redirect url
  src/components/ProfileCard/NetworkOption/NetworkOption.tsx
Labels: bug

#1221 Fix post margin
  src/components/PostDetail/PostDetail.tsx
  src/components/PostDetail/render/Reddit.tsx
  src/components/PostDetail/render/Twitter.tsx
  src/components/atoms/PostHeader/cardTitle/CardTitle.component.tsx
  src/components/atoms/Video/Video.tsx
Labels: bug

#1222 Update format balance on notify socmed
  src/components/common/Tipping/render/ButtonNotify.tsx
Labels: bug

#1223 Show tip history on own profile
  src/components/ProfileHeader/index.tsx
Labels: bug
