Repository myriadsocial/myriad-web, pull requests merged in 2022-12, with the labels that each got.

#1595 fix: add button load more on experience
  src/components/Expericence/ModalAddToPost/ModalAddToPost.provider.tsx
  src/components/ExperienceList/ExperienceList.container.tsx
Labels: bug

#1594 feat: add nova wallet on wallet options
  src/components/Login/render/Options/Options.tsx
  src/components/atoms/Icons/Wallet.tsx
  src/images/wallet/nova-disable.svg
Labels: Feature

#1593 fix: friend interaction
  src/components/Profile/Profile.container.tsx
  src/components/Profile/Profile.tsx
  src/components/ProfileBanned/ProfileBanned.tsx
  src/components/ProfileCard/ProfileContent.tsx
  src/components/ProfileHeader/ProfileHeaderContainer.tsx
  src/components/ProfileHeader/hooks/use-friend-options.hook.ts
  src/components/ProfileHeader/index.tsx
  src/components/UserMenu/hooks/user-tabs.hooks.tsx
  src/hooks/use-friend-request.hook.ts
  src/hooks/use-friends-hook.ts
  src/interfaces/friend.ts
  src/interfaces/user.ts
  src/lib/api/user.ts
  src/lib/api/wallet.ts
  src/reducers/friend-request/actions.ts
  src/reducers/friend/actions.ts
  src/reducers/profile/actions.ts
  src/reducers/profile/reducer.ts
Labels: Improvement

#1596 fix: visit profile error
  pages/profile/[id].tsx
  src/components/Profile/Profile.tsx
  src/components/ProfileHeader/ProfileHeaderContainer.tsx
  src/components/ProfileHeader/hooks/use-friend-options.hook.ts
  src/components/ProfileHeader/index.tsx
  src/hooks/use-friend-request.hook.ts
  src/reducers/friend-request/actions.ts
Labels: Improvement

#1599 fix: editor max character validation
  src/components/common/Editor/plugins/CharLimit/createCharLimitPlugin.ts
  src/components/common/Editor/plugins/CharLimit/onKeydownLimit.ts
Labels: Fix

#1600 feat: Custom Visibilities Setting on Post
  src/components/PostCreate/PostCreate.styles.ts
  src/components/PostCreate/PostCreate.tsx
  src/components/PostCreate/SettingVisibility.styles.ts
  src/components/PostCreate/SettingVisibility.tsx
  src/components/PostCreate/default.ts
  src/components/atoms/ListItem/ListItemPeople.tsx
  src/interfaces/post.ts
  src/lib/api/post.ts
Labels: Feature

#1602 fix: error handling for imported post
  src/components/PostCreate/PostCreate.container.tsx
  src/locale/en.json
  src/locale/id.json
  src/locale/ru.json
Labels: Improvement

#1615 fix: handle asset in post detail component
  src/components/PostDetail/PostDetail.tsx
  src/interfaces/post.ts
Labels: Improvement

#1620 fix: improve query
  src/lib/api/experience.ts
  src/reducers/experience/actions.ts
Labels: Improvement
