Repository myriadsocial/myriad-web, pull requests merged in 2022-04, with the labels that each got.

#1078 Deduce gas fee from max tip amount
  src/components/common/Tipping/Tipping.tsx
  src/components/common/Tipping/render/InputAmount/InputAmount.tsx
Labels: bug

#1080 Enabled signing in to Myriad using other NEAR wallets
  src/components/BannedDialog/BannedDialog.tsx
  src/components/Login/render/Profile/Profile.tsx
  src/components/ProfileCard/ProfileCard.container.tsx
  src/hooks/auth.hook.ts
Labels: Feature

#1079 Fix tipping wallet address, decimal amount & styling
  src/components/common/TermOfService/TermOfService.style.tsx
  src/components/common/TermOfService/TermOfService.tsx
  src/components/common/Tipping/Tipping.tsx
  src/components/common/Tipping/render/FormatCurrency.tsx
  src/components/common/Tipping/render/InputAmount/InputAmount.tsx
  src/components/common/Tipping/render/Summary/Summary.tsx
  src/helpers/balance.ts
  src/hooks/use-polkadot-api.hook.ts
  src/lib/api/post.ts
Labels: bug

#1082 fixed switch network
  pages/home.tsx
  src/components/Manage/Manage.container.tsx
  src/components/ProfileCard/NetworkOption/NetworkOption.tsx
  src/components/ProfileCard/ProfileCard.container.tsx
  src/components/ProfileCard/ProfileCard.interfaces.ts
  src/components/ProfileCard/ProfileCard.tsx
  src/hooks/auth.hook.ts
  src/interfaces/user.ts
  src/lib/api/wallet.ts
Labels: Fix

#1081 Removed Sender Wallet option when Polkadot network is selected
  src/components/Login/render/Options/Options.tsx
Labels: bug

#1083 Limit tipping char length to 10
  src/components/common/Tipping/render/InputAmount/InputAmount.style.ts
  src/components/common/Tipping/render/InputAmount/InputAmount.tsx
Labels: bug

#1085 Change public address on connect social
  src/components/SocialMediaList/SocialMediaList.container.tsx
  src/components/Socials/Socials.container.tsx
  src/components/Socials/Socials.tsx
  src/hooks/use-share-social.ts
  src/reducers/user/actions.ts
Labels: bug

#1088 Update filter transaction history
  src/components/HistoryDetailList/HistoryDetailList.tsx
  src/components/TipHistory/TipHistory.tsx
  src/components/WalletBalance/index.tsx
  src/components/atoms/DropdownMenu/DropdownMenu.tsx
  src/components/common/SendTipButton/SendTipButton.tsx
Labels: bug, enhancement

#1084 change wallet name with capital
  pages/experience/[experienceId]/clone.tsx
  pages/experience/[experienceId]/edit.tsx
  pages/experience/[experienceId]/preview.tsx
  pages/experience/create.tsx
  pages/experience/index.tsx
  pages/friends.tsx
  pages/nft.tsx
  pages/notification.tsx
  pages/profile/[id].tsx
  pages/search.tsx
  pages/settings.tsx
  pages/socials.tsx
  pages/socialtoken.tsx
  pages/topic/[type].tsx
  pages/topic/index.tsx
  src/components/ProfileCard/NetworkOption/NetworkOption.tsx
Labels: Fix

#1089 Filter unavailable currency
  src/components/HistoryDetailList/HistoryDetailList.tsx
  src/components/TipHistory/TipHistory.container.tsx
  src/components/TipHistory/TipHistory.tsx
  src/components/atoms/Icons/Core.tsx
Labels: bug

#1090 Fixed change network
  src/components/ProfileCard/NetworkOption/NetworkOption.tsx
  src/components/WalletBalance/WalletBalanceContainer.tsx
  src/hooks/auth.hook.ts
  src/hooks/use-near-api.hook.ts
  src/hooks/use-polkadot-api.hook.ts
  src/interfaces/user.ts
  src/lib/api/ext-auth.ts
  src/reducers/balance/actions.ts
Labels: Improvement

#1091 wiring claim tip
  .env-template
  next.config.js
  pages/wallet.tsx
  src/components/Tip/Tip.container.tsx
  src/components/Tip/Tip.tsx
  src/hooks/use-claim-tip.hook.ts
  src/interfaces/wallet.ts
  src/lib/api/wallet.ts
  src/lib/services/polkadot-js.ts
  src/reducers/user/actions.ts
  src/reducers/user/constants.ts
  src/reducers/user/reducer.ts
Labels: Feature

#1092 Change profile public key
  src/components/UserSettings/UserSettings.container.tsx
  src/components/UserSettings/UserSettings.tsx
Labels: bug

#1093 Fix transaction history filter
  src/lib/api/transaction.ts
Labels: bug

#1095 add docker build args
  .github/workflows/builder.yml
  .maintain/docker/Dockerfile
Labels: CI

#1096 removed env myriad server id
  .env-template
  next.config.js
  src/components/BalanceDetailList/BalanceDetailList.tsx
  src/components/BalanceDetailList/BalanceDetailListContainer.tsx
  src/components/ProfileCard/ProfileContent.tsx
  src/components/Tip/Tip.container.tsx
  src/hooks/use-claim-tip.hook.ts
  src/lib/api/wallet.ts
Labels: Fix

#1097 Handle connect near failure
  src/components/BalanceDetailList/BalanceDetailList.tsx
  src/components/Manage/Manage.container.tsx
  src/components/atoms/TabList/TabList.tsx
  src/hooks/auth.hook.ts
  src/hooks/use-near-api.hook.ts
  src/lib/api/errors/account-registered.error.ts
  src/lib/api/wallet.ts
  src/lib/services/near-api-js.ts
Labels: bug

#1101 Fixed balance after changed network
  src/hooks/auth.hook.ts
  src/reducers/balance/actions.ts
  src/reducers/user/actions.ts
  src/reducers/user/constants.ts
  src/reducers/user/reducer.ts
Labels: Improvement

#1102 Update profile wallet info
  src/components/Manage/Manage.tsx
  src/components/Manage/use-wallet-list.hook.tsx
  src/components/TipHistory/TipHistory.stories.tsx
  src/components/UserMenu/hooks/user-tabs.hooks.tsx
  src/components/UserSettings/UserSettings.container.tsx
  src/components/UserSettings/UserSettings.styles.ts
  src/components/UserSettings/UserSettings.tsx
  src/interfaces/transaction.ts
  src/interfaces/user.ts
Labels: bug, enhancement

#1103 added shimmer component in claim tip
  src/components/Tip/Shimer.tsx
  src/components/Tip/Tip.container.tsx
Labels: Feature

#1104 Update wallet list styling
  src/components/Manage/Manage.tsx
  src/components/Manage/manage.style.ts
  src/components/Manage/use-wallet-list.hook.tsx
  src/components/UserMenu/hooks/user-tabs.hooks.tsx
  src/components/UserSettings/UserSettings.styles.ts
  src/components/UserSettings/UserSettings.tsx
Labels: bug, enhancement

#1105 Show send tip unavailable for imported post
  src/components/TipHistory/TipHistory.container.tsx
  src/components/common/SendTipButton/SendTipButton.tsx
Labels: enhancement

#1099 Prevent signin on connect wallet
  src/components/Manage/Manage.container.tsx
  src/lib/api/errors/account-banned.error.ts
  src/lib/api/errors/account-registered.error.ts
  src/lib/api/wallet.ts
  src/lib/services/near-api-js.ts
Labels: bug

#1106 Update login redirect on connect near
  pages/index.tsx
  src/components/Login/Login.tsx
  src/components/template/Login/Login.stories.tsx
  src/lib/services/near-api-js.ts
Labels: bug

#1107 Fixed connect to near waller
  next.config.js
  src/interfaces/network.ts
  src/lib/api/network.ts
  src/lib/services/near-api-js.ts
Labels: Improvement

#1108 Fix handle imported post tipping
  src/components/common/SendTipButton/SendTipButton.tsx
  src/interfaces/wallet.ts
Labels: bug

#1100 send tip with near
  src/components/common/Tipping/Tipping.interface.ts
  src/components/common/Tipping/Tipping.provider.tsx
  src/components/common/Tipping/Tipping.tsx
  src/components/common/Tipping/render/FormatCurrency.tsx
  src/components/common/Tipping/render/InputAmount/InputAmount.tsx
  src/components/template/Default/DefaultLayout.tsx
  src/helpers/balance.ts
  src/helpers/string.ts
  src/hooks/use-near-api.hook.ts
  src/lib/services/near-api-js.ts
Labels: Feature, Improvement

#1109 Fix switch wallet
  src/components/Login/Login.tsx
  src/components/Login/render/Options/Options.tsx
  src/components/Manage/Manage.container.tsx
  src/components/ProfileCard/NetworkOption/NetworkOption.tsx
  src/components/common/Tipping/Tipping.tsx
  src/hooks/auth.hook.ts
  src/hooks/use-near-api.hook.ts
  src/lib/services/near-api-js.ts
Labels: bug

#1111 Fix login near when not redirect to near auth page
  src/components/Login/render/Options/Options.tsx
  src/lib/services/near-api-js.ts
Labels: bug

#1112 Handle send tip with tipping pallet
  src/components/CommentDetail/CommentDetail.tsx
  src/components/FriendsMenu/FriendList.tsx
  src/components/ProfileHeader/ProfileHeaderContainer.tsx
  src/components/SendTip/SendTip.tsx
  src/components/atoms/CurrencyOption/index.tsx
  src/components/common/SendTipButton/SendTipButton.tsx
  src/components/common/Tipping/Tipping.interface.ts
  src/components/common/Tipping/Tipping.provider.tsx
  src/components/common/Tipping/Tipping.tsx
  src/hooks/use-polkadot-api.hook.ts
  src/interfaces/transaction.ts
  src/interfaces/wallet.ts
  src/lib/api/comment.ts
  src/lib/api/user.ts
  src/lib/services/polkadot-js.ts
Labels: Improvement

#1110 handle success and reject on tipping with near
  pages/home.tsx
  pages/post/[postId].tsx
  pages/profile/[id].tsx
  src/components/common/Tipping/Tipping.interface.ts
  src/components/common/Tipping/Tipping.provider.tsx
  src/components/common/Tipping/Tipping.tsx
  src/components/common/Tipping/render/Tipping.success.tsx
Labels: Fix, Feature

#1113 Fixed send tip to imported post
  src/components/ProfileCard/NetworkOption/NetworkOption.tsx
  src/components/ProfileCard/ProfileContent.tsx
  src/components/atoms/CurrencyOption/index.tsx
  src/components/common/Tipping/Tipping.tsx
  src/hooks/use-polkadot-api.hook.ts
Labels: Improvement

#1114 read another balance on network near
  src/hooks/use-near-api.hook.ts
  src/lib/services/near-api-js.ts
  src/reducers/balance/actions.ts
Labels: Feature, Improvement

#1115 add button notify on tipping imported post
  src/components/common/Tipping/render/ButtonNotify.tsx
Labels: Improvement

#1117 enable function sending balance beside near
  src/components/common/Tipping/Tipping.tsx
  src/hooks/use-near-api.hook.ts
  src/lib/services/near-api-js.ts
Labels: Fix, Improvement

#1118 Update pagination & filter transaction
  src/components/BalanceDetailList/BalanceDetailList.tsx
  src/components/HistoryDetailList/HistoryDetailList.styles.ts
  src/components/HistoryDetailList/HistoryDetailList.tsx
  src/components/HistoryDetailList/HistoryDetailListContainer.tsx
  src/components/HistoryDetailList/default.ts
  src/components/Timeline/default.ts
  src/components/TipHistory/TipHistory.tsx
  src/components/atoms/DropdownMenu/DropdownMenu.tsx
  src/components/common/CookieConsent/CookieConsent.tsx
  src/hooks/tip-history.hook.ts
  src/hooks/use-transaction.hooks.ts
  src/interfaces/transaction.ts
  src/lib/api/transaction.ts
  src/reducers/comment/reducer.ts
  src/reducers/tip-summary/actions.ts
  src/reducers/tip-summary/reducer.ts
  src/reducers/transaction/actions.ts
  src/reducers/transaction/constants.ts
  src/reducers/transaction/reducer.ts
Labels: bug

#1119 fixed notify tip on reddit
  src/components/common/Tipping/render/ButtonNotify.tsx
Labels: Fix

#1122 Filter unknown currency
  src/hooks/use-transaction.hooks.ts
Labels: bug

#1123 Remove failed option on transaction
  .env-template
  src/components/HistoryDetailList/default.ts
  src/components/Manage/Manage.container.tsx
Labels: bug

#1124 Fix filter reducer tansaction
  src/components/HistoryDetailList/HistoryDetailList.tsx
  src/hooks/use-transaction.hooks.ts
  src/reducers/transaction/actions.ts
  src/reducers/transaction/constants.ts
  src/reducers/transaction/reducer.ts
Labels: bug

#1125 Renamed enum fields
  src/interfaces/wallet.ts
Labels: Improvement

#1127 Fix filter state on change tab
  src/components/HistoryDetailList/HistoryDetailList.tsx
  src/components/HistoryDetailList/HistoryDetailListContainer.tsx
  src/hooks/use-transaction.hooks.ts
Labels: bug

#1129 Updated token name
  src/components/PrimaryCoinMenu/DraggableBalanceCard.tsx
Labels: Fix

#1121 Implement generic type for reusable component
  src/components/BalanceDetailList/BalanceDetailList.tsx
  src/components/CommentHistoryList/CommentHistoryList.tsx
  src/components/FriendsMenu/FriendList.tsx
  src/components/FriendsMenu/FriendMenu.tsx
  src/components/HistoryDetailList/HistoryDetailList.tsx
  src/components/MyWallet/MyWallet.tsx
  src/components/PostCreate/PostCreate.tsx
  src/components/PostDetail/PostDetail.tsx
  src/components/PostsList/PostsList.tsx
  src/components/Profile/tabs/ExperienceTab.tsx
  src/components/RightMenuBar/RightMenuBar.tsx
  src/components/Search/SearchResultContainer.tsx
  src/components/Settings/AccountSettings.tsx
  src/components/Settings/LanguageSetting.tsx
  src/components/Timeline/default.ts
  src/components/Timeline/hooks/use-timeline-filter.hook.ts
  src/components/TimelineFilter/TimelineFilter.container.tsx
  src/components/TimelineFilter/TimelineFilter.tsx
  src/components/TimelineFilter/hooks/use-filter-option.hook.ts
  src/components/TipHistory/TipHistory.tsx
  src/components/UserMenu/UserMenu.tsx
  src/components/atoms/Avatar/Avatar.tsx
  src/components/atoms/DropdownMenu/DropdownMenu.tsx
  src/components/atoms/TabList/TabList.styles.ts
  src/components/atoms/TabList/TabList.tsx
  src/components/atoms/TabPanel/TabPanel.tsx
  src/components/atoms/Tabs/Tabs.stories.tsx
  src/components/atoms/Tabs/Tabs.tsx
  src/interfaces/timeline.ts
Labels: enhancement

#1132 Prevent load balance multiple times
  src/lib/services/polkadot-js.ts
  src/reducers/balance/actions.ts
Labels: bug

#1131 fixed claim tip
  src/components/Tip/Tip.container.tsx
  src/hooks/use-claim-tip.hook.ts
  src/lib/services/polkadot-js.ts
Labels: Fix

#1133 Fixed transaction payload
  src/components/common/Tipping/Tipping.tsx
  src/hooks/use-claim-tip.hook.ts
  src/hooks/use-polkadot-api.hook.ts
  src/interfaces/transaction.ts
  src/lib/api/transaction.ts
Labels: Improvement

#1134 check balance before claim tips
  package.json
  src/components/Tip/Tip.container.tsx
  src/components/common/Tipping/Tipping.provider.tsx
Labels: Fix

#1135 Handle wallet used by other account on switch network
  src/components/ProfileCard/NetworkOption/NetworkOption.tsx
  src/hooks/auth.hook.ts
  src/lib/api/wallet.ts
Labels: bug

#1137 revised sort assets dropdown
  src/components/BalanceDetailList/BalanceDetailList.tsx
  src/components/Timeline/default.ts
Labels: Fix

#1128 Universal tip button
  src/components/CommentDetail/CommentDetail.tsx
  src/components/CommentDetail/CommentRender.tsx
  src/components/CommentList/CommentList.container.tsx
  src/components/PostDetail/PostDetail.styles.ts
  src/components/PostDetail/PostDetail.tsx
  src/components/ProfileHeader/ProfileHeaderContainer.tsx
  src/components/ProfileHeader/index.tsx
  src/components/SendTip/SendTip.styles.ts
  src/components/SendTip/SendTip.tsx
  src/components/SendTip/SendTipContainer.tsx
  src/components/SendTip/ToolTip.tsx
  src/components/SendTip/index.ts
  src/components/Timeline/hooks/use-timeline.hook.ts
  src/components/TipHistory/TipHistory.container.tsx
  src/components/TipHistory/TipHistory.tsx
  src/components/atoms/PostAction/index.tsx
  src/components/atoms/PostAction/postAction.style.ts
  src/components/common/SendTipButton/SendTipButton.style.ts
  src/components/common/SendTipButton/SendTipButton.tsx
  src/components/template/profile/ProfilePage.tsx
  src/hooks/use-polkadot-api.hook.ts
  src/reducers/index.ts
  src/reducers/timeline/actions.ts
  src/reducers/timeline/constants.ts
  src/reducers/timeline/reducer.ts
  src/reducers/wallet/actions.ts
  src/reducers/wallet/constants.ts
  src/reducers/wallet/reducer.ts
  src/stories/SendTip.stories.tsx
Labels: enhancement

#1140 wired switch network based on DB
  pages/experience/[experienceId]/clone.tsx
  pages/experience/[experienceId]/edit.tsx
  pages/experience/[experienceId]/preview.tsx
  pages/experience/create.tsx
  pages/experience/index.tsx
  pages/friends.tsx
  pages/home.tsx
  pages/nft.tsx
  pages/notification.tsx
  pages/post/[postId].tsx
  pages/profile/[id].tsx
  pages/search.tsx
  pages/settings.tsx
  pages/socials.tsx
  pages/socialtoken.tsx
  src/components/Mobile/MenuDrawer/MenuDrawer.tsx
  src/components/ProfileCard/NetworkOption/NetworkOption.tsx
  src/components/ProfileCard/ProfileCard.container.tsx
  src/components/ProfileCard/ProfileCard.interfaces.ts
  src/components/ProfileCard/ProfileCard.tsx
  src/components/ProfileCard/ProfileContent.tsx
  src/components/Tip/Tip.container.tsx
  src/components/Tip/Tip.tsx
  src/components/TipHistory/TipHistory.stories.tsx
  src/components/common/Tipping/Tipping.tsx
  src/components/template/Default/DefaultLayout.tsx
  src/components/template/home/HomePage.stories.tsx
  src/components/template/home/HomePage.tsx
  src/components/template/home/home-page.style.ts
  src/components/template/profile/ProfilePage.stories.tsx
  src/components/template/profile/ProfilePage.tsx
  src/components/template/profile/profile-page.style.ts
  src/hooks/auth.hook.ts
  src/hooks/use-claim-tip.hook.ts
  src/interfaces/user.ts
Labels: Fix

#1139 fix send tip behavior
  src/components/common/SendTipButton/SendTipButton.tsx
  src/components/common/Tipping/Tipping.context.ts
  src/components/common/Tipping/Tipping.provider.tsx
  src/reducers/balance/actions.ts
  src/reducers/balance/reducer.ts
Labels: bug, Fix

#1144 improve test and build pipeline
  .github/workflows/analyzer.yml
  .github/workflows/builder.yml
  .github/workflows/tester.yml
Labels: CI

#1138 Fix disable button on edit experience
  src/components/Expericence/Experience.tsx
  src/components/ExperienceEditor/Experience.container.tsx
  src/components/ExperienceEditor/ExperienceEditor.tsx
  src/components/ExperiencePreview/ExperienceClone.container.tsx
  src/components/ExperiencePreview/ExperienceEdit.container.tsx
Labels: bug

#1142 wired network login based on DB
  pages/index.tsx
  src/components/Login/Login.tsx
  src/components/Login/render/Options/Options.style.ts
  src/components/Login/render/Options/Options.tsx
  src/components/Login/render/Profile/Profile.tsx
  src/components/ProfileCard/ProfileCard.container.tsx
  src/components/ProfileCard/ProfileCard.interfaces.ts
  src/components/ProfileCard/ProfileCard.tsx
  src/components/template/Login/Login.styles.ts
  src/hooks/auth.hook.ts
  src/reducers/user/actions.ts
Labels: Improvement

#1145 Fix load balance on myriad network
  package.json
  src/components/common/Tipping/render/ButtonNotify.tsx
  src/hooks/use-polkadot-api.hook.ts
  src/reducers/balance/actions.ts
Labels: bug, Fix

#1146 fix show wallet address near on profile card
  src/components/ProfileCard/ProfileCard.tsx
  src/hooks/use-polkadot-api.hook.ts
  src/reducers/balance/actions.ts
  src/reducers/user/actions.ts
Labels: bug, Fix

#1147 disabled button claim while claiming tip
  src/components/Tip/Tip.container.tsx
  src/components/Tip/Tip.tsx
  src/components/Tip/tip.style.ts
  src/hooks/use-claim-tip.hook.ts
  src/lib/services/polkadot-js.ts
Labels: Improvement

#1149 Fix floating point number on format balance
  src/helpers/balance.ts
  src/helpers/string.ts
Labels: bug

#1151 Changed the order of RPC list on login page
  src/reducers/user/actions.ts
Labels: Fix

#1150 simplified error text when tipping address is not found
  pages/post/[postId].tsx
  src/components/common/SendTipButton/SendTipButton.tsx
Labels: Fix, Improvement

#1152 fixed login as anonymous demo
  pages/experience/[experienceId]/clone.tsx
  pages/experience/[experienceId]/edit.tsx
  pages/experience/[experienceId]/preview.tsx
  pages/experience/create.tsx
  pages/experience/index.tsx
  pages/friends.tsx
  pages/home.tsx
  pages/nft.tsx
  pages/notification.tsx
  pages/post/[postId].tsx
  pages/profile/[id].tsx
  pages/search.tsx
  pages/settings.tsx
  pages/socials.tsx
  pages/socialtoken.tsx
  pages/topic/[type].tsx
  pages/topic/index.tsx
  pages/wallet.tsx
  src/components/ProfileCard/ProfileCard.container.tsx
  src/components/ProfileCard/ProfileCard.interfaces.ts
  src/components/ProfileCard/ProfileCard.tsx
  src/components/ProfileCard/ProfileContent.tsx
  src/components/ProfileCard/profileContent.style.ts
Labels: bug
