Repository myriadsocial/myriad-web, pull requests merged in 2023-04, with the labels that each got.

#1792 feat: update indonesian translation
  src/locale/id.json
Labels: Fix

#1808 fix: behaviour subscribe/unsubscribe discoverd
  src/components/Expericence/Experience.tsx
  src/reducers/user/reducer.ts
Labels: Fix

#1809 feat: notification setting
  src/components/Settings/hooks/use-notification-setting.hook.ts
  src/interfaces/setting.ts
  src/locale/en.json
  src/locale/id.json
  src/locale/ru.json
  src/reducers/config/reducer.ts
Labels: Feature

#1815 fix: remove limitation when clone experience
  pages/experience/[experienceId]/clone.tsx
  src/components/ExperienceList/ExperienceList.container.tsx
  src/components/ExperiencePreview/ExperiencePreview.container.tsx
Labels: Improvement

#1817 fix: user not found on edit experience
  pages/experience/[experienceId]/edit.tsx
Labels: Improvement
