Repository myriadsocial/myriad-web, pull requests merged in 2023-03, with the labels that each got.

#1740 fix: call function isSubscribe
  src/components/Timeline/Render/ExperienceCard.tsx
Labels: Fix

#1741 fix: hotfix payment exclusive content
  src/components/common/Tipping/Tipping.tsx
  src/components/common/Tipping/render/FormatCurrency.tsx
  src/lib/services/polkadot-js.ts
Labels: Improvement

#1745 fix: enable web2 account to edit images
  src/components/ProfileEdit/IconButtonUpload.component.tsx
  src/components/ProfileEdit/ImageButton.component.tsx
Labels: Fix

#1747 fix: improved formatted balance when inputted
  src/components/ExclusiveContentCreate/InputAmount/InputAmount.tsx
  src/components/common/Tipping/Tipping.tsx
  src/components/common/Tipping/render/FormatCurrency.tsx
  src/components/common/Tipping/render/InputAmount/InputAmount.tsx
  src/helpers/balance.ts
  src/hooks/use-near-api.hook.ts
  src/hooks/use-polkadot-api.hook.ts
  src/hooks/use-wallet-hook.ts
  src/lib/services/near-api-js.ts
  src/lib/services/polkadot-js.ts
Labels: Improvement

#1748 fix: change add to timeline button style
  src/components/PostDetail/render/AddToTimeline/AddToTimeline.tsx
Labels: Fix

#1749 fix: remove text from exclusive content modal
  src/components/ExclusiveContentCreate/ExclusiveCreate.tsx
Labels: Fix

#1751 fix: fixed formatted balance
  src/components/BalanceDetailList/BalanceDetailList.tsx
  src/helpers/balance.ts
Labels: Improvement

#1752 fix: remove create timeline limitation
  src/components/RightMenuBar/tabs/ExperienceTab.tsx
Labels: Improvement

#1739 chore(main): release 2.3.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1759 fix: overlapping link in comment detail
  src/components/CommentDetail/CommentDetail.styles.ts
Labels: Fix

#1760 fix: remove attach button wording and change icon to giftIcon
  src/components/CommentEditor/CommentActionMobile.tsx
Labels: Fix

#1761 chore(main): release 2.3.2
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1767 fix: tipping
  package.json
  src/components/common/SendTipButton/SendTipButton.tsx
  src/locale/en.json
  src/locale/id.json
  src/locale/ru.json
  yarn.lock
Labels: Fix

#1770 fix: wrong time on imported post
  src/components/PostDetail/render/Header/Header.tsx
Labels: Improvement

#1766 chore(main): release 2.3.3
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1773 fix: handle claim tip with debio
  src/components/Tip/Tip.container.tsx
  src/hooks/use-claim-tip.hook.ts
  src/hooks/use-polkadot-api.hook.ts
Labels: Improvement

#1774 fix: sticky navbar
  pages/index.tsx
Labels: Fix

#1777 fix: near tip redirect
  src/components/common/SendTipButton/SendTipButton.tsx
Labels: Fix

#1779 fix: fixed mentions data on post creation
  src/components/CommentEditor/formatter.ts
  src/components/PostCreate/formatter.ts
  src/components/common/Editor/Editor.interface.ts
  src/components/common/NodeViewer/NodeViewer.tsx
  src/components/common/NodeViewer/formatter.ts
Labels: Improvement

#1780 fix: selected user ids interfaces on experience
  pages/experience/[experienceId]/clone.tsx
  pages/experience/[experienceId]/index.tsx
  src/components/ExperienceEditor/ExperienceEditor.tsx
  src/components/ExperiencePreview/ExperiencePreview.tsx
  src/interfaces/experience.ts
  src/locale/en.json
  src/locale/id.json
  src/locale/ru.json
Labels: Improvement

#1781 fix: send tip modal
  package.json
  src/components/common/SendTipButton/SendTipButton.tsx
  yarn.lock
Labels: Fix
