Repository myriadsocial/myriad-web, pull requests merged in 2023-02, with the labels that each got.

#1689 fix: refetch network when change instance
  src/components/Login/render/Options/Options.tsx
Labels: Improvement

#1695 fix: improved selected instance
  @types/next-auth.d.ts
  pages/api/[...all].ts
  pages/api/auth/[...nextauth].ts
  pages/experience/[experienceId]/clone.tsx
  pages/experience/[experienceId]/edit.tsx
  pages/experience/[experienceId]/index.tsx
  pages/experience/create.tsx
  pages/experience/index.tsx
  pages/experience/trending.tsx
  pages/friends.tsx
  pages/index.tsx
  pages/leaderboard.tsx
  pages/login.tsx
  pages/nft.tsx
  pages/notification.tsx
  pages/post/[postId].tsx
  pages/profile/[id].tsx
  pages/search.tsx
  pages/settings.tsx
  pages/socials.tsx
  pages/socialtoken.tsx
  pages/topic/[type].tsx
  pages/topic/index.tsx
  pages/town.tsx
  pages/wallet.tsx
  src/components/Login/render/CreateAccounts/CreateAccounts.tsx
  src/components/Login/render/Email/LoginByEmail.tsx
  src/components/Login/render/Options/Options.tsx
  src/components/Menu/Menu.styles.ts
  src/components/Menu/Menu.tsx
  src/components/Mobile/Navbar/Navbar.tsx
  src/components/ProfileCard/ProfileCard.tsx
  src/components/Search/SearchResultContainer.tsx
  src/components/SelectServer.tsx
  src/components/SelectServer/InstanceCard.tsx
  src/components/SelectServer/InstanceCardSkeleton.tsx
  src/components/SelectServer/SelectServer.styles.ts
  src/components/SelectServer/index.tsx
  src/components/WalletBalance/WalletBalanceContainer.tsx
  src/components/template/Default/DefaultLayout.tsx
  src/hooks/auth.hook.ts
  src/hooks/use-instances.hooks.ts
  src/interfaces/server-list.ts
  src/interfaces/session.ts
  src/lib/api/auth-link.ts
  src/lib/api/ext-auth.ts
  src/lib/api/network.ts
  src/lib/api/server.ts
  src/lib/serializers/session.ts
  src/lib/services/near-api-js.ts
  src/reducers/index.ts
  src/reducers/server/actions.ts
  src/reducers/server/constants.ts
  src/reducers/server/reducer.ts
Labels: Improvement

#1697 fix: switch instance with email
  src/components/Menu/Menu.tsx
  src/hooks/auth.hook.ts
  src/hooks/use-instances.hooks.ts
Labels: Improvement

#1698 fix: improved selected instance as anonymous user
  pages/api/[...all].ts
  pages/api/auth/[...nextauth].ts
  pages/experience/[experienceId]/clone.tsx
  pages/experience/[experienceId]/edit.tsx
  pages/experience/[experienceId]/index.tsx
  pages/experience/create.tsx
  pages/experience/index.tsx
  pages/experience/trending.tsx
  pages/friends.tsx
  pages/index.tsx
  pages/login.tsx
  pages/nft.tsx
  pages/notification.tsx
  pages/post/[postId].tsx
  pages/profile/[id].tsx
  pages/search.tsx
  pages/settings.tsx
  pages/socials.tsx
  pages/socialtoken.tsx
  pages/topic/[type].tsx
  pages/topic/index.tsx
  pages/town.tsx
  pages/wallet.tsx
  src/components/ExperiencePreview/ExperienceSignIn.tsx
  src/components/Login/Login.tsx
  src/components/Login/render/CreateAccounts/CreateAccounts.tsx
  src/components/Login/render/Email/LoginByEmail.tsx
  src/components/Login/render/Options/Options.tsx
  src/components/Login/render/Profile/Profile.tsx
  src/components/Menu/Menu.tsx
  src/components/Mobile/MenuDrawer/MenuDrawer.tsx
  src/components/ProfileCard/ProfileCard.container.tsx
  src/components/SelectServer/InstanceCard.tsx
  src/components/SelectServer/index.tsx
  src/components/common/Blockchain/Blockchain.context.ts
  src/components/common/Blockchain/Blockchain.provider.tsx
  src/components/template/Default/DefaultLayout.tsx
  src/hooks/auth-link.hook.ts
  src/hooks/auth.hook.ts
  src/hooks/use-instances.hooks.ts
  src/lib/api/auth-link.ts
  src/lib/api/network.ts
  src/lib/api/user.ts
  src/lib/api/wallet.ts
Labels: Improvement

#1700 fix: network option not shown on login page
  pages/login.tsx
  src/components/Login/render/Options/Options.tsx
  src/components/SelectServer/index.tsx
Labels: Improvement

#1708 fix: session user
  next.config.js
Labels: Fix

#1709 fix: api url healthcheck on serverside pages
  @types/next-auth.d.ts
  pages/_middleware.ts
  pages/api/auth/[...nextauth].ts
  pages/experience/[experienceId]/clone.tsx
  pages/experience/[experienceId]/edit.tsx
  pages/experience/[experienceId]/index.tsx
  pages/experience/create.tsx
  pages/experience/index.tsx
  pages/experience/trending.tsx
  pages/friends.tsx
  pages/index.tsx
  pages/login.tsx
  pages/nft.tsx
  pages/notification.tsx
  pages/post/[postId].tsx
  pages/profile/[id].tsx
  pages/search.tsx
  pages/settings.tsx
  pages/socials.tsx
  pages/socialtoken.tsx
  pages/topic/[type].tsx
  pages/topic/index.tsx
  pages/town.tsx
  pages/wallet.tsx
  src/components/FriendsMenu/FriendList.tsx
  src/components/Login/Login.tsx
  src/components/Login/render/Email/LoginByEmail.tsx
  src/components/Login/render/Options/Options.tsx
  src/components/SelectServer/index.tsx
  src/helpers/auth.ts
  src/hooks/auth.hook.ts
  src/hooks/use-instances.hooks.ts
  src/interfaces/session.ts
  src/lib/api/healthcheck.ts
  src/lib/serializers/session.ts
Labels: Improvement

#1710 fix: handle create transaction when exclusive payment
  src/components/common/Tipping/Tipping.tsx
  src/hooks/use-wallet-hook.ts
  src/interfaces/blockchain-interface.ts
  src/lib/services/polkadot-js.ts
Labels: Improvement

#1711 fix: handle exclusive payment to escrow
  src/hooks/use-wallet-hook.ts
Labels: Improvement

#1712 fix: handle escrow tipping / reveal content with DeBio Network
  src/components/ExclusiveContentCreate/CurrencyOption.tsx
Labels: Improvement

#1713 fix: fixed authentication with email
  @types/next-auth.d.ts
  pages/api/[...all].ts
  pages/api/auth/[...nextauth].ts
  src/hooks/auth-link.hook.ts
  src/hooks/use-instances.hooks.ts
  src/interfaces/session.ts
  src/lib/api/auth-link.ts
  src/lib/api/ext-auth.ts
  src/lib/serializers/session.ts
  src/reducers/base/reducer.ts
Labels: Improvement

#1714 fix: change to keydown and change type to search
  src/components/SocialMediaList/SocialMediaList.container.test.tsx
  src/components/atoms/Search/SearchBox.tsx
Labels: Fix

#1715 fix: update user session detail
  @types/next-auth.d.ts
  pages/api/auth/[...nextauth].ts
  src/components/SelectServer/index.tsx
  src/hooks/auth.hook.ts
  src/hooks/use-instances.hooks.ts
  src/interfaces/session.ts
  src/lib/serializers/session.ts
Labels: Improvement

#1717 fix: change date field on post detail
  src/components/PostDetail/render/Header/Header.tsx
  src/components/PostDetailExperience/PostDetailExperienceHeader.tsx
  src/components/PostHeader/index.tsx
Labels: Improvement

#1719 fix: enable web2 user to edit profile
  src/components/Profile/Profile.tsx
  src/locale/en.json
  src/locale/id.json
  src/locale/ru.json
Labels: Fix

#1720 fix: enable web2 user to create exclusive content
  src/components/PostCreate/PostCreate.tsx
Labels: Fix

#1725 fix: update detail when navigate between post detail
  src/components/PostDetail/PostDetail.container.tsx
Labels: bug, Fix

#1726 fix: enable web2 account to edit bio and web
  src/components/ProfileEdit/ProfileEdit.tsx
Labels: Fix

#1727 fix: enable Web2 User to Create Exclusive Content when post a comment
  src/components/CommentEditor/CommentAction.tsx
  src/components/CommentEditor/CommentActionMobile.tsx
  src/components/CommentEditor/CommentEditor.tsx
  src/hooks/use-experience-hook.ts
  src/locale/en.json
  src/locale/id.json
  src/locale/ru.json
Labels: Fix

#1730 Fix/myr 2952
  src/components/CommentHistory/CommentHistory.tsx
  src/helpers/string.ts
Labels: Fix

#1732 fix: handle logout with dynamic callback url
  src/hooks/auth.hook.ts
Labels: Improvement

#1734 fix: handle error fetch experience by id
  src/components/PostVisibility/PostVisibility.tsx
Labels: Improvement

#1729 chore(main): release 2.3.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1737 fix: error tab comment
  src/helpers/string.ts
Labels: Fix
